-- DragonUI_NewEra/modules/cooldownviewer/CdmArsenal.lua — GENERATED, DO NOT HAND-EDIT.
--
-- The full per-class pool of abilities carrying a real cooldown (> 1.5s), keyed rank-1. This is what
-- the settings panel offers under "Not Displayed": the arsenal a player can ADD to a viewer, as
-- opposed to the curated defaults that start there.
--
-- Upstream ships the equivalent as a generated NE_CDM_HIDDEN global. Ours is a module table so it
-- cannot collide with anything, and it is regenerated by tools/cdm-spellgen/gen_arsenal.py from this
-- client's own Spell.dbc + SkillLineAbility.dbc — no id is typed by hand.
--
-- Curated ids are deliberately still present here. The adapter subtracts whatever currently sits in
-- a viewer, so anything already in Essential/Utility never shows up there anyway; baking that
-- exclusion into the data would rot the moment the curated lists changed.
--
-- KNOWN GAP: Data/patch-4.MPQ and patch-S.mpq are encrypted and unreadable, so if this server
-- overrides spell data there, these ids reflect the stock client.

local NE = DragonUI_NewEra
NE.cooldownviewer = NE.cooldownviewer or {}
local M = NE.cooldownviewer

M.ARSENAL_BY_CLASS = {

  DEATHKNIGHT = {
    48707,   -- Anti-Magic Shell
    51052,   -- Anti-Magic Zone
    42650,   -- Army of the Dead
    45529,   -- Blood Tap
    49222,   -- Bone Shield
    49158,   -- Corpse Explosion
    49028,   -- Dancing Rune Weapon
    56222,   -- Dark Command
    43265,   -- Death and Decay
    50977,   -- Death Gate
    49576,   -- Death Grip
    48743,   -- Death Pact
    50033,   -- Death Rune Mastery
    49796,   -- Deathchill
    47568,   -- Empower Rune Weapon
    57532,   -- Eye of Acherus
    63560,   -- Ghoul Frenzy
    57330,   -- Horn of Winter
    49184,   -- Howling Blast
    49203,   -- Hungering Cold
    49016,   -- Hysteria
    48792,   -- Icebound Fortitude
    52372,   -- Icy Touch
    49039,   -- Lichborne
    49005,   -- Mark of Blood
    47528,   -- Mind Freeze
    61999,   -- Raise Ally
    46584,   -- Raise Dead
    48982,   -- Rune Tap
    47476,   -- Strangulate
    49206,   -- Summon Gargoyle
    51271,   -- Unbreakable Armor
    55233,   -- Vampiric Blood
  },
  DRUID = {
    22812,   -- Barkskin
    5211,   -- Bash
    50334,   -- Berserk
    5209,   -- Challenging Roar
    8998,   -- Cower
    1850,   -- Dash
    5229,   -- Enrage
    16857,   -- Faerie Fire (Feral)
    16979,   -- Feral Charge - Bear
    49376,   -- Feral Charge - Cat
    33831,   -- Force of Nature
    22842,   -- Frenzied Regeneration
    6795,   -- Growl
    29166,   -- Innervate
    22570,   -- Maim
    33878,   -- Mangle (Bear)
    16689,   -- Nature's Grasp
    17116,   -- Nature's Swiftness
    5215,   -- Prowl
    20484,   -- Rebirth
    48505,   -- Starfall
    61336,   -- Survival Instincts
    18562,   -- Swiftmend
    5217,   -- Tiger's Fury
    740,   -- Tranquility
    50516,   -- Typhoon
    48438,   -- Wild Growth
  },
  HUNTER = {
    19434,   -- Aimed Shot
    3044,   -- Arcane Shot
    19574,   -- Bestial Wrath
    3674,   -- Black Arrow
    62757,   -- Call Stabled Pet
    53209,   -- Chimera Shot
    5116,   -- Concussive Shot
    19306,   -- Counterattack
    19263,   -- Deterrence
    781,   -- Disengage
    20736,   -- Distracting Shot
    53301,   -- Explosive Shot
    13813,   -- Explosive Trap
    6991,   -- Feed Pet
    5384,   -- Feign Death
    1543,   -- Flare
    60192,   -- Freezing Arrow
    1499,   -- Freezing Trap
    13809,   -- Frost Trap
    13795,   -- Immolation Trap
    19577,   -- Intimidation
    34026,   -- Kill Command
    53351,   -- Kill Shot
    56453,   -- Lock and Load
    53271,   -- Master's Call
    34477,   -- Misdirection
    1495,   -- Mongoose Bite
    2643,   -- Multi-Shot
    3045,   -- Rapid Fire
    2973,   -- Raptor Strike
    23989,   -- Readiness
    1513,   -- Scare Beast
    19503,   -- Scatter Shot
    34490,   -- Silencing Shot
    34600,   -- Snake Trap
    19801,   -- Tranquilizing Shot
    3034,   -- Viper Sting
    19386,   -- Wyvern Sting
  },
  MAGE = {
    44425,   -- Arcane Barrage
    12042,   -- Arcane Power
    11113,   -- Blast Wave
    1953,   -- Blink
    11958,   -- Cold Snap
    11129,   -- Combustion
    120,   -- Cone of Cold
    2139,   -- Counterspell
    44572,   -- Deep Freeze
    31661,   -- Dragon's Breath
    12051,   -- Evocation
    2136,   -- Fire Blast
    543,   -- Fire Ward
    122,   -- Frost Nova
    6143,   -- Frost Ward
    11426,   -- Ice Barrier
    45438,   -- Ice Block
    12472,   -- Icy Veins
    66,   -- Invisibility
    55342,   -- Mirror Image
    53142,   -- Portal: Dalaran
    11419,   -- Portal: Darnassus
    32266,   -- Portal: Exodar
    11416,   -- Portal: Ironforge
    11417,   -- Portal: Orgrimmar
    33691,   -- Portal: Shattrath
    32267,   -- Portal: Silvermoon
    49361,   -- Portal: Stonard
    10059,   -- Portal: Stormwind
    49360,   -- Portal: Theramore
    11420,   -- Portal: Thunder Bluff
    11418,   -- Portal: Undercity
    12043,   -- Presence of Mind
    43987,   -- Ritual of Refreshment
    31687,   -- Summon Water Elemental
    70909,   -- Summon Water Elemental (Prototype)
  },
  PALADIN = {
    31821,   -- Aura Mastery
    31935,   -- Avenger's Shield
    31884,   -- Avenging Wrath
    26573,   -- Consecration
    35395,   -- Crusader Strike
    20216,   -- Divine Favor
    31842,   -- Divine Illumination
    19752,   -- Divine Intervention
    54428,   -- Divine Plea
    498,   -- Divine Protection
    64205,   -- Divine Sacrifice
    642,   -- Divine Shield
    53385,   -- Divine Storm
    879,   -- Exorcism
    853,   -- Hammer of Justice
    53595,   -- Hammer of the Righteous
    24275,   -- Hammer of Wrath
    1044,   -- Hand of Freedom
    1022,   -- Hand of Protection
    62124,   -- Hand of Reckoning
    6940,   -- Hand of Sacrifice
    1038,   -- Hand of Salvation
    20925,   -- Holy Shield
    20473,   -- Holy Shock
    2812,   -- Holy Wrath
    53407,   -- Judgement of Justice
    20271,   -- Judgement of Light
    53408,   -- Judgement of Wisdom
    633,   -- Lay on Hands
    20066,   -- Repentance
    31789,   -- Righteous Defense
    53600,   -- Shield of Righteousness
  },
  PRIEST = {
    34861,   -- Circle of Healing
    19236,   -- Desperate Prayer
    47585,   -- Dispersion
    64843,   -- Divine Hymn
    586,   -- Fade
    6346,   -- Fear Ward
    47788,   -- Guardian Spirit
    14914,   -- Holy Fire
    64901,   -- Hymn of Hope
    14751,   -- Inner Focus
    724,   -- Lightwell
    8092,   -- Mind Blast
    33206,   -- Pain Suppression
    47540,   -- Penance
    10060,   -- Power Infusion
    17,   -- Power Word: Shield
    33076,   -- Prayer of Mending
    64044,   -- Psychic Horror
    8122,   -- Psychic Scream
    32379,   -- Shadow Word: Death
    34433,   -- Shadowfiend
    15487,   -- Silence
  },
  ROGUE = {
    13750,   -- Adrenaline Rush
    13877,   -- Blade Flurry
    2094,   -- Blind
    31224,   -- Cloak of Shadows
    14177,   -- Cold Blood
    51722,   -- Dismantle
    1725,   -- Distract
    5277,   -- Evasion
    1966,   -- Feint
    14278,   -- Ghostly Strike
    1776,   -- Gouge
    1766,   -- Kick
    408,   -- Kidney Shot
    51690,   -- Killing Spree
    14183,   -- Premeditation
    14185,   -- Preparation
    14251,   -- Riposte
    51713,   -- Shadow Dance
    36554,   -- Shadowstep
    2983,   -- Sprint
    1784,   -- Stealth
    57934,   -- Tricks of the Trade
    1856,   -- Vanish
  },
  SHAMAN = {
    556,   -- Astral Recall
    2825,   -- Bloodlust
    421,   -- Chain Lightning
    2062,   -- Earth Elemental Totem
    8042,   -- Earth Shock
    2484,   -- Earthbind Totem
    16166,   -- Elemental Mastery
    51533,   -- Feral Spirit
    2894,   -- Fire Elemental Totem
    1535,   -- Fire Nova
    8050,   -- Flame Shock
    8056,   -- Frost Shock
    30874,   -- Gift of the Water Spirit
    8177,   -- Grounding Totem
    32182,   -- Heroism
    51514,   -- Hex
    51505,   -- Lava Burst
    60103,   -- Lava Lash
    16190,   -- Mana Tide Totem
    16188,   -- Nature's Swiftness
    20608,   -- Reincarnation
    61295,   -- Riptide
    30823,   -- Shamanistic Rage
    5730,   -- Stoneclaw Totem
    17364,   -- Stormstrike
    51490,   -- Thunderstorm
    55198,   -- Tidal Force
    57994,   -- Wind Shear
  },
  WARLOCK = {
    59671,   -- Challenging Howl
    50796,   -- Chaos Bolt
    17962,   -- Conflagrate
    603,   -- Curse of Doom
    6789,   -- Death Coil
    54785,   -- Demon Charge
    48020,   -- Demonic Circle: Teleport
    47193,   -- Demonic Empowerment
    18708,   -- Fel Domination
    48181,   -- Haunt
    5484,   -- Howl of Terror
    50589,   -- Immolation Aura
    1122,   -- Inferno
    47241,   -- Metamorphosis
    18540,   -- Ritual of Doom
    29893,   -- Ritual of Souls
    698,   -- Ritual of Summoning
    50581,   -- Shadow Cleave
    6229,   -- Shadow Ward
    17877,   -- Shadowburn
    47897,   -- Shadowflame
    30283,   -- Shadowfury
    29858,   -- Soulshatter
  },
  WARRIOR = {
    18499,   -- Berserker Rage
    46924,   -- Bladestorm
    2687,   -- Bloodrage
    23881,   -- Bloodthirst
    1161,   -- Challenging Shout
    100,   -- Charge
    12809,   -- Concussion Blow
    12292,   -- Death Wish
    676,   -- Disarm
    55694,   -- Enraged Regeneration
    60970,   -- Heroic Fury
    57755,   -- Heroic Throw
    20252,   -- Intercept
    3411,   -- Intervene
    5246,   -- Intimidating Shout
    12975,   -- Last Stand
    694,   -- Mocking Blow
    12294,   -- Mortal Strike
    7384,   -- Overpower
    6552,   -- Pummel
    1719,   -- Recklessness
    20230,   -- Retaliation
    6572,   -- Revenge
    64382,   -- Shattering Throw
    72,   -- Shield Bash
    2565,   -- Shield Block
    23922,   -- Shield Slam
    871,   -- Shield Wall
    46968,   -- Shockwave
    23920,   -- Spell Reflection
    12328,   -- Sweeping Strikes
    355,   -- Taunt
    6343,   -- Thunder Clap
    1680,   -- Whirlwind
  },
}

if M.InvalidateCuratedCache then M.InvalidateCuratedCache() end
