"""Generates modules/cooldownviewer/CdmArsenal.lua — the full per-class pool of trackable abilities.

This is the 3.3.5a equivalent of upstream's generated NE_CDM_HIDDEN table, and it is what makes the
settings panel's "Not Displayed" section a real SPELL PICKER rather than a list of things you already
removed. Without it the panel can only re-offer curated defaults, so a player could never add an
ability the curation left out.

Definition of "trackable" matches what the cooldown viewer itself reads: the rank-1 castable id of
any class ability with a real cooldown (> 1.5s). That is exactly resolve.py's output, so this script
is a thin emitter over resolved.json rather than new analysis.

Curated ids are NOT excluded. The adapter subtracts whatever is currently in a viewer at runtime, so
an ability in Essential simply does not appear in the catalog; baking the exclusion in would break the
moment the curation changed.
"""
import json, sys

HEADER = '''-- DragonUI_NewEra/modules/cooldownviewer/CdmArsenal.lua — GENERATED, DO NOT HAND-EDIT.
--
-- The full per-class pool of abilities carrying a real cooldown (> 1.5s), keyed rank-1. This is what
-- the settings panel offers under "Not Displayed": the arsenal a player can ADD to a viewer, as
-- opposed to the curated defaults that start there.
--
-- Upstream ships the equivalent as a generated NE_CDM_HIDDEN global. Ours is a module table so it
-- cannot collide with anything, and it is regenerated by tools/cdm-spellgen/gen_arsenal.py from this
-- client's own Spell.dbc + SkillLineAbility.dbc — no id is typed by hand.
--
-- Curated ids are deliberately still present here. The adapter subtracts whatever currently sits in
-- a viewer, so anything already in Essential/Utility never shows up there anyway; baking that
-- exclusion into the data would rot the moment the curated lists changed.
--
-- KNOWN GAP: Data/patch-4.MPQ and patch-S.mpq are encrypted and unreadable, so if this server
-- overrides spell data there, these ids reflect the stock client.

local NE = DragonUI_NewEra
NE.cooldownviewer = NE.cooldownviewer or {}
local M = NE.cooldownviewer

M.ARSENAL_BY_CLASS = {
'''


def main():
    try:
        resolved = json.load(open("resolved.json", encoding="utf-8"))
    except FileNotFoundError:
        sys.exit("resolved.json missing — run dbc.py then resolve.py first")
    try:
        spells = json.load(open("spells.json", encoding="utf-8"))
    except FileNotFoundError:
        sys.exit("spells.json missing — run dbc.py first")
    byid = {int(k): v for k, v in spells.items()}

    out = [HEADER]
    total = 0
    for cls in sorted(resolved):
        entries = sorted(resolved[cls].items(), key=lambda kv: kv[0].lower())
        out.append(f"  {cls} = {{")
        for name, sid in entries:
            # Re-read the name from the DBC rather than trusting the key, so a mismatch shows up in
            # review instead of being carried silently into the comment.
            real = byid.get(sid, ["?", ""])[0]
            out.append(f"    {sid},   -- {real}")
            total += 1
        out.append("  },")
    out.append("}")
    out.append("")
    # The learn-gate's class-ability set is memoised, and it now reads this table (§H.3.21). This
    # file loads after CooldownViewer.lua, so drop the cache the same way CdmSeedWotLK.lua does
    # rather than relying on nothing having asked yet.
    out.append("if M.InvalidateCuratedCache then M.InvalidateCuratedCache() end")

    path = "../../modules/cooldownviewer/CdmArsenal.lua"
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")

    print(f"wrote {path}")
    for cls in sorted(resolved):
        print(f"  {cls:12s} {len(resolved[cls]):3d}")
    print(f"  {'TOTAL':12s} {total:3d}")


if __name__ == "__main__":
    main()
