--[[
================================================================================
DragonUI_NewEra - Latin American Spanish Locale (esMX)

Generated by tools/locale-lint/gen_locale.py from enUS.lua; edit the translation
map in tools/locale-lint/translations/esMX.py and regenerate, or correct a
string here and port the fix back. Entries left as `= true` fall back to English.

Machine-drafted and unreviewed by a native speaker: corrections welcome. Every
entry is checked against its English key for placeholder parity
(check_keys.py --verify), so a %d or |n cannot go missing, but wording has not
been through a human pass.
================================================================================
]]

local L = LibStub("AceLocale-3.0"):NewLocale("DragonUI_NewEra", "esMX")
if not L then return end
-- ============================================================================
-- ============================================================================
L["Alchemy"] = "Alquimia"
L["Blacksmithing"] = "Herrería"
L["Enchanting"] = "Encantamiento"
L["Engineering"] = "Ingeniería"
L["Herbalism"] = "Herboristería"
L["Leatherworking"] = "Peletería"
L["Mining"] = "Minería"
L["Smelting"] = "Fundición"
L["Skinning"] = "Desuello"
L["Tailoring"] = "Sastrería"
L["Inscription"] = "Inscripción"
L["Jewelcrafting"] = "Joyería"
L["Prospecting"] = "Prospección"
L["Cooking"] = "Cocina"
L["First Aid"] = "Primeros auxilios"
L["Fishing"] = "Pesca"
L["Select a recipe to craft"] = "Selecciona una receta para fabricar"
L["Hide item tooltips in list"] = "Ocultar descripciones de objetos en la lista"
L["Colour names by skill difficulty"] = "Colorear nombres según la dificultad"
L["Plain skill bar (no animation)"] = "Barra de habilidad simple (sin animación)"
L["Create"] = "Crear"
L["Create All"] = "Crear todo"
L["Show Learned"] = "Mostrar aprendidas"
L["Has Skill Up"] = "Sube habilidad"
L["Have Materials"] = "Tengo materiales"

-- ============================================================================
-- AUCTION HOUSE
-- ============================================================================

L[" -- partial scan"] = " -- escaneo parcial"
L["Auction query is throttled. Try again in a moment."] = "La consulta de subastas está limitada. Inténtalo de nuevo en un momento."
L["Buy out this auction for %s?"] = "¿Comprar esta subasta por %s?"
L["Choose search criteria and press \"Search\""] = "Elige criterios de búsqueda y pulsa \"Buscar\""
L["Loading results..."] = "Cargando resultados..."
L["Lvl"] = "Niv"
L["Modern visual shell for Buy/Sell/Auctions with optional Auctionator tab embedding."] = "Interfaz moderna para Comprar/Vender/Subastas con pestaña opcional de Auctionator."
L["No listings."] = "Sin anuncios."
L["No results. Adjust filters and search again."] = "Sin resultados. Ajusta los filtros y busca de nuevo."
L["Page %d of %d  (items %d-%d of %d, from %d auction)%s"] = "Página %d de %d  (objetos %d-%d de %d, de %d subasta)%s"
L["Page %d of %d  (items %d-%d of %d, from %d auctions)%s"] = "Página %d de %d  (objetos %d-%d de %d, de %d subastas)%s"
L["Page 1 of 1"] = "Página 1 de 1"
L["Per Item"] = "Por unidad"
L["Place a bid of %s?"] = "¿Pujar %s?"
L["Scanning page %d of %d..."] = "Escaneando página %d de %d..."
L["Searching..."] = "Buscando..."
L["Sort Per Item"] = "Ordenar por unidad"
L["You have no auctions."] = "No tienes subastas."

-- ============================================================================
-- BAGS
-- ============================================================================

L["All Bags"] = "Todas las bolsas"
L["Auto-empty old bag when swapping"] = "Vaciar la bolsa antigua al cambiarla"
L["Auto-sell junk at merchants"] = "Vender basura automáticamente en los mercaderes"
L["Bag Options"] = "Opciones de bolsa"
L["Category (smart)"] = "Categoría (inteligente)"
L["Combined bag (all-in-one)"] = "Bolsa combinada (todo en uno)"
L["Item Level"] = "Nivel de objeto"
L["Keys"] = "Llaves"
L["Merchant"] = "Mercader"
L["Name"] = "Nombre"
L["Not enough free space to swap that bag."] = "No hay espacio libre suficiente para cambiar esa bolsa."
L["One movable window showing every bag slot in a Dragonflight-style grid. Takes over bag opening and replaces the per-window 'Retail bags' restyle. Reload (/reload) to apply."] = "Una ventana movible que muestra todas las ranuras de bolsa en una cuadrícula estilo Dragonflight. Se encarga de abrir las bolsas y sustituye el rediseño 'Bolsas retail' por ventana. /reload para aplicar."
L["Quality"] = "Calidad"
L["Red-tint unusable items"] = "Teñir de rojo los objetos inutilizables"
L["Restyle the bag windows with the Dragonflight metal frame, portrait, and item quality borders. Disable to keep the stock Blizzard bags. Reload (/reload) to apply."] = "Rediseña las ventanas de bolsa con el marco metálico de Dragonflight, retrato y bordes de calidad. Desactívalo para conservar las bolsas originales de Blizzard. /reload para aplicar."
L["Retail bags"] = "Bolsas retail"
L["Reverse sort order"] = "Invertir el orden"
L["Search"] = "Buscar"
L["Separate specialty bags"] = "Separar bolsas especializadas"
L["Shift-right-click to stop watching"] = "Mayús+clic derecho para dejar de vigilar"
L["Show item level on items"] = "Mostrar el nivel de objeto en los objetos"
L["Show keyring row"] = "Mostrar la fila del llavero"
L["Sold %d junk item(s)."] = "%d objeto(s) de basura vendido(s)."
L["Sort Bags"] = "Ordenar bolsas"
L["Sort by"] = "Ordenar por"
L["Sorting…"] = "Ordenando…"
L["Swapping bag…"] = "Cambiando bolsa…"
L["The same setting as Enable Item Level in DragonUI's options (Enhancements > Item Level). Covers the character panel and every other frame too."] = "La misma opción que 'Activar nivel de objeto' en las opciones de DragonUI (Mejoras > Nivel de objeto). También cubre el panel de personaje y todas las demás ventanas."
L["Turn on Item Level in DragonUI's options (Enhancements > Item Level) first."] = "Activa antes 'Nivel de objeto' en las opciones de DragonUI (Mejoras > Nivel de objeto)."

-- ============================================================================
-- COOLDOWN MANAGER
-- ============================================================================

L["(empty)"] = "(vacío)"
L["(your spec)"] = "(tu especialización)"
L["A ready sound plays when a COOLDOWN finishes.|nThis spell has none, so it can never play.|nClearing it also clears the badge."] = "El sonido de preparado suena cuando termina un TIEMPO DE REUTILIZACIÓN.|nEste hechizo no tiene, así que nunca sonará.|nBorrarlo también borra el distintivo."
L["A spell can be on cooldown and buffing you at the same time. The glow says which icons are buffed; the timer says how long."] = "Un hechizo puede estar en reutilización y beneficiándote a la vez. El brillo indica qué iconos tienen beneficio; el temporizador, cuánto dura."
L["Active"] = "Activo"
L["Alert"] = "Aviso"
L["Always"] = "Siempre"
L["Auto-track buffs under %ds"] = "Seguir automáticamente beneficios de menos de %ds"
L["Available"] = "Disponible"
L["Bar Content"] = "Contenido de la barra"
L["Bar Width"] = "Anchura de la barra"
L["Both of these are immediate and cannot be undone from here — Revert only covers layout changes."] = "Ambas acciones son inmediatas y no se pueden deshacer desde aquí: 'Revertir' solo cubre cambios de diseño."
L["Buff Bars"] = "Barras de beneficios"
L["Buff Icons"] = "Iconos de beneficios"
L["Buff tracking"] = "Seguimiento de beneficios"
L["Buffed spells"] = "Hechizos con beneficio"
L["Buffs you have not seen before are recorded and listed under Not Displayed on the Tracked Buffs tab, where you can assign the ones you want. Nothing appears on screen until you do."] = "Los beneficios que no hayas visto antes se registran y aparecen en 'No mostrados' en la pestaña 'Beneficios seguidos', donde puedes asignar los que quieras. Hasta entonces no aparece nada."
L["Button Glow"] = "Brillo de botón"
L["Clear All Alerts"] = "Borrar todos los avisos"
L["Clear Ready Sound"] = "Borrar sonido de preparado"
L["Clear all alerts and sounds"] = "Borrar todos los avisos y sonidos"
L["Clear every configured alert and ready sound?\n\nSpell lists and frame positions are not affected."] = "¿Borrar todos los avisos y sonidos de preparado configurados?\n\nLas listas de hechizos y las posiciones de las ventanas no se ven afectadas."
L["Closes edit mode and opens the Cooldown Manager window, which carries the settings that are not per-viewer: alerts, ready sounds, buff tracking, icon fit and the resets."] = "Cierra el modo de edición y abre la ventana del Gestor de reutilizaciones, que contiene los ajustes que no son de un visor concreto: avisos, sonidos de preparado, seguimiento de beneficios, ajuste de iconos y los restablecimientos."
L["Cooldown Manager"] = "Gestor de reutilizaciones"
L["Cooldown Manager Settings"] = "Ajustes del Gestor de reutilizaciones"
L["Cooldown Manager layout string (Ctrl+C to copy):"] = "Código de diseño del Gestor de reutilizaciones (Ctrl+C para copiar):"
L["Copy"] = "Copiar"
L["Defensives, interrupts, CC and escapes."] = "Defensivas, interrupciones, control y escapes."
L["Delete"] = "Borrar"
L["Delete the layout \"%s\"?"] = "¿Borrar el diseño \"%s\"?"
L["Drag onto Essential or Utility to track it."] = "Arrástralo a 'Esenciales' o 'Utilidad' para seguirlo."
L["Draw the countdown number on each icon."] = "Mostrar la cuenta atrás en cada icono."
L["Each viewer's own settings — size, spacing, orientation, visibility, what its icons show — live on the frame, in edit mode, where you can see what you are changing. These open edit mode with that viewer selected and its settings already up. Closes this window; not available in combat."] = "Los ajustes propios de cada visor —tamaño, espaciado, orientación, visibilidad y qué muestran sus iconos— están en la propia ventana, en modo de edición, donde ves lo que cambias. Estos botones abren el modo de edición con ese visor seleccionado y sus ajustes ya abiertos. Cierra esta ventana; no disponible en combate."
L["Enable Cooldown Manager"] = "Activar el Gestor de reutilizaciones"
L["Enabled"] = "Activado"
L["Essential Cooldowns"] = "Reutilizaciones esenciales"
L["Everything"] = "Todo"
L["Everything (no spec)"] = "Todo (sin especialización)"
L["Everything the Cooldown Manager can be told to do that is not about one viewer's layout. Layout and position both live on the frame itself, in edit mode (/dui edit) — click a viewer there for its own settings, or use the buttons just below to go straight to one."] = "Todo lo que puede hacer el Gestor de reutilizaciones que no tenga que ver con el diseño de un visor concreto. El diseño y la posición están en la propia ventana, en modo de edición (/dui edit): haz clic allí en un visor para ver sus ajustes, o usa los botones de abajo para ir directamente a uno."
L["Export Layout"] = "Exportar diseño"
L["FX Style"] = "Estilo de efecto"
L["Flashes once, the moment the cooldown finishes.|nWorks for every spell."] = "Destella una vez en cuanto termina la reutilización.|nFunciona con todos los hechizos."
L["Frame strength"] = "Intensidad del marco"
L["Gap between icons. Retail offsets this by -4, so the low end overlaps slightly — that is the stock look, not a bug."] = "Separación entre iconos. Retail lo desplaza en -4, así que en el extremo bajo se solapan un poco: ese es el aspecto original, no un fallo."
L["Glow while buffed"] = "Brillar mientras hay beneficio"
L["Glows during the last %d%% of this buff's|nremaining time."] = "Brilla durante el último %d%% del tiempo|nrestante de este beneficio."
L["Glows during the last %d%% of this spell's own|nbuff or debuff."] = "Brilla durante el último %d%% del propio|nbeneficio o perjuicio de este hechizo."
L["Glows for as long as the spell is off cooldown|nand affordable."] = "Brilla mientras el hechizo esté disponible|ny se pueda pagar."
L["Glows for as long as this buff is on you.|n|nThe one that works for a proc: it asks whether the|nbuff is up, not whether something is castable|nor off cooldown."] = "Brilla mientras tengas este beneficio.|n|nEl que funciona con un proc: comprueba si el|nbeneficio está activo, no si algo se puede lanzar|no está disponible."
L["Glows for as long as this spell's effect is|nup on %s."] = "Brilla mientras el efecto de este hechizo|nesté activo en %s."
L["Halo the icon gold while the spell's buff (or, for a shaman, its totem) is up."] = "Rodea el icono de dorado mientras el beneficio del hechizo (o, en chamanes, su tótem) esté activo."
L["Hidden"] = "Oculto"
L["Hide When Inactive"] = "Ocultar cuando esté inactivo"
L["Horizontal"] = "Horizontal"
L["How many icons before the layout wraps. Vertical orientation reads this as icons per column."] = "Cuántos iconos antes de que el diseño salte de línea. En orientación vertical se lee como iconos por columna."
L["Icon Direction"] = "Dirección de iconos"
L["Icon Limit"] = "Límite de iconos"
L["Icon Only"] = "Solo icono"
L["Icon Padding"] = "Separación de iconos"
L["Icon Size"] = "Tamaño de icono"
L["Icon and Name"] = "Icono y nombre"
L["Icon fit"] = "Ajuste de iconos"
L["Icon inset"] = "Margen del icono"
L["Import"] = "Importar"
L["Import Layout"] = "Importar diseño"
L["In Combat"] = "En combate"
L["Lasts %s sec"] = "Dura %s s"
L["Layouts"] = "Diseños"
L["Layouts include appearance"] = "Los diseños incluyen la apariencia"
L["Left"] = "Izquierda"
L["Load the %s starter layout?\n\nEssential is set to that spec's spells. Everything else for your class moves to Not Displayed — nothing is deleted, and you can drag any of it back.\n\nTracked auras, trinkets, alerts and frame positions are not affected."] = "¿Cargar el diseño inicial de %s?\n\n'Esenciales' pasa a los hechizos de esa especialización. Todo lo demás de tu clase pasa a 'No mostrados': no se borra nada y puedes arrastrarlo de vuelta.\n\nLas auras seguidas, abalorios, avisos y posiciones de las ventanas no se ven afectados."
L["Marching Ants"] = "Hormigas en marcha"
L["Move to %s"] = "Mover a %s"
L["Name Only"] = "Solo nombre"
L["Name this layout:"] = "Nombra este diseño:"
L["New Layout"] = "Nuevo diseño"
L["None"] = "Ninguno"
L["Not displayed on any viewer"] = "No se muestra en ningún visor"
L["Not yet learned"] = "Aún no aprendido"
L["Nothing to undo. It covers LAYOUTS, not the settings|non these tabs — a viewer's own size and position revert|nfrom its edit-mode panel instead."] = "Nada que deshacer. Cubre los DISEÑOS, no los ajustes|nde estas pestañas: el tamaño y la posición de un visor|nse revierten desde su panel de modo de edición."
L["Off by default. Turn on to show the four viewers; turn off to hide them again. Takes effect immediately either way, and nothing is forgotten — this switch stores one flag and touches nothing else, so your setup comes back exactly as you left it."] = "Desactivado por defecto. Actívalo para mostrar los cuatro visores; desactívalo para ocultarlos de nuevo. Surte efecto de inmediato en ambos sentidos y no se olvida nada: este interruptor guarda un solo indicador y no toca nada más, así que tu configuración vuelve tal y como la dejaste."
L["Off, both specs share one set of lists. Turning it on copies the layout you have now into the spec you are in."] = "Desactivado, ambas especializaciones comparten un mismo conjunto de listas. Al activarlo se copia el diseño actual a la especialización en la que estés."
L["Off, loading or importing a layout changes only what you track — lists, tracked buffs, trinkets, alerts and sounds. On, it also applies the orientation, icons per row, size, padding and opacity the layout was saved with.|n|nLayouts always SAVE appearance either way, so this only decides what happens when one is applied. Revert always puts appearance back, whatever this says."] = "Desactivado, cargar o importar un diseño solo cambia lo que sigues: listas, beneficios seguidos, abalorios, avisos y sonidos. Activado, también aplica la orientación, los iconos por fila, el tamaño, la separación y la opacidad con los que se guardó.|n|nLos diseños siempre GUARDAN la apariencia en ambos casos, así que esto solo decide qué ocurre al aplicarlos. 'Revertir' siempre restaura la apariencia, diga lo que diga esta opción."
L["Off, orientation, icons per row, size, padding and opacity are one setup for every character. On, each character can differ — until you change something here it still follows the shared setup, so nothing moves when you tick this, and unticking it gives the shared setup back without losing what you changed."] = "Desactivado, la orientación, los iconos por fila, el tamaño, la separación y la opacidad son una sola configuración para todos los personajes. Activado, cada personaje puede diferir: hasta que cambies algo aquí sigue usando la configuración compartida, así que nada se mueve al marcarlo, y al desmarcarlo recuperas la compartida sin perder lo que cambiaste."
L["Offensive burst and damage cooldowns."] = "Reutilizaciones ofensivas de daño y explosión."
L["Opacity"] = "Opacidad"
L["Open Cooldown Manager"] = "Abrir el Gestor de reutilizaciones"
L["Opens a share string you can copy with Ctrl+C.|nIt covers this class's spell lists, tracked auras,|ntrinket placement, alerts and sounds."] = "Abre un código para compartir que puedes copiar con Ctrl+C.|nIncluye las listas de hechizos de esta clase, las auras seguidas,|nla colocación de abalorios, los avisos y los sonidos."
L["Opens the Cooldown Manager window (/cdm) on its Spells tab. Needs the module on — the window configures the viewers, so it goes away with them."] = "Abre la ventana del Gestor de reutilizaciones (/cdm) en la pestaña 'Hechizos'. Requiere el módulo activado: la ventana configura los visores, así que desaparece con ellos."
L["Options"] = "Opciones"
L["Orientation"] = "Orientación"
L["Pandemic Border"] = "Borde de pandemia"
L["Paste a Cooldown Manager layout string:"] = "Pega un código de diseño del Gestor de reutilizaciones:"
L["Ready Sound"] = "Sonido de preparado"
L["Ready sound: %s"] = "Sonido de preparado: %s"
L["Refresh"] = "Renovar"
L["Refresh Window"] = "Ventana de renovación"
L["Remove"] = "Quitar"
L["Remove every per-spell alert and ready sound. Spell lists and positions are not affected."] = "Quita todos los avisos y sonidos de preparado por hechizo. Las listas de hechizos y las posiciones no se ven afectadas."
L["Rename"] = "Renombrar"
L["Requires the %s talent"] = "Requiere el talento %s"
L["Reset"] = "Restablecer"
L["Reset %s to its default layout?\n\nThis viewer's position, size, orientation and visibility all go back to stock. Nothing else is affected, and it cannot be undone."] = "¿Restablecer %s a su diseño por defecto?\n\nLa posición, el tamaño, la orientación y la visibilidad de este visor vuelven a los valores originales. Nada más se ve afectado y no se puede deshacer."
L["Reset Spell Lists"] = "Restablecer listas de hechizos"
L["Reset spell and buff lists"] = "Restablecer listas de hechizos y beneficios"
L["Reset this class's Cooldown Manager spell and buff lists to their defaults?\n\nOther classes, alerts, sounds and frame positions are not affected."] = "¿Restablecer a sus valores por defecto las listas de hechizos y beneficios del Gestor de reutilizaciones de esta clase?\n\nOtras clases, avisos, sonidos y posiciones de ventanas no se ven afectados."
L["Reset to the starter layout?\n\nThis reverts every Cooldown Manager edit — spells, tracked auras, trinket placement, alerts and sounds — to their defaults, and clears your saved-layout selection.\n\nFrame positions are not affected."] = "¿Restablecer el diseño inicial?\n\nEsto revierte a sus valores por defecto todos los cambios del Gestor de reutilizaciones —hechizos, auras seguidas, colocación de abalorios, avisos y sonidos— y borra tu selección de diseño guardado.\n\nLas posiciones de las ventanas no se ven afectadas."
L["Restore the curated defaults and the auto-track window for THIS CLASS, clearing its spell lists, aura assignments and trinket placement. Other classes, alerts, sounds and positions are not affected."] = "Restaura los valores por defecto seleccionados y la ventana de seguimiento automático de ESTA CLASE, borrando sus listas de hechizos, asignaciones de auras y colocación de abalorios. Otras clases, avisos, sonidos y posiciones no se ven afectados."
L["Retail's Cooldown Manager, driven from curated per-class cooldown lists. |cffffcc55Off by default|r — it adds four viewers to the middle of your screen, so it waits to be asked. Every setting — which spells and buffs are tracked, each viewer's layout, size and visibility, alerts and ready sounds — lives in the Cooldown Manager window itself (/cdm). Drag the viewers with DragonUI's editor mode to reposition them, and right-click one there for its own layout settings."] = "El Gestor de reutilizaciones de retail, basado en listas de reutilizaciones seleccionadas por clase. |cffffcc55Desactivado por defecto|r: añade cuatro visores en el centro de la pantalla, así que espera a que se lo pidas. Todos los ajustes —qué hechizos y beneficios se siguen, el diseño, tamaño y visibilidad de cada visor, los avisos y los sonidos de preparado— están en la propia ventana del Gestor (/cdm). Arrastra los visores con el modo de edición de DragonUI para recolocarlos y haz clic derecho en uno allí para ver sus ajustes de diseño."
L["Retail's behaviour: while buffed, the icon counts down the BUFF. Off, it counts down the spell's cooldown and the glow alone marks it as buffed — which is clearer when the two differ, as on Prayer of Mending."] = "Comportamiento de retail: mientras hay beneficio, el icono descuenta el BENEFICIO. Desactivado, descuenta la reutilización del hechizo y solo el brillo lo marca como beneficiado, lo que es más claro cuando ambos difieren, como en 'Plegaria de sanación'."
L["Revert"] = "Revertir"
L["Right"] = "Derecha"
L["Save, load, import and export the whole|nCooldown Manager setup for this class."] = "Guarda, carga, importa y exporta toda la configuración|ndel Gestor de reutilizaciones de esta clase."
L["Separate appearance per character"] = "Apariencia distinta por personaje"
L["Separate layout per spec"] = "Diseño distinto por especialización"
L["Short-duration buffs and procs, as depleting bars."] = "Beneficios y procs de corta duración, como barras que se vacían."
L["Short-duration buffs and procs, as icons."] = "Beneficios y procs de corta duración, como iconos."
L["Show Timer"] = "Mostrar temporizador"
L["Show Tooltips"] = "Mostrar descripciones"
L["Show Unlearned"] = "Mostrar no aprendidos"
L["Show a slot only while its aura is active."] = "Mostrar una ranura solo mientras su aura esté activa."
L["Show a tooltip when hovering an icon."] = "Mostrar una descripción al pasar el cursor por un icono."
L["Show every short buff the moment it lands, without assigning it first. Convenient on a character you are still setting up; in a raid it fills the viewers with other people's cooldowns, food and flasks."] = "Muestra todos los beneficios cortos en cuanto se aplican, sin asignarlos antes. Práctico en un personaje que aún estás configurando; en una banda llena los visores con reutilizaciones, comida y frascos de los demás."
L["Show the buff's time, not the cooldown"] = "Mostrar el tiempo del beneficio, no la reutilización"
L["Show them as"] = "Mostrarlos como"
L["Show this viewer at all. The editor handle stays either way, so this is reversible from right here."] = "Mostrar este visor siquiera. El asa de edición permanece en ambos casos, así que se puede revertir desde aquí mismo."
L["Sparkles"] = "Destellos"
L["Talent specs"] = "Especializaciones de talento"
L["The frame is a soft shadow that falls on the icon's outer edge, so it only shows where there is icon underneath it. Strength draws it more than once to deepen it — that is also what makes its rounded corners read, since the icons themselves cannot be rounded here. Inset shrinks the icon, which slides the shadow off it, so raise that one sparingly."] = "El marco es una sombra suave que cae sobre el borde exterior del icono, así que solo se ve donde hay icono debajo. La intensidad lo dibuja varias veces para oscurecerlo, que es también lo que hace visibles sus esquinas redondeadas, ya que aquí los iconos no pueden redondearse. El margen encoge el icono y desliza la sombra fuera de él, así que súbelo con moderación."
L["The full curated list for your class, both specs' spells|nincluded. This is what the Cooldown Manager shipped with|nbefore per-spec starters."] = "La lista completa seleccionada para tu clase, con los hechizos|nde ambas especializaciones. Es lo que traía el Gestor de reutilizaciones|nantes de los diseños iniciales por especialización."
L["Tracked automatically. Drag it into a section to pin it there."] = "Seguido automáticamente. Arrástralo a una sección para fijarlo allí."
L["Undoes the last layout change — applying a layout,|nimporting one, or the starter reset.|n|nOne step, and only for this session."] = "Deshace el último cambio de diseño: aplicar un diseño,|nimportar uno o restablecer el inicial.|n|nUn solo paso, y solo durante esta sesión."
L["Usable"] = "Utilizable"
L["Use Starter Layout"] = "Usar diseño inicial"
L["Utility Cooldowns"] = "Reutilizaciones de utilidad"
L["Vertical"] = "Vertical"
L["Viewer layout"] = "Diseño del visor"
L["Visibility"] = "Visibilidad"
L["When this viewer is on screen at all. Hidden still leaves the editor handle here."] = "Cuándo aparece este visor en pantalla. 'Oculto' deja aquí el asa de edición de todos modos."
L["Which of the two buff viewers auto-tracked buffs land in."] = "En cuál de los dos visores de beneficios acaban los seguidos automáticamente."
L["Which spells and buffs you track is remembered separately for each talent spec, so a Discipline layout and a Holy one do not overwrite each other. Where each viewer sits is always remembered per character; the appearance settings are shared unless you say otherwise below."] = "Qué hechizos y beneficios sigues se recuerda por separado para cada especialización de talento, así que un diseño de Disciplina y otro Sagrado no se sobrescriben. Dónde se sitúa cada visor se recuerda siempre por personaje; los ajustes de apariencia son compartidos salvo que indiques lo contrario abajo."
L["is turned off. Enable it in DragonUI's options, under New Era > Cooldown Manager."] = "está desactivado. Actívalo en las opciones de DragonUI, en New Era > Gestor de reutilizaciones."
L["you"] = "ti"
L["|n|nOn a buff row this is about RE-CASTING it,|nnot about the buff being up — that is Active."] = "|n|nEn una fila de beneficio esto trata de VOLVER a lanzarlo,|nno de que el beneficio esté activo: eso es 'Activo'."
L["|n|nThe one for a DoT or a shield: it asks whether|nthe aura is up, not whether the cooldown is ready."] = "|n|nEl indicado para un DoT o un escudo: comprueba si|nel aura está activa, no si la reutilización está lista."
L["|n|nThis one also waits for a target below %d%% health."] = "|n|nEste además espera a un objetivo por debajo del %d%% de salud."
L["|n|n|cff40ff40Applies %s to %s, so this will work.|r"] = "|n|n|cff40ff40Aplica %s a %s, así que esto funcionará.|r"
L["|n|n|cff40ff40Its aura is active now, so this will work.|r"] = "|n|n|cff40ff40Su aura está activa ahora, así que esto funcionará.|r"
L["|n|n|cffffd200No aura of this name is up right now.|r"] = "|n|n|cffffd200Ahora mismo no hay ningún aura con ese nombre activa.|r"

-- ============================================================================
-- ADVENTURE GUIDE
-- ============================================================================

L["(No abilities recorded for this encounter.)"] = "(No hay habilidades registradas para este encuentro.)"
L["(no model)"] = "(sin modelo)"
L["Adventure Guide"] = "Guía de aventuras"
L["Eastern Kingdoms"] = "Reinos del Este"
L["Kalimdor"] = "Kalimdor"
L["Model will load once seen within this session due to client limitations."] = "El modelo se cargará cuando se haya visto en esta sesión, por limitaciones del cliente."
L["Phase %d"] = "Fase %d"
L["The Adventure Guide: bosses, abilities, and loot for Classic and Burning Crusade dungeons and raids (/aguide)."] = "La Guía de aventuras: jefes, habilidades y botín de las mazmorras y bandas de Classic y Burning Crusade (/aguide)."

-- ============================================================================
-- GUILD
-- ============================================================================

L["GuildControlPopupFrame is missing on this client."] = "GuildControlPopupFrame no existe en este cliente."
L["Modern Communities-style guild window (Roster / Info / Chat)."] = "Ventana de cofradía moderna estilo Comunidades (Lista / Información / Chat)."
L["Promote"] = "Ascender"

-- ============================================================================
-- LEVEL UP DISPLAY
-- ============================================================================

L["Battleground available"] = "Campo de batalla disponible"
L["Can be learned from a trainer"] = "Se puede aprender de un maestro"
L["Dungeon available"] = "Mazmorra disponible"
L["Enable Level Up Display"] = "Activar el aviso de subida de nivel"
L["Level Up Display"] = "Aviso de subida de nivel"
L["New Feature"] = "Nueva función"
L["New Riding Skill"] = "Nueva habilidad de montar"
L["New Talent Point"] = "Nuevo punto de talento"
L["New Talent Points"] = "Nuevos puntos de talento"
L["New rank available"] = "Nuevo rango disponible"
L["On by default. Turn off to stop the banner appearing on level-up; the harvest keeps running either way, so turning it back on costs nothing."] = "Activado por defecto. Desactívalo para que el cartel no aparezca al subir de nivel; la recopilación sigue funcionando igualmente, así que volver a activarlo no cuesta nada."
L["Play the level-up sound"] = "Reproducir el sonido de subida de nivel"
L["Raid available"] = "Banda disponible"
L["Retail's level-up banner. What it announces is read from |cffffcc55this server|r — abilities and their levels come from your class trainer's own list, battlegrounds and dungeons from the client's brackets. Visit a trainer once to fill it in; |cffffcc55/nelevelup coverage|r shows what it knows."] = "El cartel de subida de nivel de retail. Lo que anuncia se lee de |cffffcc55este servidor|r: las habilidades y sus niveles vienen de la lista de tu maestro de clase, y los campos de batalla y mazmorras de los rangos del cliente. Visita una vez a un maestro para rellenarlo; |cffffcc55/nelevelup coverage|r muestra lo que conoce."
L["Talents"] = "Talentos"
L["You have reached"] = "Has alcanzado"
L["level %d"] = "el nivel %d"
L["|cffffcc55Off by default.|r The game already plays its own fanfare when you level, so this only adds a second copy on top of it. Turn it on if you want /nelevelup previews to make a sound, since those fire no game sound of their own."] = "|cffffcc55Desactivado por defecto.|r El juego ya reproduce su propia fanfarria al subir de nivel, así que esto solo añade una segunda encima. Actívalo si quieres que las vistas previas de /nelevelup suenen, ya que esas no disparan ningún sonido del juego."

-- ============================================================================
-- PROFESSIONS
-- ============================================================================

L["Auctionator API not available for reagent scans."] = "La API de Auctionator no está disponible para escanear componentes."
L["Auctionator scan started for recipe reagents."] = "Escaneo de Auctionator iniciado para los componentes de la receta."
L["Open the Auction House first to run Auctionator scans."] = "Abre antes la Casa de subastas para ejecutar escaneos de Auctionator."
L["Requires the Auction House window to be open."] = "Requiere que la ventana de la Casa de subastas esté abierta."
L["Requires: %s"] = "Requiere: %s"
L["Retail-style crafting window for all professions."] = "Ventana de fabricación estilo retail para todas las profesiones."
L["Scan AH"] = "Escanear CS"
L["Searches Auctionator for the selected recipe and its reagents."] = "Busca en Auctionator la receta seleccionada y sus componentes."

-- ============================================================================
-- SOCIAL
-- ============================================================================

L["Away"] = "Ausente"
L["Busy"] = "Ocupado"
L["Cancel Extend"] = "Cancelar prórroga"
L["Enter a note for %s:"] = "Escribe una nota para %s:"
L["Extend"] = "Prorrogar"
L["Extended"] = "Prorrogado"
L["ID: %s"] = "ID: %s"
L["Instance"] = "Instancia"
L["Modern friends window (Friends / Ignore / Who) with a Guild tab."] = "Ventana de amigos moderna (Amigos / Ignorados / Quién) con pestaña de cofradía."
L["Promote to Assistant"] = "Ascender a ayudante"
L["Promote to Raid Leader"] = "Ascender a líder de banda"
L["Resets In"] = "Se reinicia en"
L["Set Note"] = "Poner nota"
L["You are not saved to any instances."] = "No estás asignado a ninguna instancia."

-- ============================================================================
-- SPELLBOOK
-- ============================================================================

L["Spellbook"] = "Libro de hechizos"
L["The modern Dragonflight spellbook window. Disable to keep the stock Blizzard spellbook."] = "La ventana moderna del libro de hechizos estilo Dragonflight. Desactívalo para conservar el libro de hechizos original de Blizzard."

-- ============================================================================
-- TALENTS
-- ============================================================================

L["  %s: have %d, build wants %d"] = "  %s: tienes %d, la build pide %d"
L["%s\n\nImport anyway?"] = "%s\n\n¿Importar de todos modos?"
L["ACTIVE EFFECTS"] = "EFECTOS ACTIVOS"
L["Activate"] = "Activar"
L["Copy this build string (Ctrl+C). Talented & the WoWhead/wotlkdb calculators import it too:"] = "Copia este código de build (Ctrl+C). Talented y las calculadoras de WoWhead/wotlkdb también lo importan:"
L["Delete loadout '%s'?"] = "¿Borrar la configuración '%s'?"
L["GLYPHS"] = "GLIFOS"
L["Glyph options"] = "Opciones de glifos"
L["Glyphs"] = "Glifos"
L["Import…"] = "Importar…"
L["Loadouts"] = "Configuraciones"
L["Locked"] = "Bloqueado"
L["MAJOR GLYPHS"] = "GLIFOS MAYORES"
L["MINOR GLYPHS"] = "GLIFOS MENORES"
L["NO ACTIVE EFFECTS"] = "SIN EFECTOS ACTIVOS"
L["Name this imported loadout:"] = "Nombra esta configuración importada:"
L["Name this loadout (saves your current spec):"] = "Nombra esta configuración (guarda tu especialización actual):"
L["Paste a talent string or calculator URL (Talented / WoWhead / wotlkdb):"] = "Pega un código de talentos o una URL de calculadora (Talented / WoWhead / wotlkdb):"
L["Pet"] = "Mascota"
L["Remove this glyph?"] = "¿Quitar este glifo?"
L["Rename loadout:"] = "Renombrar configuración:"
L["Rename specialization"] = "Renombrar especialización"
L["Rename this specialization (letters only, max %d):"] = "Renombra esta especialización (solo letras, máx. %d):"
L["Save current spec…"] = "Guardar especialización actual…"
L["Server uses custom talents"] = "El servidor usa talentos personalizados"
L["Show glyph effects"] = "Mostrar efectos de glifos"
L["Show glyph names"] = "Mostrar nombres de glifos"
L["Tags exported builds with this realm so imports onto other layouts warn first."] = "Etiqueta las builds exportadas con este servidor para que las importaciones en otros diseños avisen antes."
L["Talents Panel"] = "Panel de talentos"
L["The modern talents window. Turn off to use the standard Blizzard talent window."] = "La ventana de talentos moderna. Desactívalo para usar la ventana de talentos estándar de Blizzard."
L["This loadout has fewer points in some talents than you've already spent, so it needs a respec first:\n"] = "Esta configuración tiene menos puntos en algunos talentos de los que ya has gastado, así que necesita reasignarlos primero:\n"
L["Toggle slot name labels and the active-effects list."] = "Alterna las etiquetas de nombre de ranura y la lista de efectos activos."
L["Unlock Spec"] = "Desbloquear especialización"
L["\n\nReset at a class trainer, then load again. (The rest has been staged — click Apply to learn it.)"] = "\n\nReasigna con un maestro de clase y vuelve a cargar. (El resto está preparado: pulsa 'Aplicar' para aprenderlo.)"

-- ============================================================================
-- OPTIONS PANEL
-- ============================================================================

L["Adventure Guide (Encounter Journal)"] = "Guía de aventuras (Diario de encuentros)"
L["Auction House"] = "Casa de subastas"
L["Boss and loot browser. Requires a /reload to take effect (the micro button doesn't re-check this live)."] = "Explorador de jefes y botín. Requiere /reload para surtir efecto (el microbotón no lo vuelve a comprobar en directo)."
L["Click for this frame's settings."] = "Haz clic para ver los ajustes de esta ventana."
L["Combined Bag"] = "Bolsa combinada"
L["Custom"] = "Personalizado"
L["Custom scale"] = "Escala personalizada"
L["Drag to move."] = "Arrastra para mover."
L["Each window's size: \"Use UI scale\" follows the game's UI Scale slider, \"No scaling\" stays pixel-perfect, \"Custom\" uses its slider. The custom slider is greyed out and locked unless that window's mode is set to Custom."] = "El tamaño de cada ventana: \"Usar escala de interfaz\" sigue el deslizador de escala del juego, \"Sin escalado\" mantiene la precisión de píxel y \"Personalizado\" usa su deslizador. El deslizador personalizado está atenuado y bloqueado salvo que el modo de esa ventana sea 'Personalizado'."
L["Guild"] = "Cofradía"
L["Looking For Group"] = "Buscar grupo"
L["Looking For Group (Dungeon/Raid Finder)"] = "Buscar grupo (buscador de mazmorras/bandas)"
L["NewEra panels ported onto DragonUI. Toggle a panel below to enable or disable it. Panels appear here as their modules load."] = "Paneles de NewEra portados a DragonUI. Activa o desactiva un panel abajo. Los paneles aparecen aquí a medida que se cargan sus módulos."
L["No scaling"] = "Sin escalado"
L["Our all-in-one bag window. Turn OFF to use the stock Blizzard bags instead. Reload (/reload) to apply."] = "Nuestra ventana de bolsas todo en uno. DESACTÍVALA para usar las bolsas originales de Blizzard. /reload para aplicar."
L["Professions"] = "Profesiones"
L["Reload (/reload) to apply."] = "/reload para aplicar."
L["Scale mode"] = "Modo de escala"
L["Scaling controls are unavailable: the 'core\\Scale.lua' file isn't loaded. Make sure your installed DragonUI_NewEra includes core/Scale.lua AND its line in the .toc, then /reload."] = "Los controles de escala no están disponibles: el archivo 'core\\Scale.lua' no está cargado. Asegúrate de que tu instalación de DragonUI_NewEra incluye core/Scale.lua Y su línea en el .toc, y luego usa /reload."
L["Scaling controls need a newer DragonUI options panel (AddSlider/AddDropdown)."] = "Los controles de escala necesitan un panel de opciones de DragonUI más reciente (AddSlider/AddDropdown)."
L["Social"] = "Social"
L["Social (Friends/Who/Guild/Chat/Raid)"] = "Social (Amigos/Quién/Cofradía/Chat/Banda)"
L["Use DragonUI's window in place of the Blizzard default. Changes take effect after a /reload."] = "Usar la ventana de DragonUI en lugar de la de Blizzard. Los cambios surten efecto tras un /reload."
L["Use UI scale"] = "Usar escala de interfaz"
L["Window Scaling"] = "Escalado de ventanas"
L["Windows"] = "Ventanas"

-- ============================================================================
-- SHARED UI
-- ============================================================================

L["Select All"] = "Seleccionar todo"

-- ============================================================================
-- BOSS TIMERS (modules/bossmods)
-- ============================================================================

L["Boss Timers"] = true
L["Boss Abilities"] = true
L["Boss Warnings"] = true
L["Boss Warning - Critical"] = true
L["Boss Warning - Medium"] = true
L["Boss Warning - Minor"] = true
L["Boss ability timers as a retail-style timeline or bar list. Reads its encounter data from DBM; without DBM installed there is nothing to show."] = true
L["Large on-screen warnings for important boss abilities. Needs DBM and the Boss Timers module."] = true
L["|cffff5555DBM is not installed.|r This module renders boss ability timers, it does not detect them — the encounter data comes from Deadly Boss Mods. Install DBM and reload to use it; the switches below are saved either way."] = true
L["Retail's boss ability timeline, drawn from |cffffcc55DBM's|r timers. Shows as a vertical rail of ability icons sliding toward now, or as a list of depleting bars. |cffffcc55Off by default.|r"] = true
L["|cffffcc55Everything else is on the frames themselves.|r Open |cffffcc55/dragonui edit|r, click a Boss Timers handle, and its own dialog carries the view, size, length, opacity, tooltips and the rest — each warning tier included, edited from the tier you clicked."] = true
L["Enable Boss Timers"] = true
L["The timeline and the three warning lines together. While it is on, DBM's own bars and warnings are hidden so the same timers are not drawn twice — its sounds and voice packs are left alone. Off by default. Reload (/reload) to apply."] = true
L["View"] = true
L["Timeline (rail)"] = true
L["Bars"] = true
L["Show the frame"] = true
L["Only while timers are running"] = true
L["Icon size"] = true
L["Rail length"] = true
L["Bar width"] = true
L["Space between bars"] = true
L["Show the countdown"] = true
L["Show the ability name"] = true
L["Timeline view only — the bar list always names its abilities."] = true
L["Show a test timer"] = true
L["Runs four sample timers and one warning through the same path a real DBM timer takes, so what you see is what an encounter will look like."] = true
L["Glow when an ability is imminent"] = true
L["On by default. The action-button proc glow, held for the last five seconds before an ability lands. It stands in for a retail effect this client cannot draw; with it off you get only the brief border flash, which is easy to miss."] = true
L["Revert Changes"] = true
L["Reset to Default"] = true
L["Timeline view only. How far out the rail reaches — the icons space themselves along it."] = true
L["Bars view only."] = true
L["Size"] = true
L["Scales the whole frame — the rail, the icons and the text together. Icon Size below scales only the icons."] = true
L["Background"] = true
L["The plate behind the frame. Retail ships it invisible."] = true
L["Scales the whole warning — text and both flanking icons together."] = true
L["The two spell icons either side of the text."] = true
L["Orientation"] = "Orientación"
L["Vertical"] = "Vertical"
L["Horizontal"] = "Horizontal"
L["Icon direction"] = true
L["Down / Right"] = true
L["Up / Left"] = true
L["Tooltips"] = true
L["At the cursor"] = true
L["Beside the frame"] = true
L["Off"] = true
L["Flip horizontally"] = true
L["Timeline view only. Which way the rail runs; the icons travel along it either way."] = true
L["Timeline view only. Which end of the rail is |cffffcc55now|r — the end abilities travel toward and go off at."] = true
L["Bars view only. Mirrors each row — the icon moves to the right and the bar drains the other way."] = true
L["Hovering an ability shows its spell tooltip. DBM raises some timers that are not a spell at all — a pull timer, a phase change — and those show their own name instead."] = true
L["Show the ability icons"] = true
L["The two copies of the ability's own icon either side of the text — what retail draws. The text already names the ability, so this is decoration; turn it off for a plain line of text."] = true
