--[[
================================================================================
DragonUI_NewEra - Brazilian Portuguese Locale (ptBR)

Generated by tools/locale-lint/gen_locale.py from enUS.lua; edit the translation
map in tools/locale-lint/translations/ptBR.py and regenerate, or correct a
string here and port the fix back. Entries left as `= true` fall back to English.

Machine-drafted and unreviewed by a native speaker: corrections welcome. Every
entry is checked against its English key for placeholder parity
(check_keys.py --verify), so a %d or |n cannot go missing, but wording has not
been through a human pass.
================================================================================
]]

local L = LibStub("AceLocale-3.0"):NewLocale("DragonUI_NewEra", "ptBR")
if not L then return end
-- ============================================================================
-- ============================================================================
L["Alchemy"] = "Alquimia"
L["Blacksmithing"] = "Ferraria"
L["Enchanting"] = "Encantamento"
L["Engineering"] = "Engenharia"
L["Herbalism"] = "Herborismo"
L["Leatherworking"] = "Couraria"
L["Mining"] = "Mineração"
L["Smelting"] = "Fundição"
L["Skinning"] = "Esfolamento"
L["Tailoring"] = "Alfaiataria"
L["Inscription"] = "Escrivania"
L["Jewelcrafting"] = "Joalheria"
L["Prospecting"] = "Prospecção"
L["Cooking"] = "Culinária"
L["First Aid"] = "Primeiros Socorros"
L["Fishing"] = "Pesca"
L["Select a recipe to craft"] = "Selecione uma receita para criar"
L["Hide item tooltips in list"] = "Ocultar dicas de item na lista"
L["Colour names by skill difficulty"] = "Colorir nomes pela dificuldade"
L["Plain skill bar (no animation)"] = "Barra de perícia simples (sem animação)"
L["Create"] = "Criar"
L["Create All"] = "Criar tudo"
L["Show Learned"] = "Mostrar aprendidas"
L["Has Skill Up"] = "Aumenta perícia"
L["Have Materials"] = "Tenho materiais"

-- ============================================================================
-- AUCTION HOUSE
-- ============================================================================

L[" -- partial scan"] = " -- varredura parcial"
L["Auction query is throttled. Try again in a moment."] = "A consulta ao leilão está limitada. Tente novamente em instantes."
L["Buy out this auction for %s?"] = "Arrematar este leilão por %s?"
L["Choose search criteria and press \"Search\""] = "Escolha critérios e clique em \"Procurar\""
L["Loading results..."] = "Carregando resultados..."
L["Lvl"] = "Nív"
L["Modern visual shell for Buy/Sell/Auctions with optional Auctionator tab embedding."] = "Interface moderna para Comprar/Vender/Leilões, com aba opcional do Auctionator."
L["No listings."] = "Nenhum anúncio."
L["No results. Adjust filters and search again."] = "Nenhum resultado. Ajuste os filtros e procure novamente."
L["Page %d of %d  (items %d-%d of %d, from %d auction)%s"] = "Página %d de %d  (itens %d-%d de %d, de %d leilão)%s"
L["Page %d of %d  (items %d-%d of %d, from %d auctions)%s"] = "Página %d de %d  (itens %d-%d de %d, de %d leilões)%s"
L["Page 1 of 1"] = "Página 1 de 1"
L["Per Item"] = "Por unidade"
L["Place a bid of %s?"] = "Dar um lance de %s?"
L["Scanning page %d of %d..."] = "Varrendo página %d de %d..."
L["Searching..."] = "Procurando..."
L["Sort Per Item"] = "Ordenar por preço unitário"
L["You have no auctions."] = "Você não tem leilões."

-- ============================================================================
-- BAGS
-- ============================================================================

L["All Bags"] = "Todas as bolsas"
L["Auto-empty old bag when swapping"] = "Esvaziar a bolsa antiga ao trocar"
L["Auto-sell junk at merchants"] = "Vender lixo automaticamente nos mercadores"
L["Bag Options"] = "Opções de bolsa"
L["Category (smart)"] = "Categoria (inteligente)"
L["Combined bag (all-in-one)"] = "Bolsa combinada (tudo em um)"
L["Item Level"] = "Nível de item"
L["Keys"] = "Chaves"
L["Merchant"] = "Mercador"
L["Name"] = "Nome"
L["Not enough free space to swap that bag."] = "Espaço livre insuficiente para trocar essa bolsa."
L["One movable window showing every bag slot in a Dragonflight-style grid. Takes over bag opening and replaces the per-window 'Retail bags' restyle. Reload (/reload) to apply."] = "Uma janela móvel mostrando todos os espaços de bolsa em uma grade no estilo Dragonflight. Assume a abertura das bolsas e substitui o reestilo 'Bolsas retail' por janela. /reload para aplicar."
L["Quality"] = "Qualidade"
L["Red-tint unusable items"] = "Tingir de vermelho os itens inutilizáveis"
L["Restyle the bag windows with the Dragonflight metal frame, portrait, and item quality borders. Disable to keep the stock Blizzard bags. Reload (/reload) to apply."] = "Reestiliza as janelas de bolsa com a moldura metálica do Dragonflight, retrato e bordas de qualidade. Desative para manter as bolsas originais da Blizzard. /reload para aplicar."
L["Retail bags"] = "Bolsas retail"
L["Reverse sort order"] = "Inverter a ordem"
L["Search"] = "Procurar"
L["Separate specialty bags"] = "Separar bolsas especializadas"
L["Shift-right-click to stop watching"] = "Shift+clique direito para parar de acompanhar"
L["Show item level on items"] = "Mostrar o nível de item nos itens"
L["Show keyring row"] = "Mostrar a fileira do chaveiro"
L["Sold %d junk item(s)."] = "%d item(ns) de lixo vendido(s)."
L["Sort Bags"] = "Organizar bolsas"
L["Sort by"] = "Ordenar por"
L["Sorting…"] = "Organizando…"
L["Swapping bag…"] = "Trocando bolsa…"
L["The same setting as Enable Item Level in DragonUI's options (Enhancements > Item Level). Covers the character panel and every other frame too."] = "A mesma opção de 'Ativar nível de item' nas opções do DragonUI (Melhorias > Nível de item). Vale também para o painel de personagem e todas as outras janelas."
L["Turn on Item Level in DragonUI's options (Enhancements > Item Level) first."] = "Ative antes 'Nível de item' nas opções do DragonUI (Melhorias > Nível de item)."

-- ============================================================================
-- COOLDOWN MANAGER
-- ============================================================================

L["(empty)"] = "(vazio)"
L["(your spec)"] = "(sua especialização)"
L["A ready sound plays when a COOLDOWN finishes.|nThis spell has none, so it can never play.|nClearing it also clears the badge."] = "O som de pronto toca quando um TEMPO DE RECARGA termina.|nEsta magia não tem, então ele nunca vai tocar.|nLimpá-lo também remove o distintivo."
L["A spell can be on cooldown and buffing you at the same time. The glow says which icons are buffed; the timer says how long."] = "Uma magia pode estar em recarga e beneficiando você ao mesmo tempo. O brilho mostra quais ícones têm benefício; o cronômetro, por quanto tempo."
L["Active"] = "Ativo"
L["Alert"] = "Alerta"
L["Always"] = "Sempre"
L["Auto-track buffs under %ds"] = "Acompanhar automaticamente benefícios abaixo de %ds"
L["Available"] = "Disponível"
L["Bar Content"] = "Conteúdo da barra"
L["Bar Width"] = "Largura da barra"
L["Both of these are immediate and cannot be undone from here — Revert only covers layout changes."] = "Ambas as ações são imediatas e não podem ser desfeitas daqui — 'Reverter' cobre apenas mudanças de leiaute."
L["Buff Bars"] = "Barras de benefícios"
L["Buff Icons"] = "Ícones de benefícios"
L["Buff tracking"] = "Acompanhamento de benefícios"
L["Buffed spells"] = "Magias com benefício"
L["Buffs you have not seen before are recorded and listed under Not Displayed on the Tracked Buffs tab, where you can assign the ones you want. Nothing appears on screen until you do."] = "Benefícios que você ainda não viu são registrados e listados em 'Não exibidos' na aba 'Benefícios acompanhados', onde você pode atribuir os que quiser. Nada aparece na tela até então."
L["Button Glow"] = "Brilho de botão"
L["Clear All Alerts"] = "Limpar todos os alertas"
L["Clear Ready Sound"] = "Limpar som de pronto"
L["Clear all alerts and sounds"] = "Limpar todos os alertas e sons"
L["Clear every configured alert and ready sound?\n\nSpell lists and frame positions are not affected."] = "Limpar todos os alertas e sons de pronto configurados?\n\nAs listas de magias e as posições das janelas não são afetadas."
L["Closes edit mode and opens the Cooldown Manager window, which carries the settings that are not per-viewer: alerts, ready sounds, buff tracking, icon fit and the resets."] = "Fecha o modo de edição e abre a janela do Gerenciador de recargas, que reúne as configurações que não pertencem a um visualizador específico: alertas, sons de pronto, acompanhamento de benefícios, ajuste de ícones e as redefinições."
L["Cooldown Manager"] = "Gerenciador de recargas"
L["Cooldown Manager Settings"] = "Configurações do Gerenciador de recargas"
L["Cooldown Manager layout string (Ctrl+C to copy):"] = "Código de leiaute do Gerenciador de recargas (Ctrl+C para copiar):"
L["Copy"] = "Copiar"
L["Defensives, interrupts, CC and escapes."] = "Defensivas, interrupções, controle e fugas."
L["Delete"] = "Excluir"
L["Delete the layout \"%s\"?"] = "Excluir o leiaute \"%s\"?"
L["Drag onto Essential or Utility to track it."] = "Arraste para 'Essenciais' ou 'Utilidades' para acompanhar."
L["Draw the countdown number on each icon."] = "Mostrar a contagem regressiva em cada ícone."
L["Each viewer's own settings — size, spacing, orientation, visibility, what its icons show — live on the frame, in edit mode, where you can see what you are changing. These open edit mode with that viewer selected and its settings already up. Closes this window; not available in combat."] = "As configurações próprias de cada visualizador — tamanho, espaçamento, orientação, visibilidade e o que seus ícones mostram — ficam na própria janela, no modo de edição, onde você vê o que está mudando. Estes botões abrem o modo de edição com aquele visualizador selecionado e suas configurações já abertas. Fecha esta janela; indisponível em combate."
L["Enable Cooldown Manager"] = "Ativar o Gerenciador de recargas"
L["Enabled"] = "Ativado"
L["Essential Cooldowns"] = "Recargas essenciais"
L["Everything"] = "Tudo"
L["Everything (no spec)"] = "Tudo (sem especialização)"
L["Everything the Cooldown Manager can be told to do that is not about one viewer's layout. Layout and position both live on the frame itself, in edit mode (/dui edit) — click a viewer there for its own settings, or use the buttons just below to go straight to one."] = "Tudo o que o Gerenciador de recargas pode fazer que não diz respeito ao leiaute de um visualizador. Leiaute e posição ficam na própria janela, no modo de edição (/dui edit) — clique ali em um visualizador para ver suas configurações, ou use os botões abaixo para ir direto a um."
L["Export Layout"] = "Exportar leiaute"
L["FX Style"] = "Estilo de efeito"
L["Flashes once, the moment the cooldown finishes.|nWorks for every spell."] = "Pisca uma vez, assim que a recarga termina.|nFunciona para todas as magias."
L["Frame strength"] = "Intensidade da moldura"
L["Gap between icons. Retail offsets this by -4, so the low end overlaps slightly — that is the stock look, not a bug."] = "Espaço entre os ícones. O retail desloca isso em -4, então na ponta baixa eles se sobrepõem um pouco — essa é a aparência original, não um erro."
L["Glow while buffed"] = "Brilhar enquanto houver benefício"
L["Glows during the last %d%% of this buff's|nremaining time."] = "Brilha durante os últimos %d%% do tempo|nrestante deste benefício."
L["Glows during the last %d%% of this spell's own|nbuff or debuff."] = "Brilha durante os últimos %d%% do próprio|nbenefício ou prejuízo desta magia."
L["Glows for as long as the spell is off cooldown|nand affordable."] = "Brilha enquanto a magia estiver pronta|ne você puder pagá-la."
L["Glows for as long as this buff is on you.|n|nThe one that works for a proc: it asks whether the|nbuff is up, not whether something is castable|nor off cooldown."] = "Brilha enquanto este benefício estiver em você.|n|nO indicado para um proc: verifica se o|nbenefício está ativo, não se algo pode ser conjurado|nou está fora de recarga."
L["Glows for as long as this spell's effect is|nup on %s."] = "Brilha enquanto o efeito desta magia|nestiver ativo em %s."
L["Halo the icon gold while the spell's buff (or, for a shaman, its totem) is up."] = "Cerca o ícone de dourado enquanto o benefício da magia (ou, para xamãs, seu totem) estiver ativo."
L["Hidden"] = "Oculto"
L["Hide When Inactive"] = "Ocultar quando inativo"
L["Horizontal"] = "Horizontal"
L["How many icons before the layout wraps. Vertical orientation reads this as icons per column."] = "Quantos ícones antes de o leiaute quebrar a linha. Na orientação vertical, isso conta como ícones por coluna."
L["Icon Direction"] = "Direção dos ícones"
L["Icon Limit"] = "Limite de ícones"
L["Icon Only"] = "Somente ícone"
L["Icon Padding"] = "Espaçamento dos ícones"
L["Icon Size"] = "Tamanho dos ícones"
L["Icon and Name"] = "Ícone e nome"
L["Icon fit"] = "Ajuste dos ícones"
L["Icon inset"] = "Recuo do ícone"
L["Import"] = "Importar"
L["Import Layout"] = "Importar leiaute"
L["In Combat"] = "Em combate"
L["Lasts %s sec"] = "Dura %s s"
L["Layouts"] = "Leiautes"
L["Layouts include appearance"] = "Os leiautes incluem a aparência"
L["Left"] = "Esquerda"
L["Load the %s starter layout?\n\nEssential is set to that spec's spells. Everything else for your class moves to Not Displayed — nothing is deleted, and you can drag any of it back.\n\nTracked auras, trinkets, alerts and frame positions are not affected."] = "Carregar o leiaute inicial de %s?\n\n'Essenciais' passa a ter as magias dessa especialização. Todo o resto da sua classe vai para 'Não exibidos' — nada é excluído e você pode arrastar de volta.\n\nAuras acompanhadas, berloques, alertas e posições de janelas não são afetados."
L["Marching Ants"] = "Formigas em marcha"
L["Move to %s"] = "Mover para %s"
L["Name Only"] = "Somente nome"
L["Name this layout:"] = "Dê um nome a este leiaute:"
L["New Layout"] = "Novo leiaute"
L["None"] = "Nenhum"
L["Not displayed on any viewer"] = "Não exibido em nenhum visualizador"
L["Not yet learned"] = "Ainda não aprendido"
L["Nothing to undo. It covers LAYOUTS, not the settings|non these tabs — a viewer's own size and position revert|nfrom its edit-mode panel instead."] = "Nada a desfazer. Isso cobre LEIAUTES, não as configurações|ndestas abas — o tamanho e a posição de um visualizador|nsão revertidos pelo painel do modo de edição dele."
L["Off by default. Turn on to show the four viewers; turn off to hide them again. Takes effect immediately either way, and nothing is forgotten — this switch stores one flag and touches nothing else, so your setup comes back exactly as you left it."] = "Desativado por padrão. Ative para mostrar os quatro visualizadores; desative para ocultá-los de novo. O efeito é imediato nos dois sentidos e nada é esquecido: esta chave guarda um único indicador e não mexe em mais nada, então sua configuração volta exatamente como você deixou."
L["Off, both specs share one set of lists. Turning it on copies the layout you have now into the spec you are in."] = "Desativado, as duas especializações compartilham um mesmo conjunto de listas. Ao ativar, o leiaute atual é copiado para a especialização em que você está."
L["Off, loading or importing a layout changes only what you track — lists, tracked buffs, trinkets, alerts and sounds. On, it also applies the orientation, icons per row, size, padding and opacity the layout was saved with.|n|nLayouts always SAVE appearance either way, so this only decides what happens when one is applied. Revert always puts appearance back, whatever this says."] = "Desativado, carregar ou importar um leiaute muda apenas o que você acompanha: listas, benefícios acompanhados, berloques, alertas e sons. Ativado, aplica também a orientação, os ícones por fileira, o tamanho, o espaçamento e a opacidade com que o leiaute foi salvo.|n|nOs leiautes sempre SALVAM a aparência de qualquer forma, então isto decide apenas o que acontece ao aplicá-los. 'Reverter' sempre restaura a aparência, independentemente desta opção."
L["Off, orientation, icons per row, size, padding and opacity are one setup for every character. On, each character can differ — until you change something here it still follows the shared setup, so nothing moves when you tick this, and unticking it gives the shared setup back without losing what you changed."] = "Desativado, a orientação, os ícones por fileira, o tamanho, o espaçamento e a opacidade formam uma única configuração para todos os personagens. Ativado, cada personagem pode diferir: até você mudar algo aqui, ele ainda segue a configuração compartilhada, então nada se move ao marcar esta opção, e desmarcá-la devolve a configuração compartilhada sem perder o que você alterou."
L["Offensive burst and damage cooldowns."] = "Recargas ofensivas de explosão e dano."
L["Opacity"] = "Opacidade"
L["Open Cooldown Manager"] = "Abrir o Gerenciador de recargas"
L["Opens a share string you can copy with Ctrl+C.|nIt covers this class's spell lists, tracked auras,|ntrinket placement, alerts and sounds."] = "Abre um código de compartilhamento que você pode copiar com Ctrl+C.|nEle cobre as listas de magias desta classe, as auras acompanhadas,|no posicionamento de berloques, os alertas e os sons."
L["Opens the Cooldown Manager window (/cdm) on its Spells tab. Needs the module on — the window configures the viewers, so it goes away with them."] = "Abre a janela do Gerenciador de recargas (/cdm) na aba 'Magias'. Requer o módulo ativado: a janela configura os visualizadores, então some junto com eles."
L["Options"] = "Opções"
L["Orientation"] = "Orientação"
L["Pandemic Border"] = "Borda de pandemia"
L["Paste a Cooldown Manager layout string:"] = "Cole um código de leiaute do Gerenciador de recargas:"
L["Ready Sound"] = "Som de pronto"
L["Ready sound: %s"] = "Som de pronto: %s"
L["Refresh"] = "Renovar"
L["Refresh Window"] = "Janela de renovação"
L["Remove"] = "Remover"
L["Remove every per-spell alert and ready sound. Spell lists and positions are not affected."] = "Remove todos os alertas e sons de pronto por magia. As listas de magias e as posições não são afetadas."
L["Rename"] = "Renomear"
L["Requires the %s talent"] = "Requer o talento %s"
L["Reset"] = "Redefinir"
L["Reset %s to its default layout?\n\nThis viewer's position, size, orientation and visibility all go back to stock. Nothing else is affected, and it cannot be undone."] = "Redefinir %s para o leiaute padrão?\n\nA posição, o tamanho, a orientação e a visibilidade deste visualizador voltam ao original. Nada mais é afetado, e não pode ser desfeito."
L["Reset Spell Lists"] = "Redefinir listas de magias"
L["Reset spell and buff lists"] = "Redefinir listas de magias e benefícios"
L["Reset this class's Cooldown Manager spell and buff lists to their defaults?\n\nOther classes, alerts, sounds and frame positions are not affected."] = "Redefinir para o padrão as listas de magias e benefícios do Gerenciador de recargas desta classe?\n\nOutras classes, alertas, sons e posições de janelas não são afetados."
L["Reset to the starter layout?\n\nThis reverts every Cooldown Manager edit — spells, tracked auras, trinket placement, alerts and sounds — to their defaults, and clears your saved-layout selection.\n\nFrame positions are not affected."] = "Voltar ao leiaute inicial?\n\nIsso reverte para o padrão todas as alterações do Gerenciador de recargas — magias, auras acompanhadas, posicionamento de berloques, alertas e sons — e limpa sua seleção de leiaute salvo.\n\nAs posições das janelas não são afetadas."
L["Restore the curated defaults and the auto-track window for THIS CLASS, clearing its spell lists, aura assignments and trinket placement. Other classes, alerts, sounds and positions are not affected."] = "Restaura os padrões selecionados e a janela de acompanhamento automático para ESTA CLASSE, limpando suas listas de magias, atribuições de auras e posicionamento de berloques. Outras classes, alertas, sons e posições não são afetados."
L["Retail's Cooldown Manager, driven from curated per-class cooldown lists. |cffffcc55Off by default|r — it adds four viewers to the middle of your screen, so it waits to be asked. Every setting — which spells and buffs are tracked, each viewer's layout, size and visibility, alerts and ready sounds — lives in the Cooldown Manager window itself (/cdm). Drag the viewers with DragonUI's editor mode to reposition them, and right-click one there for its own layout settings."] = "O Gerenciador de recargas do retail, alimentado por listas de recargas selecionadas por classe. |cffffcc55Desativado por padrão|r — ele adiciona quatro visualizadores ao centro da sua tela, então espera ser solicitado. Todas as configurações — quais magias e benefícios são acompanhados, o leiaute, o tamanho e a visibilidade de cada visualizador, os alertas e os sons de pronto — ficam na própria janela do Gerenciador (/cdm). Arraste os visualizadores com o modo de edição do DragonUI para reposicioná-los e clique com o botão direito em um deles ali para ver suas configurações de leiaute."
L["Retail's behaviour: while buffed, the icon counts down the BUFF. Off, it counts down the spell's cooldown and the glow alone marks it as buffed — which is clearer when the two differ, as on Prayer of Mending."] = "Comportamento do retail: enquanto houver benefício, o ícone conta o BENEFÍCIO. Desativado, ele conta a recarga da magia e só o brilho indica o benefício — o que fica mais claro quando os dois divergem, como em 'Prece de Cura'."
L["Revert"] = "Reverter"
L["Right"] = "Direita"
L["Save, load, import and export the whole|nCooldown Manager setup for this class."] = "Salvar, carregar, importar e exportar toda a configuração|ndo Gerenciador de recargas desta classe."
L["Separate appearance per character"] = "Aparência separada por personagem"
L["Separate layout per spec"] = "Leiaute separado por especialização"
L["Short-duration buffs and procs, as depleting bars."] = "Benefícios e procs de curta duração, como barras que esvaziam."
L["Short-duration buffs and procs, as icons."] = "Benefícios e procs de curta duração, como ícones."
L["Show Timer"] = "Mostrar cronômetro"
L["Show Tooltips"] = "Mostrar dicas"
L["Show Unlearned"] = "Mostrar não aprendidos"
L["Show a slot only while its aura is active."] = "Mostrar um espaço apenas enquanto sua aura estiver ativa."
L["Show a tooltip when hovering an icon."] = "Mostrar uma dica ao passar o cursor sobre um ícone."
L["Show every short buff the moment it lands, without assigning it first. Convenient on a character you are still setting up; in a raid it fills the viewers with other people's cooldowns, food and flasks."] = "Mostra todo benefício curto assim que ele é aplicado, sem atribuí-lo antes. Conveniente em um personagem que você ainda está configurando; numa raide, enche os visualizadores com recargas, comidas e frascos dos outros."
L["Show the buff's time, not the cooldown"] = "Mostrar o tempo do benefício, não o da recarga"
L["Show them as"] = "Mostrá-los como"
L["Show this viewer at all. The editor handle stays either way, so this is reversible from right here."] = "Exibir este visualizador ou não. A alça de edição permanece de qualquer forma, então isto é reversível daqui mesmo."
L["Sparkles"] = "Cintilações"
L["Talent specs"] = "Especializações de talento"
L["The frame is a soft shadow that falls on the icon's outer edge, so it only shows where there is icon underneath it. Strength draws it more than once to deepen it — that is also what makes its rounded corners read, since the icons themselves cannot be rounded here. Inset shrinks the icon, which slides the shadow off it, so raise that one sparingly."] = "A moldura é uma sombra suave que cai sobre a borda externa do ícone, então só aparece onde há ícone embaixo. A intensidade a desenha mais de uma vez para aprofundá-la — é também o que torna visíveis seus cantos arredondados, já que os próprios ícones não podem ser arredondados aqui. O recuo encolhe o ícone, o que desliza a sombra para fora dele, então aumente esse valor com parcimônia."
L["The full curated list for your class, both specs' spells|nincluded. This is what the Cooldown Manager shipped with|nbefore per-spec starters."] = "A lista completa selecionada para sua classe, com as magias|ndas duas especializações. É o que o Gerenciador de recargas trazia|nantes dos leiautes iniciais por especialização."
L["Tracked automatically. Drag it into a section to pin it there."] = "Acompanhado automaticamente. Arraste-o para uma seção para fixá-lo ali."
L["Undoes the last layout change — applying a layout,|nimporting one, or the starter reset.|n|nOne step, and only for this session."] = "Desfaz a última mudança de leiaute — aplicar um leiaute,|nimportar um ou redefinir para o inicial.|n|nUm único passo, e apenas nesta sessão."
L["Usable"] = "Utilizável"
L["Use Starter Layout"] = "Usar leiaute inicial"
L["Utility Cooldowns"] = "Recargas de utilidade"
L["Vertical"] = "Vertical"
L["Viewer layout"] = "Leiaute do visualizador"
L["Visibility"] = "Visibilidade"
L["When this viewer is on screen at all. Hidden still leaves the editor handle here."] = "Quando este visualizador aparece na tela. 'Oculto' ainda deixa a alça de edição aqui."
L["Which of the two buff viewers auto-tracked buffs land in."] = "Em qual dos dois visualizadores de benefícios caem os acompanhados automaticamente."
L["Which spells and buffs you track is remembered separately for each talent spec, so a Discipline layout and a Holy one do not overwrite each other. Where each viewer sits is always remembered per character; the appearance settings are shared unless you say otherwise below."] = "Quais magias e benefícios você acompanha é lembrado separadamente para cada especialização de talento, então um leiaute de Disciplina e um de Sagrado não se sobrescrevem. Onde cada visualizador fica é sempre lembrado por personagem; as configurações de aparência são compartilhadas, a não ser que você indique o contrário abaixo."
L["is turned off. Enable it in DragonUI's options, under New Era > Cooldown Manager."] = "está desativado. Ative-o nas opções do DragonUI, em New Era > Gerenciador de recargas."
L["you"] = "você"
L["|n|nOn a buff row this is about RE-CASTING it,|nnot about the buff being up — that is Active."] = "|n|nNuma linha de benefício, isto trata de CONJURAR de novo,|nnão de o benefício estar ativo — isso é 'Ativo'."
L["|n|nThe one for a DoT or a shield: it asks whether|nthe aura is up, not whether the cooldown is ready."] = "|n|nO indicado para um DoT ou escudo: verifica se|na aura está ativa, não se a recarga está pronta."
L["|n|nThis one also waits for a target below %d%% health."] = "|n|nEste também espera um alvo abaixo de %d%% de vida."
L["|n|n|cff40ff40Applies %s to %s, so this will work.|r"] = "|n|n|cff40ff40Aplica %s em %s, então isto vai funcionar.|r"
L["|n|n|cff40ff40Its aura is active now, so this will work.|r"] = "|n|n|cff40ff40A aura está ativa agora, então isto vai funcionar.|r"
L["|n|n|cffffd200No aura of this name is up right now.|r"] = "|n|n|cffffd200Nenhuma aura com esse nome está ativa no momento.|r"

-- ============================================================================
-- ADVENTURE GUIDE
-- ============================================================================

L["(No abilities recorded for this encounter.)"] = "(Nenhuma habilidade registrada para este encontro.)"
L["(no model)"] = "(sem modelo)"
L["Adventure Guide"] = "Guia de aventuras"
L["Eastern Kingdoms"] = "Reinos do Leste"
L["Kalimdor"] = "Kalimdor"
L["Model will load once seen within this session due to client limitations."] = "O modelo será carregado assim que for visto nesta sessão, por limitações do cliente."
L["Phase %d"] = "Fase %d"
L["The Adventure Guide: bosses, abilities, and loot for Classic and Burning Crusade dungeons and raids (/aguide)."] = "O Guia de aventuras: chefes, habilidades e despojos das masmorras e raides de Classic e Burning Crusade (/aguide)."

-- ============================================================================
-- GUILD
-- ============================================================================

L["GuildControlPopupFrame is missing on this client."] = "GuildControlPopupFrame não existe neste cliente."
L["Modern Communities-style guild window (Roster / Info / Chat)."] = "Janela de guilda moderna no estilo Comunidades (Lista / Informações / Bate-papo)."
L["Promote"] = "Promover"

-- ============================================================================
-- LEVEL UP DISPLAY
-- ============================================================================

L["Battleground available"] = "Campo de batalha disponível"
L["Can be learned from a trainer"] = "Pode ser aprendido com um treinador"
L["Dungeon available"] = "Masmorra disponível"
L["Enable Level Up Display"] = "Ativar o aviso de subida de nível"
L["Level Up Display"] = "Aviso de subida de nível"
L["New Feature"] = "Novo recurso"
L["New Riding Skill"] = "Nova perícia de montaria"
L["New Talent Point"] = "Novo ponto de talento"
L["New Talent Points"] = "Novos pontos de talento"
L["New rank available"] = "Nova patente disponível"
L["On by default. Turn off to stop the banner appearing on level-up; the harvest keeps running either way, so turning it back on costs nothing."] = "Ativado por padrão. Desative para que o banner não apareça ao subir de nível; a coleta continua funcionando de qualquer forma, então reativar não custa nada."
L["Play the level-up sound"] = "Tocar o som de subida de nível"
L["Raid available"] = "Raide disponível"
L["Retail's level-up banner. What it announces is read from |cffffcc55this server|r — abilities and their levels come from your class trainer's own list, battlegrounds and dungeons from the client's brackets. Visit a trainer once to fill it in; |cffffcc55/nelevelup coverage|r shows what it knows."] = "O banner de subida de nível do retail. O que ele anuncia é lido |cffffcc55deste servidor|r — as habilidades e seus níveis vêm da lista do seu treinador de classe, e os campos de batalha e masmorras das faixas do cliente. Visite um treinador uma vez para preencher; |cffffcc55/nelevelup coverage|r mostra o que ele conhece."
L["Talents"] = "Talentos"
L["You have reached"] = "Você alcançou"
L["level %d"] = "o nível %d"
L["|cffffcc55Off by default.|r The game already plays its own fanfare when you level, so this only adds a second copy on top of it. Turn it on if you want /nelevelup previews to make a sound, since those fire no game sound of their own."] = "|cffffcc55Desativado por padrão.|r O jogo já toca a própria fanfarra ao subir de nível, então isto apenas acrescenta uma segunda por cima. Ative se quiser que as prévias do /nelevelup emitam som, já que elas não disparam nenhum som do jogo."

-- ============================================================================
-- PROFESSIONS
-- ============================================================================

L["Auctionator API not available for reagent scans."] = "A API do Auctionator não está disponível para varreduras de reagentes."
L["Auctionator scan started for recipe reagents."] = "Varredura do Auctionator iniciada para os reagentes da receita."
L["Open the Auction House first to run Auctionator scans."] = "Abra antes a Casa de Leilões para executar varreduras do Auctionator."
L["Requires the Auction House window to be open."] = "Requer a janela da Casa de Leilões aberta."
L["Requires: %s"] = "Requer: %s"
L["Retail-style crafting window for all professions."] = "Janela de criação no estilo retail para todas as profissões."
L["Scan AH"] = "Varrer CL"
L["Searches Auctionator for the selected recipe and its reagents."] = "Procura no Auctionator a receita selecionada e seus reagentes."

-- ============================================================================
-- SOCIAL
-- ============================================================================

L["Away"] = "Ausente"
L["Busy"] = "Ocupado"
L["Cancel Extend"] = "Cancelar prorrogação"
L["Enter a note for %s:"] = "Escreva uma anotação para %s:"
L["Extend"] = "Prorrogar"
L["Extended"] = "Prorrogado"
L["ID: %s"] = "ID: %s"
L["Instance"] = "Instância"
L["Modern friends window (Friends / Ignore / Who) with a Guild tab."] = "Janela de amigos moderna (Amigos / Ignorados / Quem) com aba de guilda."
L["Promote to Assistant"] = "Promover a assistente"
L["Promote to Raid Leader"] = "Promover a líder de raide"
L["Resets In"] = "Reinicia em"
L["Set Note"] = "Definir anotação"
L["You are not saved to any instances."] = "Você não está salvo em nenhuma instância."

-- ============================================================================
-- SPELLBOOK
-- ============================================================================

L["Spellbook"] = "Grimório"
L["The modern Dragonflight spellbook window. Disable to keep the stock Blizzard spellbook."] = "A janela moderna de grimório no estilo Dragonflight. Desative para manter o grimório original da Blizzard."

-- ============================================================================
-- TALENTS
-- ============================================================================

L["  %s: have %d, build wants %d"] = "  %s: você tem %d, a build pede %d"
L["%s\n\nImport anyway?"] = "%s\n\nImportar mesmo assim?"
L["ACTIVE EFFECTS"] = "EFEITOS ATIVOS"
L["Activate"] = "Ativar"
L["Copy this build string (Ctrl+C). Talented & the WoWhead/wotlkdb calculators import it too:"] = "Copie este código de build (Ctrl+C). O Talented e as calculadoras do WoWhead/wotlkdb também o importam:"
L["Delete loadout '%s'?"] = "Excluir a configuração '%s'?"
L["GLYPHS"] = "GLIFOS"
L["Glyph options"] = "Opções de glifos"
L["Glyphs"] = "Glifos"
L["Import…"] = "Importar…"
L["Loadouts"] = "Configurações"
L["Locked"] = "Bloqueado"
L["MAJOR GLYPHS"] = "GLIFOS MAIORES"
L["MINOR GLYPHS"] = "GLIFOS MENORES"
L["NO ACTIVE EFFECTS"] = "SEM EFEITOS ATIVOS"
L["Name this imported loadout:"] = "Dê um nome a esta configuração importada:"
L["Name this loadout (saves your current spec):"] = "Dê um nome a esta configuração (salva sua especialização atual):"
L["Paste a talent string or calculator URL (Talented / WoWhead / wotlkdb):"] = "Cole um código de talentos ou uma URL de calculadora (Talented / WoWhead / wotlkdb):"
L["Pet"] = "Ajudante"
L["Remove this glyph?"] = "Remover este glifo?"
L["Rename loadout:"] = "Renomear configuração:"
L["Rename specialization"] = "Renomear especialização"
L["Rename this specialization (letters only, max %d):"] = "Renomeie esta especialização (somente letras, máx. %d):"
L["Save current spec…"] = "Salvar especialização atual…"
L["Server uses custom talents"] = "O servidor usa talentos personalizados"
L["Show glyph effects"] = "Mostrar efeitos dos glifos"
L["Show glyph names"] = "Mostrar nomes dos glifos"
L["Tags exported builds with this realm so imports onto other layouts warn first."] = "Marca as builds exportadas com este reino para que importações em outros leiautes avisem antes."
L["Talents Panel"] = "Painel de talentos"
L["The modern talents window. Turn off to use the standard Blizzard talent window."] = "A janela de talentos moderna. Desative para usar a janela de talentos padrão da Blizzard."
L["This loadout has fewer points in some talents than you've already spent, so it needs a respec first:\n"] = "Esta configuração tem menos pontos em alguns talentos do que você já gastou, então precisa de uma redistribuição antes:\n"
L["Toggle slot name labels and the active-effects list."] = "Alterna os rótulos de nome dos espaços e a lista de efeitos ativos."
L["Unlock Spec"] = "Desbloquear especialização"
L["\n\nReset at a class trainer, then load again. (The rest has been staged — click Apply to learn it.)"] = "\n\nRedistribua com um treinador de classe e carregue novamente. (O restante está preparado — clique em 'Aplicar' para aprender.)"

-- ============================================================================
-- OPTIONS PANEL
-- ============================================================================

L["Adventure Guide (Encounter Journal)"] = "Guia de aventuras (Diário de encontros)"
L["Auction House"] = "Casa de Leilões"
L["Boss and loot browser. Requires a /reload to take effect (the micro button doesn't re-check this live)."] = "Navegador de chefes e despojos. Requer /reload para ter efeito (o microbotão não reconfere isso ao vivo)."
L["Click for this frame's settings."] = "Clique para ver as configurações desta janela."
L["Combined Bag"] = "Bolsa combinada"
L["Custom"] = "Personalizado"
L["Custom scale"] = "Escala personalizada"
L["Drag to move."] = "Arraste para mover."
L["Each window's size: \"Use UI scale\" follows the game's UI Scale slider, \"No scaling\" stays pixel-perfect, \"Custom\" uses its slider. The custom slider is greyed out and locked unless that window's mode is set to Custom."] = "O tamanho de cada janela: \"Usar escala da interface\" segue o controle de escala do jogo, \"Sem escala\" mantém a precisão de pixel e \"Personalizado\" usa o próprio controle. O controle personalizado fica esmaecido e travado a menos que o modo daquela janela seja 'Personalizado'."
L["Guild"] = "Guilda"
L["Looking For Group"] = "Busca por grupo"
L["Looking For Group (Dungeon/Raid Finder)"] = "Busca por grupo (masmorras/raides)"
L["NewEra panels ported onto DragonUI. Toggle a panel below to enable or disable it. Panels appear here as their modules load."] = "Painéis do NewEra portados para o DragonUI. Ative ou desative um painel abaixo. Os painéis aparecem aqui conforme seus módulos são carregados."
L["No scaling"] = "Sem escala"
L["Our all-in-one bag window. Turn OFF to use the stock Blizzard bags instead. Reload (/reload) to apply."] = "Nossa janela de bolsas tudo-em-um. DESATIVE para usar as bolsas originais da Blizzard. /reload para aplicar."
L["Professions"] = "Profissões"
L["Reload (/reload) to apply."] = "/reload para aplicar."
L["Scale mode"] = "Modo de escala"
L["Scaling controls are unavailable: the 'core\\Scale.lua' file isn't loaded. Make sure your installed DragonUI_NewEra includes core/Scale.lua AND its line in the .toc, then /reload."] = "Os controles de escala não estão disponíveis: o arquivo 'core\\Scale.lua' não foi carregado. Verifique se a sua instalação do DragonUI_NewEra inclui core/Scale.lua E a linha dele no .toc, e então use /reload."
L["Scaling controls need a newer DragonUI options panel (AddSlider/AddDropdown)."] = "Os controles de escala precisam de um painel de opções do DragonUI mais recente (AddSlider/AddDropdown)."
L["Social"] = "Social"
L["Social (Friends/Who/Guild/Chat/Raid)"] = "Social (Amigos/Quem/Guilda/Bate-papo/Raide)"
L["Use DragonUI's window in place of the Blizzard default. Changes take effect after a /reload."] = "Usar a janela do DragonUI no lugar da padrão da Blizzard. As mudanças têm efeito após um /reload."
L["Use UI scale"] = "Usar escala da interface"
L["Window Scaling"] = "Escala das janelas"
L["Windows"] = "Janelas"

-- ============================================================================
-- SHARED UI
-- ============================================================================

L["Select All"] = "Selecionar tudo"

-- ============================================================================
-- BOSS TIMERS (modules/bossmods)
-- ============================================================================

L["Boss Timers"] = true
L["Boss Abilities"] = true
L["Boss Warnings"] = true
L["Boss Warning - Critical"] = true
L["Boss Warning - Medium"] = true
L["Boss Warning - Minor"] = true
L["Boss ability timers as a retail-style timeline or bar list. Reads its encounter data from DBM; without DBM installed there is nothing to show."] = true
L["Large on-screen warnings for important boss abilities. Needs DBM and the Boss Timers module."] = true
L["|cffff5555DBM is not installed.|r This module renders boss ability timers, it does not detect them — the encounter data comes from Deadly Boss Mods. Install DBM and reload to use it; the switches below are saved either way."] = true
L["Retail's boss ability timeline, drawn from |cffffcc55DBM's|r timers. Shows as a vertical rail of ability icons sliding toward now, or as a list of depleting bars. |cffffcc55Off by default.|r"] = true
L["|cffffcc55Everything else is on the frames themselves.|r Open |cffffcc55/dragonui edit|r, click a Boss Timers handle, and its own dialog carries the view, size, length, opacity, tooltips and the rest — each warning tier included, edited from the tier you clicked."] = true
L["Enable Boss Timers"] = true
L["The timeline and the three warning lines together. While it is on, DBM's own bars and warnings are hidden so the same timers are not drawn twice — its sounds and voice packs are left alone. Off by default. Reload (/reload) to apply."] = true
L["View"] = true
L["Timeline (rail)"] = true
L["Bars"] = true
L["Show the frame"] = true
L["Only while timers are running"] = true
L["Icon size"] = true
L["Rail length"] = true
L["Bar width"] = true
L["Space between bars"] = true
L["Show the countdown"] = true
L["Show the ability name"] = true
L["Timeline view only — the bar list always names its abilities."] = true
L["Show a test timer"] = true
L["Runs four sample timers and one warning through the same path a real DBM timer takes, so what you see is what an encounter will look like."] = true
L["Glow when an ability is imminent"] = true
L["On by default. The action-button proc glow, held for the last five seconds before an ability lands. It stands in for a retail effect this client cannot draw; with it off you get only the brief border flash, which is easy to miss."] = true
L["Revert Changes"] = true
L["Reset to Default"] = true
L["Timeline view only. How far out the rail reaches — the icons space themselves along it."] = true
L["Bars view only."] = true
L["Size"] = true
L["Scales the whole frame — the rail, the icons and the text together. Icon Size below scales only the icons."] = true
L["Background"] = true
L["The plate behind the frame. Retail ships it invisible."] = true
L["Scales the whole warning — text and both flanking icons together."] = true
L["The two spell icons either side of the text."] = true
L["Orientation"] = "Orientação"
L["Vertical"] = "Vertical"
L["Horizontal"] = "Horizontal"
L["Icon direction"] = true
L["Down / Right"] = true
L["Up / Left"] = true
L["Tooltips"] = true
L["At the cursor"] = true
L["Beside the frame"] = true
L["Off"] = true
L["Flip horizontally"] = true
L["Timeline view only. Which way the rail runs; the icons travel along it either way."] = true
L["Timeline view only. Which end of the rail is |cffffcc55now|r — the end abilities travel toward and go off at."] = true
L["Bars view only. Mirrors each row — the icon moves to the right and the bar drains the other way."] = true
L["Hovering an ability shows its spell tooltip. DBM raises some timers that are not a spell at all — a pull timer, a phase change — and those show their own name instead."] = true
L["Show the ability icons"] = true
L["The two copies of the ability's own icon either side of the text — what retail draws. The text already names the ability, so this is decoration; turn it off for a plain line of text."] = true
