--[[
================================================================================
DragonUI_NewEra - Russian Locale (ruRU)

Generated by tools/locale-lint/gen_locale.py from enUS.lua; edit the translation
map in tools/locale-lint/translations/ruRU.py and regenerate, or correct a
string here and port the fix back. Entries left as `= true` fall back to English.

Machine-drafted and unreviewed by a native speaker: corrections welcome. Every
entry is checked against its English key for placeholder parity
(check_keys.py --verify), so a %d or |n cannot go missing, but wording has not
been through a human pass.
================================================================================
]]

local L = LibStub("AceLocale-3.0"):NewLocale("DragonUI_NewEra", "ruRU")
if not L then return end
-- ============================================================================
-- ============================================================================
L["Alchemy"] = "Алхимия"
L["Blacksmithing"] = "Кузнечное дело"
L["Enchanting"] = "Наложение чар"
L["Engineering"] = "Инженерное дело"
L["Herbalism"] = "Травничество"
L["Leatherworking"] = "Кожевничество"
L["Mining"] = "Горное дело"
L["Smelting"] = "Выплавка металла"
L["Skinning"] = "Снятие шкур"
L["Tailoring"] = "Портняжное дело"
L["Inscription"] = "Начертание"
L["Jewelcrafting"] = "Ювелирное дело"
L["Prospecting"] = "Просеивание"
L["Cooking"] = "Кулинария"
L["First Aid"] = "Первая помощь"
L["Fishing"] = "Рыбная ловля"
L["Select a recipe to craft"] = "Выберите рецепт для создания"
L["Hide item tooltips in list"] = "Скрывать подсказки в списке"
L["Colour names by skill difficulty"] = "Окрашивать названия по сложности"
L["Plain skill bar (no animation)"] = "Обычная полоса навыка (без анимации)"
L["Create"] = "Создать"
L["Create All"] = "Создать все"
L["Show Learned"] = "Показывать изученные"
L["Has Skill Up"] = "Повышают навык"
L["Have Materials"] = "Есть реагенты"

-- ============================================================================
-- AUCTION HOUSE
-- ============================================================================

L[" -- partial scan"] = " -- частичное сканирование"
L["Auction query is throttled. Try again in a moment."] = "Запрос к аукциону ограничен. Повторите попытку через мгновение."
L["Buy out this auction for %s?"] = "Выкупить этот лот за %s?"
L["Choose search criteria and press \"Search\""] = "Выберите условия поиска и нажмите \"Поиск\""
L["Loading results..."] = "Загрузка результатов..."
L["Lvl"] = "Ур."
L["Modern visual shell for Buy/Sell/Auctions with optional Auctionator tab embedding."] = "Современный интерфейс для покупки, продажи и лотов с необязательной вкладкой Auctionator."
L["No listings."] = "Лотов нет."
L["No results. Adjust filters and search again."] = "Ничего не найдено. Измените фильтры и повторите поиск."
L["Page %d of %d  (items %d-%d of %d, from %d auction)%s"] = "Страница %d из %d  (предметы %d-%d из %d, из %d лота)%s"
L["Page %d of %d  (items %d-%d of %d, from %d auctions)%s"] = "Страница %d из %d  (предметы %d-%d из %d, из %d лотов)%s"
L["Page 1 of 1"] = "Страница 1 из 1"
L["Per Item"] = "За штуку"
L["Place a bid of %s?"] = "Сделать ставку %s?"
L["Scanning page %d of %d..."] = "Сканирование страницы %d из %d..."
L["Searching..."] = "Поиск..."
L["Sort Per Item"] = "Сортировать по цене за штуку"
L["You have no auctions."] = "У вас нет выставленных лотов."

-- ============================================================================
-- BAGS
-- ============================================================================

L["All Bags"] = "Все сумки"
L["Auto-empty old bag when swapping"] = "Опустошать старую сумку при замене"
L["Auto-sell junk at merchants"] = "Автоматически продавать хлам торговцам"
L["Bag Options"] = "Настройки сумок"
L["Category (smart)"] = "Категория (умная)"
L["Combined bag (all-in-one)"] = "Объединённая сумка (всё в одном)"
L["Item Level"] = "Уровень предмета"
L["Keys"] = "Ключи"
L["Merchant"] = "Торговец"
L["Name"] = "Название"
L["Not enough free space to swap that bag."] = "Недостаточно свободного места для замены этой сумки."
L["One movable window showing every bag slot in a Dragonflight-style grid. Takes over bag opening and replaces the per-window 'Retail bags' restyle. Reload (/reload) to apply."] = "Одно перемещаемое окно со всеми ячейками сумок в сетке в стиле Dragonflight. Берёт на себя открытие сумок и заменяет оформление отдельных окон «Сумки retail». /reload для применения."
L["Quality"] = "Качество"
L["Red-tint unusable items"] = "Подсвечивать красным непригодные предметы"
L["Restyle the bag windows with the Dragonflight metal frame, portrait, and item quality borders. Disable to keep the stock Blizzard bags. Reload (/reload) to apply."] = "Оформляет окна сумок металлической рамкой Dragonflight, портретом и рамками качества предметов. Отключите, чтобы оставить стандартные сумки Blizzard. /reload для применения."
L["Retail bags"] = "Сумки retail"
L["Reverse sort order"] = "Обратный порядок сортировки"
L["Search"] = "Поиск"
L["Separate specialty bags"] = "Отделять специализированные сумки"
L["Shift-right-click to stop watching"] = "Shift+ПКМ, чтобы прекратить отслеживание"
L["Show item level on items"] = "Показывать уровень предмета на предметах"
L["Show keyring row"] = "Показывать ряд связки ключей"
L["Sold %d junk item(s)."] = "Продано предметов хлама: %d."
L["Sort Bags"] = "Сортировать сумки"
L["Sort by"] = "Сортировать по"
L["Sorting…"] = "Сортировка…"
L["Swapping bag…"] = "Замена сумки…"
L["The same setting as Enable Item Level in DragonUI's options (Enhancements > Item Level). Covers the character panel and every other frame too."] = "Та же настройка, что и «Включить уровень предмета» в настройках DragonUI (Улучшения > Уровень предмета). Действует и на окно персонажа, и на все остальные окна."
L["Turn on Item Level in DragonUI's options (Enhancements > Item Level) first."] = "Сначала включите «Уровень предмета» в настройках DragonUI (Улучшения > Уровень предмета)."

-- ============================================================================
-- COOLDOWN MANAGER
-- ============================================================================

L["(empty)"] = "(пусто)"
L["(your spec)"] = "(ваша специализация)"
L["A ready sound plays when a COOLDOWN finishes.|nThis spell has none, so it can never play.|nClearing it also clears the badge."] = "Звук готовности звучит по окончании ВРЕМЕНИ ВОССТАНОВЛЕНИЯ.|nУ этого заклинания его нет, поэтому звук никогда не прозвучит.|nОчистка также убирает значок."
L["A spell can be on cooldown and buffing you at the same time. The glow says which icons are buffed; the timer says how long."] = "Заклинание может одновременно восстанавливаться и усиливать вас. Свечение показывает, на каких значках есть эффект, а таймер — как долго."
L["Active"] = "Активно"
L["Alert"] = "Оповещение"
L["Always"] = "Всегда"
L["Auto-track buffs under %ds"] = "Автоматически отслеживать эффекты короче %d сек."
L["Available"] = "Доступно"
L["Bar Content"] = "Содержимое полосы"
L["Bar Width"] = "Ширина полосы"
L["Both of these are immediate and cannot be undone from here — Revert only covers layout changes."] = "Оба действия выполняются сразу и отсюда не отменяются — «Откат» касается только изменений расположения."
L["Buff Bars"] = "Полосы эффектов"
L["Buff Icons"] = "Значки эффектов"
L["Buff tracking"] = "Отслеживание эффектов"
L["Buffed spells"] = "Усиленные заклинания"
L["Buffs you have not seen before are recorded and listed under Not Displayed on the Tracked Buffs tab, where you can assign the ones you want. Nothing appears on screen until you do."] = "Ранее не встречавшиеся эффекты записываются и появляются в разделе «Не отображаются» на вкладке «Отслеживаемые эффекты», где вы можете назначить нужные. До этого на экране ничего не появится."
L["Button Glow"] = "Свечение кнопки"
L["Clear All Alerts"] = "Очистить все оповещения"
L["Clear Ready Sound"] = "Очистить звук готовности"
L["Clear all alerts and sounds"] = "Очистить все оповещения и звуки"
L["Clear every configured alert and ready sound?\n\nSpell lists and frame positions are not affected."] = "Очистить все настроенные оповещения и звуки готовности?\n\nСписки заклинаний и положения окон не затрагиваются."
L["Closes edit mode and opens the Cooldown Manager window, which carries the settings that are not per-viewer: alerts, ready sounds, buff tracking, icon fit and the resets."] = "Закрывает режим редактирования и открывает окно менеджера восстановления, где собраны настройки, не относящиеся к отдельной панели: оповещения, звуки готовности, отслеживание эффектов, подгонка значков и сбросы."
L["Cooldown Manager"] = "Менеджер восстановления"
L["Cooldown Manager Settings"] = "Настройки менеджера восстановления"
L["Cooldown Manager layout string (Ctrl+C to copy):"] = "Строка расположения менеджера восстановления (Ctrl+C для копирования):"
L["Copy"] = "Копировать"
L["Defensives, interrupts, CC and escapes."] = "Защита, прерывания, контроль и способности отхода."
L["Delete"] = "Удалить"
L["Delete the layout \"%s\"?"] = "Удалить расположение \"%s\"?"
L["Drag onto Essential or Utility to track it."] = "Перетащите на «Основные» или «Вспомогательные», чтобы отслеживать."
L["Draw the countdown number on each icon."] = "Показывать отсчёт на каждом значке."
L["Each viewer's own settings — size, spacing, orientation, visibility, what its icons show — live on the frame, in edit mode, where you can see what you are changing. These open edit mode with that viewer selected and its settings already up. Closes this window; not available in combat."] = "Собственные настройки каждой панели — размер, отступы, ориентация, видимость, содержимое значков — находятся на самой рамке, в режиме редактирования, где видно, что именно вы меняете. Эти кнопки открывают режим редактирования с выбранной панелью и её настройками. Закрывает это окно; в бою недоступно."
L["Enable Cooldown Manager"] = "Включить менеджер восстановления"
L["Enabled"] = "Включено"
L["Essential Cooldowns"] = "Основные способности"
L["Everything"] = "Всё"
L["Everything (no spec)"] = "Всё (без специализации)"
L["Everything the Cooldown Manager can be told to do that is not about one viewer's layout. Layout and position both live on the frame itself, in edit mode (/dui edit) — click a viewer there for its own settings, or use the buttons just below to go straight to one."] = "Всё, что умеет менеджер восстановления, кроме расположения отдельной панели. Расположение и положение находятся на самой рамке, в режиме редактирования (/dui edit) — щёлкните там по панели для её настроек либо воспользуйтесь кнопками ниже."
L["Export Layout"] = "Экспорт расположения"
L["FX Style"] = "Стиль эффекта"
L["Flashes once, the moment the cooldown finishes.|nWorks for every spell."] = "Вспыхивает один раз, как только восстановление завершится.|nРаботает для любого заклинания."
L["Frame strength"] = "Насыщенность рамки"
L["Gap between icons. Retail offsets this by -4, so the low end overlaps slightly — that is the stock look, not a bug."] = "Расстояние между значками. Retail смещает его на -4, поэтому в нижней части диапазона они слегка перекрываются — так и должно быть, это не ошибка."
L["Glow while buffed"] = "Светиться при действующем эффекте"
L["Glows during the last %d%% of this buff's|nremaining time."] = "Светится в течение последних %d%% оставшегося|nвремени этого эффекта."
L["Glows during the last %d%% of this spell's own|nbuff or debuff."] = "Светится в течение последних %d%% собственного|nэффекта этого заклинания."
L["Glows for as long as the spell is off cooldown|nand affordable."] = "Светится, пока заклинание готово|nи его можно применить."
L["Glows for as long as this buff is on you.|n|nThe one that works for a proc: it asks whether the|nbuff is up, not whether something is castable|nor off cooldown."] = "Светится, пока этот эффект действует на вас.|n|nПодходит для срабатываний: проверяется наличие|nэффекта, а не готовность применения|nили восстановления."
L["Glows for as long as this spell's effect is|nup on %s."] = "Светится, пока эффект этого заклинания|nдействует на %s."
L["Halo the icon gold while the spell's buff (or, for a shaman, its totem) is up."] = "Окружает значок золотым ореолом, пока действует эффект заклинания (у шамана — его тотем)."
L["Hidden"] = "Скрыто"
L["Hide When Inactive"] = "Скрывать при бездействии"
L["Horizontal"] = "Горизонтально"
L["How many icons before the layout wraps. Vertical orientation reads this as icons per column."] = "Сколько значков до переноса. При вертикальной ориентации это значков в столбце."
L["Icon Direction"] = "Направление значков"
L["Icon Limit"] = "Предел значков"
L["Icon Only"] = "Только значок"
L["Icon Padding"] = "Отступ значков"
L["Icon Size"] = "Размер значков"
L["Icon and Name"] = "Значок и название"
L["Icon fit"] = "Подгонка значков"
L["Icon inset"] = "Отступ внутри значка"
L["Import"] = "Импорт"
L["Import Layout"] = "Импорт расположения"
L["In Combat"] = "В бою"
L["Lasts %s sec"] = "Длится %s сек."
L["Layouts"] = "Расположения"
L["Layouts include appearance"] = "Расположения включают оформление"
L["Left"] = "Влево"
L["Load the %s starter layout?\n\nEssential is set to that spec's spells. Everything else for your class moves to Not Displayed — nothing is deleted, and you can drag any of it back.\n\nTracked auras, trinkets, alerts and frame positions are not affected."] = "Загрузить начальное расположение «%s»?\n\nВ «Основные» попадут заклинания этой специализации. Всё остальное для вашего класса перейдёт в «Не отображаются» — ничего не удаляется, и вы можете перетащить обратно что угодно.\n\nОтслеживаемые ауры, аксессуары, оповещения и положения окон не затрагиваются."
L["Marching Ants"] = "Бегущие огни"
L["Move to %s"] = "Переместить в «%s»"
L["Name Only"] = "Только название"
L["Name this layout:"] = "Название расположения:"
L["New Layout"] = "Новое расположение"
L["None"] = "Нет"
L["Not displayed on any viewer"] = "Не отображается ни на одной панели"
L["Not yet learned"] = "Ещё не изучено"
L["Nothing to undo. It covers LAYOUTS, not the settings|non these tabs — a viewer's own size and position revert|nfrom its edit-mode panel instead."] = "Отменять нечего. Это касается РАСПОЛОЖЕНИЙ, а не настроек|nна этих вкладках — размер и положение панели|nвозвращаются из её окна режима редактирования."
L["Off by default. Turn on to show the four viewers; turn off to hide them again. Takes effect immediately either way, and nothing is forgotten — this switch stores one flag and touches nothing else, so your setup comes back exactly as you left it."] = "По умолчанию выключено. Включите, чтобы показать четыре панели; выключите, чтобы снова их скрыть. Действует сразу в обе стороны, и ничего не теряется — этот переключатель хранит один флаг и больше ничего не трогает, поэтому ваша настройка вернётся в точности такой, какой была."
L["Off, both specs share one set of lists. Turning it on copies the layout you have now into the spec you are in."] = "Выключено — обе специализации используют один набор списков. При включении текущее расположение копируется в ту специализацию, в которой вы находитесь."
L["Off, loading or importing a layout changes only what you track — lists, tracked buffs, trinkets, alerts and sounds. On, it also applies the orientation, icons per row, size, padding and opacity the layout was saved with.|n|nLayouts always SAVE appearance either way, so this only decides what happens when one is applied. Revert always puts appearance back, whatever this says."] = "Выключено — загрузка или импорт расположения меняет только то, что вы отслеживаете: списки, отслеживаемые эффекты, аксессуары, оповещения и звуки. Включено — применяются также ориентация, число значков в ряду, размер, отступ и непрозрачность, с которыми расположение было сохранено.|n|nРасположения в любом случае всегда СОХРАНЯЮТ оформление, поэтому эта настройка решает только то, что происходит при применении. «Откат» всегда возвращает оформление, что бы здесь ни стояло."
L["Off, orientation, icons per row, size, padding and opacity are one setup for every character. On, each character can differ — until you change something here it still follows the shared setup, so nothing moves when you tick this, and unticking it gives the shared setup back without losing what you changed."] = "Выключено — ориентация, число значков в ряду, размер, отступ и непрозрачность едины для всех персонажей. Включено — каждый персонаж может отличаться: пока вы что-нибудь здесь не измените, он по-прежнему следует общей настройке, поэтому при установке флажка ничего не сдвинется, а при снятии вернётся общая настройка без потери ваших изменений."
L["Offensive burst and damage cooldowns."] = "Атакующие способности всплеска урона и восстановления."
L["Opacity"] = "Непрозрачность"
L["Open Cooldown Manager"] = "Открыть менеджер восстановления"
L["Opens a share string you can copy with Ctrl+C.|nIt covers this class's spell lists, tracked auras,|ntrinket placement, alerts and sounds."] = "Открывает строку для обмена, которую можно скопировать через Ctrl+C.|nОна включает списки заклинаний этого класса, отслеживаемые ауры,|nразмещение аксессуаров, оповещения и звуки."
L["Opens the Cooldown Manager window (/cdm) on its Spells tab. Needs the module on — the window configures the viewers, so it goes away with them."] = "Открывает окно менеджера восстановления (/cdm) на вкладке «Заклинания». Требуется включённый модуль — окно настраивает панели и исчезает вместе с ними."
L["Options"] = "Настройки"
L["Orientation"] = "Ориентация"
L["Pandemic Border"] = "Рамка пандемии"
L["Paste a Cooldown Manager layout string:"] = "Вставьте строку расположения менеджера восстановления:"
L["Ready Sound"] = "Звук готовности"
L["Ready sound: %s"] = "Звук готовности: %s"
L["Refresh"] = "Обновление"
L["Refresh Window"] = "Окно обновления"
L["Remove"] = "Убрать"
L["Remove every per-spell alert and ready sound. Spell lists and positions are not affected."] = "Убирает все оповещения и звуки готовности для отдельных заклинаний. Списки заклинаний и положения не затрагиваются."
L["Rename"] = "Переименовать"
L["Requires the %s talent"] = "Требуется талант «%s»"
L["Reset"] = "Сброс"
L["Reset %s to its default layout?\n\nThis viewer's position, size, orientation and visibility all go back to stock. Nothing else is affected, and it cannot be undone."] = "Сбросить «%s» к расположению по умолчанию?\n\nПоложение, размер, ориентация и видимость этой панели вернутся к исходным. Больше ничего не затрагивается, и отменить это нельзя."
L["Reset Spell Lists"] = "Сбросить списки заклинаний"
L["Reset spell and buff lists"] = "Сбросить списки заклинаний и эффектов"
L["Reset this class's Cooldown Manager spell and buff lists to their defaults?\n\nOther classes, alerts, sounds and frame positions are not affected."] = "Сбросить списки заклинаний и эффектов менеджера восстановления для этого класса к значениям по умолчанию?\n\nДругие классы, оповещения, звуки и положения окон не затрагиваются."
L["Reset to the starter layout?\n\nThis reverts every Cooldown Manager edit — spells, tracked auras, trinket placement, alerts and sounds — to their defaults, and clears your saved-layout selection.\n\nFrame positions are not affected."] = "Вернуться к начальному расположению?\n\nЭто вернёт все изменения менеджера восстановления — заклинания, отслеживаемые ауры, размещение аксессуаров, оповещения и звуки — к значениям по умолчанию и очистит выбор сохранённого расположения.\n\nПоложения окон не затрагиваются."
L["Restore the curated defaults and the auto-track window for THIS CLASS, clearing its spell lists, aura assignments and trinket placement. Other classes, alerts, sounds and positions are not affected."] = "Восстанавливает подобранные значения по умолчанию и окно автоотслеживания для ЭТОГО КЛАССА, очищая его списки заклинаний, назначения аур и размещение аксессуаров. Другие классы, оповещения, звуки и положения не затрагиваются."
L["Retail's Cooldown Manager, driven from curated per-class cooldown lists. |cffffcc55Off by default|r — it adds four viewers to the middle of your screen, so it waits to be asked. Every setting — which spells and buffs are tracked, each viewer's layout, size and visibility, alerts and ready sounds — lives in the Cooldown Manager window itself (/cdm). Drag the viewers with DragonUI's editor mode to reposition them, and right-click one there for its own layout settings."] = "Менеджер восстановления из retail, работающий на подобранных списках способностей по классам. |cffffcc55По умолчанию выключен|r — он добавляет четыре панели в центр экрана, поэтому ждёт вашего решения. Все настройки — какие заклинания и эффекты отслеживаются, расположение, размер и видимость каждой панели, оповещения и звуки готовности — находятся в самом окне менеджера (/cdm). Перетаскивайте панели в режиме редактирования DragonUI, а щелчок правой кнопкой по панели там откроет её собственные настройки расположения."
L["Retail's behaviour: while buffed, the icon counts down the BUFF. Off, it counts down the spell's cooldown and the glow alone marks it as buffed — which is clearer when the two differ, as on Prayer of Mending."] = "Поведение как в retail: пока действует эффект, значок отсчитывает ЭФФЕКТ. Выключено — он отсчитывает восстановление заклинания, а на действующий эффект указывает только свечение, что понятнее, когда эти значения расходятся, как у «Молитвы восстановления»."
L["Revert"] = "Откат"
L["Right"] = "Вправо"
L["Save, load, import and export the whole|nCooldown Manager setup for this class."] = "Сохранение, загрузка, импорт и экспорт всей настройки|nменеджера восстановления для этого класса."
L["Separate appearance per character"] = "Отдельное оформление для каждого персонажа"
L["Separate layout per spec"] = "Отдельное расположение для каждой специализации"
L["Short-duration buffs and procs, as depleting bars."] = "Короткие эффекты и срабатывания в виде убывающих полос."
L["Short-duration buffs and procs, as icons."] = "Короткие эффекты и срабатывания в виде значков."
L["Show Timer"] = "Показывать таймер"
L["Show Tooltips"] = "Показывать подсказки"
L["Show Unlearned"] = "Показывать неизученные"
L["Show a slot only while its aura is active."] = "Показывать ячейку, только пока действует её аура."
L["Show a tooltip when hovering an icon."] = "Показывать подсказку при наведении на значок."
L["Show every short buff the moment it lands, without assigning it first. Convenient on a character you are still setting up; in a raid it fills the viewers with other people's cooldowns, food and flasks."] = "Показывает любой короткий эффект сразу при появлении, без предварительного назначения. Удобно на персонаже, которого вы ещё настраиваете; в рейде это заполнит панели чужими способностями, едой и настоями."
L["Show the buff's time, not the cooldown"] = "Показывать время эффекта, а не восстановления"
L["Show them as"] = "Показывать как"
L["Show this viewer at all. The editor handle stays either way, so this is reversible from right here."] = "Показывать ли эту панель вообще. Маркер редактирования остаётся в любом случае, поэтому изменение обратимо прямо отсюда."
L["Sparkles"] = "Искры"
L["Talent specs"] = "Специализации талантов"
L["The frame is a soft shadow that falls on the icon's outer edge, so it only shows where there is icon underneath it. Strength draws it more than once to deepen it — that is also what makes its rounded corners read, since the icons themselves cannot be rounded here. Inset shrinks the icon, which slides the shadow off it, so raise that one sparingly."] = "Рамка — это мягкая тень по внешнему краю значка, поэтому она видна только там, где под ней есть значок. Насыщенность отрисовывает её несколько раз, делая глубже, — именно это позволяет различить скруглённые углы, ведь сами значки здесь скруглить нельзя. Отступ уменьшает значок и сдвигает тень с него, поэтому повышайте его осторожно."
L["The full curated list for your class, both specs' spells|nincluded. This is what the Cooldown Manager shipped with|nbefore per-spec starters."] = "Полный подобранный список для вашего класса, включая заклинания|nобеих специализаций. Именно с этим менеджер восстановления|nпоставлялся до появления начальных наборов по специализациям."
L["Tracked automatically. Drag it into a section to pin it there."] = "Отслеживается автоматически. Перетащите в раздел, чтобы закрепить там."
L["Undoes the last layout change — applying a layout,|nimporting one, or the starter reset.|n|nOne step, and only for this session."] = "Отменяет последнее изменение расположения — применение расположения,|nего импорт или сброс к начальному.|n|nОдин шаг, и только в течение этого сеанса."
L["Usable"] = "Можно применить"
L["Use Starter Layout"] = "Использовать начальное расположение"
L["Utility Cooldowns"] = "Вспомогательные способности"
L["Vertical"] = "Вертикально"
L["Viewer layout"] = "Расположение панели"
L["Visibility"] = "Видимость"
L["When this viewer is on screen at all. Hidden still leaves the editor handle here."] = "Когда эта панель вообще присутствует на экране. «Скрыто» всё равно оставляет здесь маркер редактирования."
L["Which of the two buff viewers auto-tracked buffs land in."] = "На какую из двух панелей эффектов попадают автоматически отслеживаемые эффекты."
L["Which spells and buffs you track is remembered separately for each talent spec, so a Discipline layout and a Holy one do not overwrite each other. Where each viewer sits is always remembered per character; the appearance settings are shared unless you say otherwise below."] = "То, какие заклинания и эффекты вы отслеживаете, запоминается отдельно для каждой специализации, поэтому расположения «Послушание» и «Свет» не перезаписывают друг друга. Положение каждой панели всегда запоминается для персонажа; настройки оформления общие, если ниже не указано иное."
L["is turned off. Enable it in DragonUI's options, under New Era > Cooldown Manager."] = "выключен. Включите его в настройках DragonUI, в разделе New Era > Менеджер восстановления."
L["you"] = "вас"
L["|n|nOn a buff row this is about RE-CASTING it,|nnot about the buff being up — that is Active."] = "|n|nВ строке эффекта речь о ПОВТОРНОМ применении,|nа не о том, действует ли эффект — это «Активно»."
L["|n|nThe one for a DoT or a shield: it asks whether|nthe aura is up, not whether the cooldown is ready."] = "|n|nПодходит для периодического урона или щита: проверяется|nналичие ауры, а не готовность восстановления."
L["|n|nThis one also waits for a target below %d%% health."] = "|n|nЭтот также ждёт цель со здоровьем ниже %d%%."
L["|n|n|cff40ff40Applies %s to %s, so this will work.|r"] = "|n|n|cff40ff40Накладывает «%s» на %s, поэтому это сработает.|r"
L["|n|n|cff40ff40Its aura is active now, so this will work.|r"] = "|n|n|cff40ff40Его аура сейчас активна, поэтому это сработает.|r"
L["|n|n|cffffd200No aura of this name is up right now.|r"] = "|n|n|cffffd200Сейчас нет активной ауры с таким названием.|r"

-- ============================================================================
-- ADVENTURE GUIDE
-- ============================================================================

L["(No abilities recorded for this encounter.)"] = "(Для этого сражения способности не записаны.)"
L["(no model)"] = "(нет модели)"
L["Adventure Guide"] = "Путеводитель"
L["Eastern Kingdoms"] = "Восточные королевства"
L["Kalimdor"] = "Калимдор"
L["Model will load once seen within this session due to client limitations."] = "Модель загрузится после того, как будет увидена в этом сеансе — ограничение клиента."
L["Phase %d"] = "Фаза %d"
L["The Adventure Guide: bosses, abilities, and loot for Classic and Burning Crusade dungeons and raids (/aguide)."] = "Путеводитель: боссы, способности и добыча подземелий и рейдов Classic и Burning Crusade (/aguide)."

-- ============================================================================
-- GUILD
-- ============================================================================

L["GuildControlPopupFrame is missing on this client."] = "GuildControlPopupFrame отсутствует в этом клиенте."
L["Modern Communities-style guild window (Roster / Info / Chat)."] = "Современное окно гильдии в стиле сообществ (Состав / Сведения / Чат)."
L["Promote"] = "Повысить"

-- ============================================================================
-- LEVEL UP DISPLAY
-- ============================================================================

L["Battleground available"] = "Доступно поле боя"
L["Can be learned from a trainer"] = "Можно изучить у учителя"
L["Dungeon available"] = "Доступно подземелье"
L["Enable Level Up Display"] = "Включить объявление о новом уровне"
L["Level Up Display"] = "Объявление о новом уровне"
L["New Feature"] = "Новая возможность"
L["New Riding Skill"] = "Новый навык верховой езды"
L["New Talent Point"] = "Новое очко талантов"
L["New Talent Points"] = "Новые очки талантов"
L["New rank available"] = "Доступен новый ранг"
L["On by default. Turn off to stop the banner appearing on level-up; the harvest keeps running either way, so turning it back on costs nothing."] = "По умолчанию включено. Выключите, чтобы баннер не появлялся при получении уровня; сбор данных продолжается в любом случае, поэтому обратное включение ничего не стоит."
L["Play the level-up sound"] = "Проигрывать звук получения уровня"
L["Raid available"] = "Доступен рейд"
L["Retail's level-up banner. What it announces is read from |cffffcc55this server|r — abilities and their levels come from your class trainer's own list, battlegrounds and dungeons from the client's brackets. Visit a trainer once to fill it in; |cffffcc55/nelevelup coverage|r shows what it knows."] = "Баннер получения уровня из retail. То, что он объявляет, считывается с |cffffcc55этого сервера|r — способности и их уровни берутся из списка вашего учителя класса, а поля боя и подземелья — из диапазонов клиента. Посетите учителя один раз, чтобы заполнить данные; |cffffcc55/nelevelup coverage|r показывает, что известно."
L["Talents"] = "Таланты"
L["You have reached"] = "Вы достигли"
L["level %d"] = "%d уровня"
L["|cffffcc55Off by default.|r The game already plays its own fanfare when you level, so this only adds a second copy on top of it. Turn it on if you want /nelevelup previews to make a sound, since those fire no game sound of their own."] = "|cffffcc55По умолчанию выключено.|r Игра и так проигрывает свои фанфары при получении уровня, поэтому это лишь добавит вторые поверх. Включите, если хотите, чтобы предпросмотры /nelevelup звучали, — сами по себе они не вызывают игровых звуков."

-- ============================================================================
-- PROFESSIONS
-- ============================================================================

L["Auctionator API not available for reagent scans."] = "API Auctionator недоступен для сканирования реагентов."
L["Auctionator scan started for recipe reagents."] = "Запущено сканирование Auctionator по реагентам рецепта."
L["Open the Auction House first to run Auctionator scans."] = "Сначала откройте аукцион, чтобы запускать сканирование Auctionator."
L["Requires the Auction House window to be open."] = "Требуется открытое окно аукциона."
L["Requires: %s"] = "Требуется: %s"
L["Retail-style crafting window for all professions."] = "Окно создания предметов в стиле retail для всех профессий."
L["Scan AH"] = "Сканировать аукцион"
L["Searches Auctionator for the selected recipe and its reagents."] = "Ищет в Auctionator выбранный рецепт и его реагенты."

-- ============================================================================
-- SOCIAL
-- ============================================================================

L["Away"] = "Отошёл"
L["Busy"] = "Занят"
L["Cancel Extend"] = "Отменить продление"
L["Enter a note for %s:"] = "Введите заметку для %s:"
L["Extend"] = "Продлить"
L["Extended"] = "Продлено"
L["ID: %s"] = "ID: %s"
L["Instance"] = "Подземелье"
L["Modern friends window (Friends / Ignore / Who) with a Guild tab."] = "Современное окно друзей (Друзья / Игнор / Кто) с вкладкой гильдии."
L["Promote to Assistant"] = "Назначить помощником"
L["Promote to Raid Leader"] = "Назначить лидером рейда"
L["Resets In"] = "Сброс через"
L["Set Note"] = "Задать заметку"
L["You are not saved to any instances."] = "Вы не привязаны ни к одному подземелью."

-- ============================================================================
-- SPELLBOOK
-- ============================================================================

L["Spellbook"] = "Книга заклинаний"
L["The modern Dragonflight spellbook window. Disable to keep the stock Blizzard spellbook."] = "Современное окно книги заклинаний в стиле Dragonflight. Отключите, чтобы оставить стандартную книгу заклинаний Blizzard."

-- ============================================================================
-- TALENTS
-- ============================================================================

L["  %s: have %d, build wants %d"] = "  %s: есть %d, сборке нужно %d"
L["%s\n\nImport anyway?"] = "%s\n\nВсё равно импортировать?"
L["ACTIVE EFFECTS"] = "ДЕЙСТВУЮЩИЕ ЭФФЕКТЫ"
L["Activate"] = "Активировать"
L["Copy this build string (Ctrl+C). Talented & the WoWhead/wotlkdb calculators import it too:"] = "Скопируйте эту строку сборки (Ctrl+C). Talented и калькуляторы WoWhead/wotlkdb тоже её импортируют:"
L["Delete loadout '%s'?"] = "Удалить набор «%s»?"
L["GLYPHS"] = "СИМВОЛЫ"
L["Glyph options"] = "Настройки символов"
L["Glyphs"] = "Символы"
L["Import…"] = "Импорт…"
L["Loadouts"] = "Наборы"
L["Locked"] = "Заблокировано"
L["MAJOR GLYPHS"] = "БОЛЬШИЕ СИМВОЛЫ"
L["MINOR GLYPHS"] = "МАЛЫЕ СИМВОЛЫ"
L["NO ACTIVE EFFECTS"] = "НЕТ ДЕЙСТВУЮЩИХ ЭФФЕКТОВ"
L["Name this imported loadout:"] = "Название импортированного набора:"
L["Name this loadout (saves your current spec):"] = "Название набора (сохраняет вашу текущую специализацию):"
L["Paste a talent string or calculator URL (Talented / WoWhead / wotlkdb):"] = "Вставьте строку талантов или ссылку на калькулятор (Talented / WoWhead / wotlkdb):"
L["Pet"] = "Питомец"
L["Remove this glyph?"] = "Убрать этот символ?"
L["Rename loadout:"] = "Переименовать набор:"
L["Rename specialization"] = "Переименовать специализацию"
L["Rename this specialization (letters only, max %d):"] = "Переименуйте эту специализацию (только буквы, не более %d):"
L["Save current spec…"] = "Сохранить текущую специализацию…"
L["Server uses custom talents"] = "На сервере используются изменённые таланты"
L["Show glyph effects"] = "Показывать эффекты символов"
L["Show glyph names"] = "Показывать названия символов"
L["Tags exported builds with this realm so imports onto other layouts warn first."] = "Помечает экспортируемые сборки этим миром, чтобы импорт в другие раскладки сначала предупреждал."
L["Talents Panel"] = "Окно талантов"
L["The modern talents window. Turn off to use the standard Blizzard talent window."] = "Современное окно талантов. Выключите, чтобы использовать стандартное окно талантов Blizzard."
L["This loadout has fewer points in some talents than you've already spent, so it needs a respec first:\n"] = "В этом наборе в некоторых талантах меньше очков, чем вы уже потратили, поэтому сначала нужно сбросить таланты:\n"
L["Toggle slot name labels and the active-effects list."] = "Переключает подписи ячеек и список действующих эффектов."
L["Unlock Spec"] = "Разблокировать специализацию"
L["\n\nReset at a class trainer, then load again. (The rest has been staged — click Apply to learn it.)"] = "\n\nСбросьте таланты у учителя класса и загрузите снова. (Остальное подготовлено — нажмите «Применить», чтобы изучить.)"

-- ============================================================================
-- OPTIONS PANEL
-- ============================================================================

L["Adventure Guide (Encounter Journal)"] = "Путеводитель (журнал сражений)"
L["Auction House"] = "Аукцион"
L["Boss and loot browser. Requires a /reload to take effect (the micro button doesn't re-check this live)."] = "Обозреватель боссов и добычи. Требуется /reload (микрокнопка не перепроверяет это на лету)."
L["Click for this frame's settings."] = "Щёлкните для настроек этого окна."
L["Combined Bag"] = "Объединённая сумка"
L["Custom"] = "Своё значение"
L["Custom scale"] = "Свой масштаб"
L["Drag to move."] = "Перетащите, чтобы переместить."
L["Each window's size: \"Use UI scale\" follows the game's UI Scale slider, \"No scaling\" stays pixel-perfect, \"Custom\" uses its slider. The custom slider is greyed out and locked unless that window's mode is set to Custom."] = "Размер каждого окна: \"Масштаб интерфейса\" следует за игровым ползунком масштаба, \"Без масштабирования\" сохраняет попиксельную точность, \"Своё значение\" использует свой ползунок. Ползунок своего значения затенён и заблокирован, пока режим окна не переведён в «Своё значение»."
L["Guild"] = "Гильдия"
L["Looking For Group"] = "Поиск группы"
L["Looking For Group (Dungeon/Raid Finder)"] = "Поиск группы (подземелья и рейды)"
L["NewEra panels ported onto DragonUI. Toggle a panel below to enable or disable it. Panels appear here as their modules load."] = "Окна NewEra, перенесённые на DragonUI. Включайте и выключайте окна ниже. Окна появляются здесь по мере загрузки их модулей."
L["No scaling"] = "Без масштабирования"
L["Our all-in-one bag window. Turn OFF to use the stock Blizzard bags instead. Reload (/reload) to apply."] = "Наше окно сумок «всё в одном». ВЫКЛЮЧИТЕ, чтобы вместо него использовать стандартные сумки Blizzard. /reload для применения."
L["Professions"] = "Профессии"
L["Reload (/reload) to apply."] = "/reload для применения."
L["Scale mode"] = "Режим масштаба"
L["Scaling controls are unavailable: the 'core\\Scale.lua' file isn't loaded. Make sure your installed DragonUI_NewEra includes core/Scale.lua AND its line in the .toc, then /reload."] = "Настройки масштаба недоступны: файл 'core\\Scale.lua' не загружен. Убедитесь, что в вашей установке DragonUI_NewEra есть core/Scale.lua И строка для него в .toc, затем выполните /reload."
L["Scaling controls need a newer DragonUI options panel (AddSlider/AddDropdown)."] = "Настройкам масштаба требуется более новое окно настроек DragonUI (AddSlider/AddDropdown)."
L["Social"] = "Общение"
L["Social (Friends/Who/Guild/Chat/Raid)"] = "Общение (друзья/кто/гильдия/чат/рейд)"
L["Use DragonUI's window in place of the Blizzard default. Changes take effect after a /reload."] = "Использовать окно DragonUI вместо стандартного окна Blizzard. Изменения вступят в силу после /reload."
L["Use UI scale"] = "Масштаб интерфейса"
L["Window Scaling"] = "Масштабирование окон"
L["Windows"] = "Окна"

-- ============================================================================
-- SHARED UI
-- ============================================================================

L["Select All"] = "Выделить всё"

-- ============================================================================
-- BOSS TIMERS (modules/bossmods)
-- ============================================================================

L["Boss Timers"] = true
L["Boss Abilities"] = true
L["Boss Warnings"] = true
L["Boss Warning - Critical"] = true
L["Boss Warning - Medium"] = true
L["Boss Warning - Minor"] = true
L["Boss ability timers as a retail-style timeline or bar list. Reads its encounter data from DBM; without DBM installed there is nothing to show."] = true
L["Large on-screen warnings for important boss abilities. Needs DBM and the Boss Timers module."] = true
L["|cffff5555DBM is not installed.|r This module renders boss ability timers, it does not detect them — the encounter data comes from Deadly Boss Mods. Install DBM and reload to use it; the switches below are saved either way."] = true
L["Retail's boss ability timeline, drawn from |cffffcc55DBM's|r timers. Shows as a vertical rail of ability icons sliding toward now, or as a list of depleting bars. |cffffcc55Off by default.|r"] = true
L["|cffffcc55Everything else is on the frames themselves.|r Open |cffffcc55/dragonui edit|r, click a Boss Timers handle, and its own dialog carries the view, size, length, opacity, tooltips and the rest — each warning tier included, edited from the tier you clicked."] = true
L["Enable Boss Timers"] = true
L["The timeline and the three warning lines together. While it is on, DBM's own bars and warnings are hidden so the same timers are not drawn twice — its sounds and voice packs are left alone. Off by default. Reload (/reload) to apply."] = true
L["View"] = true
L["Timeline (rail)"] = true
L["Bars"] = true
L["Show the frame"] = true
L["Only while timers are running"] = true
L["Icon size"] = true
L["Rail length"] = true
L["Bar width"] = true
L["Space between bars"] = true
L["Show the countdown"] = true
L["Show the ability name"] = true
L["Timeline view only — the bar list always names its abilities."] = true
L["Show a test timer"] = true
L["Runs four sample timers and one warning through the same path a real DBM timer takes, so what you see is what an encounter will look like."] = true
L["Glow when an ability is imminent"] = true
L["On by default. The action-button proc glow, held for the last five seconds before an ability lands. It stands in for a retail effect this client cannot draw; with it off you get only the brief border flash, which is easy to miss."] = true
L["Revert Changes"] = true
L["Reset to Default"] = true
L["Timeline view only. How far out the rail reaches — the icons space themselves along it."] = true
L["Bars view only."] = true
L["Size"] = true
L["Scales the whole frame — the rail, the icons and the text together. Icon Size below scales only the icons."] = true
L["Background"] = true
L["The plate behind the frame. Retail ships it invisible."] = true
L["Scales the whole warning — text and both flanking icons together."] = true
L["The two spell icons either side of the text."] = true
L["Orientation"] = "Ориентация"
L["Vertical"] = "Вертикально"
L["Horizontal"] = "Горизонтально"
L["Icon direction"] = true
L["Down / Right"] = true
L["Up / Left"] = true
L["Tooltips"] = true
L["At the cursor"] = true
L["Beside the frame"] = true
L["Off"] = true
L["Flip horizontally"] = true
L["Timeline view only. Which way the rail runs; the icons travel along it either way."] = true
L["Timeline view only. Which end of the rail is |cffffcc55now|r — the end abilities travel toward and go off at."] = true
L["Bars view only. Mirrors each row — the icon moves to the right and the bar drains the other way."] = true
L["Hovering an ability shows its spell tooltip. DBM raises some timers that are not a spell at all — a pull timer, a phase change — and those show their own name instead."] = true
L["Show the ability icons"] = true
L["The two copies of the ability's own icon either side of the text — what retail draws. The text already names the ability, so this is decoration; turn it off for a plain line of text."] = true
