--[[
================================================================================
DragonUI_NewEra - Traditional Chinese Locale (zhTW)

Generated by tools/locale-lint/gen_locale.py from enUS.lua; edit the translation
map in tools/locale-lint/translations/zhTW.py and regenerate, or correct a
string here and port the fix back. Entries left as `= true` fall back to English.

Machine-drafted and unreviewed by a native speaker: corrections welcome. Every
entry is checked against its English key for placeholder parity
(check_keys.py --verify), so a %d or |n cannot go missing, but wording has not
been through a human pass.
================================================================================
]]

local L = LibStub("AceLocale-3.0"):NewLocale("DragonUI_NewEra", "zhTW")
if not L then return end
-- ============================================================================
-- ============================================================================
L["Alchemy"] = "鍊金術"
L["Blacksmithing"] = "鍛造"
L["Enchanting"] = "附魔"
L["Engineering"] = "工程學"
L["Herbalism"] = "草藥學"
L["Leatherworking"] = "製皮"
L["Mining"] = "採礦"
L["Smelting"] = "冶煉"
L["Skinning"] = "剝皮"
L["Tailoring"] = "裁縫"
L["Inscription"] = "銘文"
L["Jewelcrafting"] = "珠寶設計"
L["Prospecting"] = "探勘"
L["Cooking"] = "烹飪"
L["First Aid"] = "急救"
L["Fishing"] = "釣魚"
L["Select a recipe to craft"] = "選擇一個配方來製作"
L["Hide item tooltips in list"] = "在清單中隱藏物品提示"
L["Colour names by skill difficulty"] = "依技能難度為名稱上色"
L["Plain skill bar (no animation)"] = "簡潔技能條（無動畫）"
L["Create"] = "製造"
L["Create All"] = "全部製造"
L["Show Learned"] = "顯示已學會"
L["Has Skill Up"] = "可提升技能"
L["Have Materials"] = "擁有材料"

-- ============================================================================
-- AUCTION HOUSE
-- ============================================================================

L[" -- partial scan"] = " -- 部分掃描"
L["Auction query is throttled. Try again in a moment."] = "拍賣場查詢受到限制。請稍後再試。"
L["Buy out this auction for %s?"] = "以%s直接購買這件拍賣品？"
L["Choose search criteria and press \"Search\""] = "選擇搜尋條件並按下\"搜尋\""
L["Loading results..."] = "正在載入結果……"
L["Lvl"] = "等級"
L["Modern visual shell for Buy/Sell/Auctions with optional Auctionator tab embedding."] = "用於「購買/出售/拍賣」的現代介面，可選擇內嵌 Auctionator 頁籤。"
L["No listings."] = "沒有拍賣品。"
L["No results. Adjust filters and search again."] = "沒有結果。請調整篩選條件後重新搜尋。"
L["Page %d of %d  (items %d-%d of %d, from %d auction)%s"] = "第%d頁，共%d頁（物品%d-%d，共%d件，來自%d件拍賣）%s"
L["Page %d of %d  (items %d-%d of %d, from %d auctions)%s"] = "第%d頁，共%d頁（物品%d-%d，共%d件，來自%d件拍賣）%s"
L["Page 1 of 1"] = "第1頁，共1頁"
L["Per Item"] = "單價"
L["Place a bid of %s?"] = "出價%s？"
L["Scanning page %d of %d..."] = "正在掃描第%d頁，共%d頁……"
L["Searching..."] = "正在搜尋……"
L["Sort Per Item"] = "依單價排序"
L["You have no auctions."] = "你沒有拍賣品。"

-- ============================================================================
-- BAGS
-- ============================================================================

L["All Bags"] = "所有背包"
L["Auto-empty old bag when swapping"] = "更換背包時自動清空舊背包"
L["Auto-sell junk at merchants"] = "在商人處自動賣出垃圾物品"
L["Bag Options"] = "背包選項"
L["Category (smart)"] = "分類（智慧）"
L["Combined bag (all-in-one)"] = "合併背包（一體式）"
L["Item Level"] = "物品等級"
L["Keys"] = "鑰匙"
L["Merchant"] = "商人"
L["Name"] = "名稱"
L["Not enough free space to swap that bag."] = "空間不足，無法更換該背包。"
L["One movable window showing every bag slot in a Dragonflight-style grid. Takes over bag opening and replaces the per-window 'Retail bags' restyle. Reload (/reload) to apply."] = "一個可移動視窗，以巨龍崛起風格的格線顯示所有背包欄位。它會接管背包的開啟，並取代逐視窗的「正式服背包」重繪。需 /reload 生效。"
L["Quality"] = "品質"
L["Red-tint unusable items"] = "將無法使用的物品染成紅色"
L["Restyle the bag windows with the Dragonflight metal frame, portrait, and item quality borders. Disable to keep the stock Blizzard bags. Reload (/reload) to apply."] = "以巨龍崛起的金屬外框、頭像和物品品質邊框重繪背包視窗。關閉則保留暴雪原版背包。需 /reload 生效。"
L["Retail bags"] = "正式服背包"
L["Reverse sort order"] = "反轉排序順序"
L["Search"] = "搜尋"
L["Separate specialty bags"] = "單獨顯示專用背包"
L["Shift-right-click to stop watching"] = "Shift+右鍵點擊可停止關注"
L["Show item level on items"] = "在物品上顯示物品等級"
L["Show keyring row"] = "顯示鑰匙圈那一列"
L["Sold %d junk item(s)."] = "已賣出%d件垃圾物品。"
L["Sort Bags"] = "整理背包"
L["Sort by"] = "排序方式"
L["Sorting…"] = "正在整理……"
L["Swapping bag…"] = "正在更換背包……"
L["The same setting as Enable Item Level in DragonUI's options (Enhancements > Item Level). Covers the character panel and every other frame too."] = "與 DragonUI 選項中「啟用物品等級」（強化 > 物品等級）為同一項設定。同樣適用於角色面板和其他所有視窗。"
L["Turn on Item Level in DragonUI's options (Enhancements > Item Level) first."] = "請先在 DragonUI 選項中開啟「物品等級」（強化 > 物品等級）。"

-- ============================================================================
-- COOLDOWN MANAGER
-- ============================================================================

L["(empty)"] = "（空）"
L["(your spec)"] = "（你的專精）"
L["A ready sound plays when a COOLDOWN finishes.|nThis spell has none, so it can never play.|nClearing it also clears the badge."] = "就緒音效會在「冷卻」結束時播放。|n此法術沒有冷卻，因此音效永遠不會響起。|n清除它同時也會清除標記。"
L["A spell can be on cooldown and buffing you at the same time. The glow says which icons are buffed; the timer says how long."] = "一個法術可以同時處於冷卻中並為你提供增益。光效顯示哪些圖示帶有增益，計時器顯示還剩多久。"
L["Active"] = "生效中"
L["Alert"] = "提示"
L["Always"] = "永遠"
L["Auto-track buffs under %ds"] = "自動追蹤短於%d秒的增益"
L["Available"] = "可用"
L["Bar Content"] = "長條內容"
L["Bar Width"] = "長條寬度"
L["Both of these are immediate and cannot be undone from here — Revert only covers layout changes."] = "這兩項都會立即生效且無法在此復原——「還原」只涵蓋版面變更。"
L["Buff Bars"] = "增益長條"
L["Buff Icons"] = "增益圖示"
L["Buff tracking"] = "增益追蹤"
L["Buffed spells"] = "帶增益的法術"
L["Buffs you have not seen before are recorded and listed under Not Displayed on the Tracked Buffs tab, where you can assign the ones you want. Nothing appears on screen until you do."] = "你先前未見過的增益會被記錄，並列在「追蹤的增益」頁籤的「未顯示」中，你可以在那裡指派需要的增益。在此之前畫面上不會出現任何內容。"
L["Button Glow"] = "按鈕光效"
L["Clear All Alerts"] = "清除所有提示"
L["Clear Ready Sound"] = "清除就緒音效"
L["Clear all alerts and sounds"] = "清除所有提示和音效"
L["Clear every configured alert and ready sound?\n\nSpell lists and frame positions are not affected."] = "清除所有已設定的提示和就緒音效？\n\n法術清單和視窗位置不受影響。"
L["Closes edit mode and opens the Cooldown Manager window, which carries the settings that are not per-viewer: alerts, ready sounds, buff tracking, icon fit and the resets."] = "關閉編輯模式並開啟冷卻管理員視窗，其中包含不屬於單一顯示器的設定：提示、就緒音效、增益追蹤、圖示調整以及各項重設。"
L["Cooldown Manager"] = "冷卻管理員"
L["Cooldown Manager Settings"] = "冷卻管理員設定"
L["Cooldown Manager layout string (Ctrl+C to copy):"] = "冷卻管理員版面代碼（按 Ctrl+C 複製）："
L["Copy"] = "複製"
L["Defensives, interrupts, CC and escapes."] = "防禦、中斷、控場和脫身技能。"
L["Delete"] = "刪除"
L["Delete the layout \"%s\"?"] = "刪除版面\"%s\"？"
L["Drag onto Essential or Utility to track it."] = "拖曳到「核心」或「輔助」上即可追蹤。"
L["Draw the countdown number on each icon."] = "在每個圖示上顯示倒數數字。"
L["Each viewer's own settings — size, spacing, orientation, visibility, what its icons show — live on the frame, in edit mode, where you can see what you are changing. These open edit mode with that viewer selected and its settings already up. Closes this window; not available in combat."] = "每個顯示器自身的設定——大小、間距、方向、可見性、圖示顯示內容——都在框架上，位於編輯模式中，你可以直接看到自己在改什麼。這些按鈕會開啟編輯模式並選取該顯示器，同時展開它的設定。會關閉本視窗；戰鬥中無法使用。"
L["Enable Cooldown Manager"] = "啟用冷卻管理員"
L["Enabled"] = "已啟用"
L["Essential Cooldowns"] = "核心冷卻"
L["Everything"] = "全部"
L["Everything (no spec)"] = "全部（不分專精）"
L["Everything the Cooldown Manager can be told to do that is not about one viewer's layout. Layout and position both live on the frame itself, in edit mode (/dui edit) — click a viewer there for its own settings, or use the buttons just below to go straight to one."] = "冷卻管理員所有與單一顯示器版面無關的功能。版面和位置都在框架本身，位於編輯模式（/dui edit）中——在那裡點擊某個顯示器可查看它自己的設定，或使用下方的按鈕直接前往。"
L["Export Layout"] = "匯出版面"
L["FX Style"] = "特效樣式"
L["Flashes once, the moment the cooldown finishes.|nWorks for every spell."] = "冷卻結束的瞬間閃爍一次。|n適用於所有法術。"
L["Frame strength"] = "外框強度"
L["Gap between icons. Retail offsets this by -4, so the low end overlaps slightly — that is the stock look, not a bug."] = "圖示之間的間距。正式服會將該值偏移 -4，因此在低值時會略微重疊——這是原版效果，並非錯誤。"
L["Glow while buffed"] = "有增益時發光"
L["Glows during the last %d%% of this buff's|nremaining time."] = "在該增益剩餘時間的|n最後%d%%內發光。"
L["Glows during the last %d%% of this spell's own|nbuff or debuff."] = "在該法術自身增益或減益剩餘時間的|n最後%d%%內發光。"
L["Glows for as long as the spell is off cooldown|nand affordable."] = "只要該法術已冷卻完畢|n且資源足夠，就持續發光。"
L["Glows for as long as this buff is on you.|n|nThe one that works for a proc: it asks whether the|nbuff is up, not whether something is castable|nor off cooldown."] = "只要該增益在你身上，就持續發光。|n|n適用於觸發效果：它判斷的是|n增益是否存在，而不是某個技能是否可施放|n或是否已冷卻完畢。"
L["Glows for as long as this spell's effect is|nup on %s."] = "只要該法術的效果在%s身上，|n就持續發光。"
L["Halo the icon gold while the spell's buff (or, for a shaman, its totem) is up."] = "當該法術的增益（薩滿則為其圖騰）存在時，為圖示加上金色光環。"
L["Hidden"] = "隱藏"
L["Hide When Inactive"] = "未生效時隱藏"
L["Horizontal"] = "水平"
L["How many icons before the layout wraps. Vertical orientation reads this as icons per column."] = "版面換行前的圖示數量。在垂直方向下，此值代表每欄的圖示數。"
L["Icon Direction"] = "圖示方向"
L["Icon Limit"] = "圖示上限"
L["Icon Only"] = "僅圖示"
L["Icon Padding"] = "圖示間距"
L["Icon Size"] = "圖示大小"
L["Icon and Name"] = "圖示和名稱"
L["Icon fit"] = "圖示調整"
L["Icon inset"] = "圖示內縮"
L["Import"] = "匯入"
L["Import Layout"] = "匯入版面"
L["In Combat"] = "戰鬥中"
L["Lasts %s sec"] = "持續%s秒"
L["Layouts"] = "版面"
L["Layouts include appearance"] = "版面包含外觀設定"
L["Left"] = "向左"
L["Load the %s starter layout?\n\nEssential is set to that spec's spells. Everything else for your class moves to Not Displayed — nothing is deleted, and you can drag any of it back.\n\nTracked auras, trinkets, alerts and frame positions are not affected."] = "載入%s的初始版面？\n\n「核心」將設為該專精的法術。你職業的其餘內容會移至「未顯示」——不會刪除任何東西，你可以隨時把它們拖回來。\n\n追蹤的光環、飾品、提示和視窗位置不受影響。"
L["Marching Ants"] = "流動虛線"
L["Move to %s"] = "移動到%s"
L["Name Only"] = "僅名稱"
L["Name this layout:"] = "為此版面命名："
L["New Layout"] = "新增版面"
L["None"] = "無"
L["Not displayed on any viewer"] = "未在任何顯示器上顯示"
L["Not yet learned"] = "尚未學會"
L["Nothing to undo. It covers LAYOUTS, not the settings|non these tabs — a viewer's own size and position revert|nfrom its edit-mode panel instead."] = "沒有可復原的內容。它涵蓋的是「版面」，而非這些頁籤|n中的設定——顯示器自身的大小和位置需從它的|n編輯模式面板還原。"
L["Off by default. Turn on to show the four viewers; turn off to hide them again. Takes effect immediately either way, and nothing is forgotten — this switch stores one flag and touches nothing else, so your setup comes back exactly as you left it."] = "預設關閉。開啟可顯示四個顯示器，關閉則再次隱藏它們。兩個方向都會立即生效，且不會遺失任何內容——這個開關只儲存一個標記，不更動其他任何東西，因此你的設定會原樣恢復。"
L["Off, both specs share one set of lists. Turning it on copies the layout you have now into the spec you are in."] = "關閉時，兩個專精共用同一組清單。開啟後會把你目前的版面複製到你所在的專精中。"
L["Off, loading or importing a layout changes only what you track — lists, tracked buffs, trinkets, alerts and sounds. On, it also applies the orientation, icons per row, size, padding and opacity the layout was saved with.|n|nLayouts always SAVE appearance either way, so this only decides what happens when one is applied. Revert always puts appearance back, whatever this says."] = "關閉時，載入或匯入版面只會改變你追蹤的內容——清單、追蹤的增益、飾品、提示和音效。開啟後，還會套用該版面儲存時的方向、每列圖示數、大小、間距和不透明度。|n|n無論如何，版面一律會「儲存」外觀，因此此項只決定套用版面時的行為。無論此項如何設定，「還原」一律會恢復外觀。"
L["Off, orientation, icons per row, size, padding and opacity are one setup for every character. On, each character can differ — until you change something here it still follows the shared setup, so nothing moves when you tick this, and unticking it gives the shared setup back without losing what you changed."] = "關閉時，方向、每列圖示數、大小、間距和不透明度對所有角色共用一組設定。開啟後，每個角色都可以不同——在你於此處做出變更之前，它仍沿用共用設定，因此勾選時不會有任何位移；取消勾選則會恢復共用設定，同時不會遺失你變更過的內容。"
L["Offensive burst and damage cooldowns."] = "進攻性爆發和傷害類冷卻技能。"
L["Opacity"] = "不透明度"
L["Open Cooldown Manager"] = "開啟冷卻管理員"
L["Opens a share string you can copy with Ctrl+C.|nIt covers this class's spell lists, tracked auras,|ntrinket placement, alerts and sounds."] = "開啟一段可用 Ctrl+C 複製的分享代碼。|n其中包含該職業的法術清單、追蹤的光環、|n飾品位置、提示和音效。"
L["Opens the Cooldown Manager window (/cdm) on its Spells tab. Needs the module on — the window configures the viewers, so it goes away with them."] = "在「法術」頁籤開啟冷卻管理員視窗（/cdm）。需要啟用該模組——此視窗用於設定顯示器，因此會隨它們一同消失。"
L["Options"] = "選項"
L["Orientation"] = "方向"
L["Pandemic Border"] = "重施外框"
L["Paste a Cooldown Manager layout string:"] = "貼上一段冷卻管理員版面代碼："
L["Ready Sound"] = "就緒音效"
L["Ready sound: %s"] = "就緒音效：%s"
L["Refresh"] = "更新"
L["Refresh Window"] = "更新時限"
L["Remove"] = "移除"
L["Remove every per-spell alert and ready sound. Spell lists and positions are not affected."] = "移除所有針對單一法術的提示和就緒音效。法術清單和位置不受影響。"
L["Rename"] = "重新命名"
L["Requires the %s talent"] = "需要天賦「%s」"
L["Reset"] = "重設"
L["Reset %s to its default layout?\n\nThis viewer's position, size, orientation and visibility all go back to stock. Nothing else is affected, and it cannot be undone."] = "將%s重設為預設版面？\n\n該顯示器的位置、大小、方向和可見性都會恢復原樣。其他內容不受影響，且此操作無法復原。"
L["Reset Spell Lists"] = "重設法術清單"
L["Reset spell and buff lists"] = "重設法術和增益清單"
L["Reset this class's Cooldown Manager spell and buff lists to their defaults?\n\nOther classes, alerts, sounds and frame positions are not affected."] = "將該職業的冷卻管理員法術和增益清單重設為預設值？\n\n其他職業、提示、音效和視窗位置不受影響。"
L["Reset to the starter layout?\n\nThis reverts every Cooldown Manager edit — spells, tracked auras, trinket placement, alerts and sounds — to their defaults, and clears your saved-layout selection.\n\nFrame positions are not affected."] = "重設為初始版面？\n\n這會將冷卻管理員的所有變更——法術、追蹤的光環、飾品位置、提示和音效——恢復為預設值，並清除你已儲存的版面選擇。\n\n視窗位置不受影響。"
L["Restore the curated defaults and the auto-track window for THIS CLASS, clearing its spell lists, aura assignments and trinket placement. Other classes, alerts, sounds and positions are not affected."] = "恢復「目前職業」的精選預設值和自動追蹤時限，並清除其法術清單、光環指派和飾品位置。其他職業、提示、音效和位置不受影響。"
L["Retail's Cooldown Manager, driven from curated per-class cooldown lists. |cffffcc55Off by default|r — it adds four viewers to the middle of your screen, so it waits to be asked. Every setting — which spells and buffs are tracked, each viewer's layout, size and visibility, alerts and ready sounds — lives in the Cooldown Manager window itself (/cdm). Drag the viewers with DragonUI's editor mode to reposition them, and right-click one there for its own layout settings."] = "正式服的冷卻管理員，由各職業精選的冷卻清單驅動。|cffffcc55預設關閉|r——它會在你的畫面中央加入四個顯示器，因此需要你主動開啟。所有設定——追蹤哪些法術和增益、每個顯示器的版面、大小和可見性、提示和就緒音效——都在冷卻管理員視窗內（/cdm）。用 DragonUI 的編輯模式拖曳顯示器以調整位置，並在那裡按右鍵點擊某個顯示器以查看它自己的版面設定。"
L["Retail's behaviour: while buffed, the icon counts down the BUFF. Off, it counts down the spell's cooldown and the glow alone marks it as buffed — which is clearer when the two differ, as on Prayer of Mending."] = "正式服的行為：有增益時，圖示倒數的是「增益」。關閉後，它倒數的是法術冷卻，僅以光效標示有增益——當兩者不一致時（例如「癒合禱言」）這樣更清楚。"
L["Revert"] = "還原"
L["Right"] = "向右"
L["Save, load, import and export the whole|nCooldown Manager setup for this class."] = "儲存、載入、匯入和匯出該職業|n整套冷卻管理員設定。"
L["Separate appearance per character"] = "每個角色使用獨立外觀"
L["Separate layout per spec"] = "每個專精使用獨立版面"
L["Short-duration buffs and procs, as depleting bars."] = "短時增益和觸發效果，以遞減長條顯示。"
L["Short-duration buffs and procs, as icons."] = "短時增益和觸發效果，以圖示顯示。"
L["Show Timer"] = "顯示計時器"
L["Show Tooltips"] = "顯示滑鼠提示"
L["Show Unlearned"] = "顯示未學會的"
L["Show a slot only while its aura is active."] = "僅在光環生效時顯示對應欄位。"
L["Show a tooltip when hovering an icon."] = "滑鼠移到圖示上時顯示提示。"
L["Show every short buff the moment it lands, without assigning it first. Convenient on a character you are still setting up; in a raid it fills the viewers with other people's cooldowns, food and flasks."] = "在每個短時增益生效的瞬間就顯示它，無需事先指派。對仍在設定中的角色很方便；但在團隊副本中，這會讓顯示器塞滿他人的冷卻技能、食物和精煉藥劑。"
L["Show the buff's time, not the cooldown"] = "顯示增益時間，而非冷卻時間"
L["Show them as"] = "顯示為"
L["Show this viewer at all. The editor handle stays either way, so this is reversible from right here."] = "是否顯示該顯示器。無論如何編輯把手都會保留，因此可以直接在此復原。"
L["Sparkles"] = "閃光"
L["Talent specs"] = "天賦專精"
L["The frame is a soft shadow that falls on the icon's outer edge, so it only shows where there is icon underneath it. Strength draws it more than once to deepen it — that is also what makes its rounded corners read, since the icons themselves cannot be rounded here. Inset shrinks the icon, which slides the shadow off it, so raise that one sparingly."] = "外框是落在圖示外緣的柔和陰影，因此只在其下方有圖示的地方顯示。強度會多次繪製它以加深效果——這也是它的圓角能被看出來的原因，因為此處圖示本身無法做成圓角。內縮會縮小圖示，使陰影滑出圖示，所以請謹慎提高該值。"
L["The full curated list for your class, both specs' spells|nincluded. This is what the Cooldown Manager shipped with|nbefore per-spec starters."] = "你職業的完整精選清單，包含兩個專精的法術。|n這是冷卻管理員在推出各專精初始版面之前|n所附帶的內容。"
L["Tracked automatically. Drag it into a section to pin it there."] = "已自動追蹤。將它拖入某個區段即可固定在那裡。"
L["Undoes the last layout change — applying a layout,|nimporting one, or the starter reset.|n|nOne step, and only for this session."] = "復原上一次版面變更——套用版面、|n匯入版面或重設為初始版面。|n|n只能復原一步，且僅在本次登入期間有效。"
L["Usable"] = "可施放"
L["Use Starter Layout"] = "使用初始版面"
L["Utility Cooldowns"] = "輔助冷卻"
L["Vertical"] = "垂直"
L["Viewer layout"] = "顯示器版面"
L["Visibility"] = "可見性"
L["When this viewer is on screen at all. Hidden still leaves the editor handle here."] = "該顯示器何時出現在畫面上。選擇「隱藏」仍會在此保留編輯把手。"
L["Which of the two buff viewers auto-tracked buffs land in."] = "自動追蹤的增益會進入兩個增益顯示器中的哪一個。"
L["Which spells and buffs you track is remembered separately for each talent spec, so a Discipline layout and a Holy one do not overwrite each other. Where each viewer sits is always remembered per character; the appearance settings are shared unless you say otherwise below."] = "你追蹤的法術和增益會依天賦專精分別記錄，因此戒律版面與神聖版面不會互相覆蓋。每個顯示器的位置一律依角色記錄；除非你在下方另行設定，否則外觀設定為共用。"
L["is turned off. Enable it in DragonUI's options, under New Era > Cooldown Manager."] = "已關閉。請在 DragonUI 選項的 New Era > 冷卻管理員中啟用它。"
L["you"] = "你"
L["|n|nOn a buff row this is about RE-CASTING it,|nnot about the buff being up — that is Active."] = "|n|n在增益列中，這指的是「重新施放」，|n而不是增益是否存在——那是「生效中」。"
L["|n|nThe one for a DoT or a shield: it asks whether|nthe aura is up, not whether the cooldown is ready."] = "|n|n適用於持續傷害或護盾：它判斷的是|n光環是否存在，而不是冷卻是否就緒。"
L["|n|nThis one also waits for a target below %d%% health."] = "|n|n此項還會等待生命值低於%d%%的目標。"
L["|n|n|cff40ff40Applies %s to %s, so this will work.|r"] = "|n|n|cff40ff40會對%s施加%s，因此這會生效。|r"
L["|n|n|cff40ff40Its aura is active now, so this will work.|r"] = "|n|n|cff40ff40它的光環目前處於生效狀態，因此這會生效。|r"
L["|n|n|cffffd200No aura of this name is up right now.|r"] = "|n|n|cffffd200目前沒有該名稱的光環生效。|r"

-- ============================================================================
-- ADVENTURE GUIDE
-- ============================================================================

L["(No abilities recorded for this encounter.)"] = "（該首領戰沒有記錄任何技能。）"
L["(no model)"] = "（無模型）"
L["Adventure Guide"] = "冒險指南"
L["Eastern Kingdoms"] = "東部王國"
L["Kalimdor"] = "卡林多"
L["Model will load once seen within this session due to client limitations."] = "受客戶端限制，模型需在本次登入中出現過一次後才會載入。"
L["Phase %d"] = "第%d階段"
L["The Adventure Guide: bosses, abilities, and loot for Classic and Burning Crusade dungeons and raids (/aguide)."] = "冒險指南：經典版和燃燒的遠征地城與團隊副本的首領、技能和戰利品（/aguide）。"

-- ============================================================================
-- GUILD
-- ============================================================================

L["GuildControlPopupFrame is missing on this client."] = "此客戶端缺少 GuildControlPopupFrame。"
L["Modern Communities-style guild window (Roster / Info / Chat)."] = "現代社群風格的公會視窗（成員 / 資訊 / 聊天）。"
L["Promote"] = "晉升"

-- ============================================================================
-- LEVEL UP DISPLAY
-- ============================================================================

L["Battleground available"] = "可進入新戰場"
L["Can be learned from a trainer"] = "可向訓練師學習"
L["Dungeon available"] = "可進入新地城"
L["Enable Level Up Display"] = "啟用升級提示"
L["Level Up Display"] = "升級提示"
L["New Feature"] = "新功能"
L["New Riding Skill"] = "新的騎術"
L["New Talent Point"] = "新的天賦點數"
L["New Talent Points"] = "新的天賦點數"
L["New rank available"] = "可取得新軍階"
L["On by default. Turn off to stop the banner appearing on level-up; the harvest keeps running either way, so turning it back on costs nothing."] = "預設開啟。關閉後升級時不再顯示橫幅；無論如何資料蒐集都會繼續執行，因此重新開啟不會有任何代價。"
L["Play the level-up sound"] = "播放升級音效"
L["Raid available"] = "可進入新團隊副本"
L["Retail's level-up banner. What it announces is read from |cffffcc55this server|r — abilities and their levels come from your class trainer's own list, battlegrounds and dungeons from the client's brackets. Visit a trainer once to fill it in; |cffffcc55/nelevelup coverage|r shows what it knows."] = "正式服的升級橫幅。它所公布的內容讀取自|cffffcc55目前伺服器|r——技能及其等級來自你職業訓練師自己的清單，戰場和地城則來自客戶端的等級區間。去訓練師那裡走一趟即可填入資料；|cffffcc55/nelevelup coverage|r 可查看它已知的內容。"
L["Talents"] = "天賦"
L["You have reached"] = "你已達到"
L["level %d"] = "%d級"
L["|cffffcc55Off by default.|r The game already plays its own fanfare when you level, so this only adds a second copy on top of it. Turn it on if you want /nelevelup previews to make a sound, since those fire no game sound of their own."] = "|cffffcc55預設關閉。|r升級時遊戲本身已會播放自己的號角聲，因此此項只會在其上疊加第二次。如果你希望 /nelevelup 的預覽帶有音效，可以開啟它，因為預覽本身不會觸發任何遊戲音效。"

-- ============================================================================
-- PROFESSIONS
-- ============================================================================

L["Auctionator API not available for reagent scans."] = "Auctionator 介面無法使用，無法掃描材料。"
L["Auctionator scan started for recipe reagents."] = "已開始使用 Auctionator 掃描配方材料。"
L["Open the Auction House first to run Auctionator scans."] = "請先開啟拍賣場才能執行 Auctionator 掃描。"
L["Requires the Auction House window to be open."] = "需要開啟拍賣場視窗。"
L["Requires: %s"] = "需要：%s"
L["Retail-style crafting window for all professions."] = "適用於所有專業的正式服風格製作視窗。"
L["Scan AH"] = "掃描拍賣場"
L["Searches Auctionator for the selected recipe and its reagents."] = "在 Auctionator 中搜尋所選配方及其材料。"

-- ============================================================================
-- SOCIAL
-- ============================================================================

L["Away"] = "暫離"
L["Busy"] = "忙碌"
L["Cancel Extend"] = "取消延長"
L["Enter a note for %s:"] = "為%s輸入備註："
L["Extend"] = "延長"
L["Extended"] = "已延長"
L["ID: %s"] = "ID：%s"
L["Instance"] = "副本"
L["Modern friends window (Friends / Ignore / Who) with a Guild tab."] = "現代好友視窗（好友 / 忽略 / 誰），並附有公會頁籤。"
L["Promote to Assistant"] = "晉升為助理"
L["Promote to Raid Leader"] = "晉升為團隊隊長"
L["Resets In"] = "重置於"
L["Set Note"] = "設定備註"
L["You are not saved to any instances."] = "你沒有綁定任何副本。"

-- ============================================================================
-- SPELLBOOK
-- ============================================================================

L["Spellbook"] = "法術書"
L["The modern Dragonflight spellbook window. Disable to keep the stock Blizzard spellbook."] = "現代巨龍崛起風格的法術書視窗。關閉則保留暴雪原版法術書。"

-- ============================================================================
-- TALENTS
-- ============================================================================

L["  %s: have %d, build wants %d"] = "  %s：現有%d點，設定需要%d點"
L["%s\n\nImport anyway?"] = "%s\n\n仍要匯入？"
L["ACTIVE EFFECTS"] = "生效中的效果"
L["Activate"] = "啟用"
L["Copy this build string (Ctrl+C). Talented & the WoWhead/wotlkdb calculators import it too:"] = "複製這段設定代碼（Ctrl+C）。Talented 以及 WoWhead/wotlkdb 計算機也可匯入："
L["Delete loadout '%s'?"] = "刪除設定「%s」？"
L["GLYPHS"] = "雕紋"
L["Glyph options"] = "雕紋選項"
L["Glyphs"] = "雕紋"
L["Import…"] = "匯入…"
L["Loadouts"] = "設定組"
L["Locked"] = "已鎖定"
L["MAJOR GLYPHS"] = "主要雕紋"
L["MINOR GLYPHS"] = "次要雕紋"
L["NO ACTIVE EFFECTS"] = "沒有生效中的效果"
L["Name this imported loadout:"] = "為匯入的設定組命名："
L["Name this loadout (saves your current spec):"] = "為此設定組命名（儲存你目前的專精）："
L["Paste a talent string or calculator URL (Talented / WoWhead / wotlkdb):"] = "貼上天賦代碼或計算機網址（Talented / WoWhead / wotlkdb）："
L["Pet"] = "寵物"
L["Remove this glyph?"] = "移除該雕紋？"
L["Rename loadout:"] = "重新命名設定組："
L["Rename specialization"] = "重新命名專精"
L["Rename this specialization (letters only, max %d):"] = "重新命名該專精（僅限字母，最多%d個字元）："
L["Save current spec…"] = "儲存目前專精…"
L["Server uses custom talents"] = "伺服器使用了自訂天賦"
L["Show glyph effects"] = "顯示雕紋效果"
L["Show glyph names"] = "顯示雕紋名稱"
L["Tags exported builds with this realm so imports onto other layouts warn first."] = "為匯出的設定標記此伺服器，以便匯入到其他版面時先行提示。"
L["Talents Panel"] = "天賦面板"
L["The modern talents window. Turn off to use the standard Blizzard talent window."] = "現代天賦視窗。關閉則使用暴雪標準天賦視窗。"
L["This loadout has fewer points in some talents than you've already spent, so it needs a respec first:\n"] = "該設定組在某些天賦上的點數少於你已投入的點數，因此需要先重置天賦：\n"
L["Toggle slot name labels and the active-effects list."] = "切換欄位名稱標籤和生效效果清單。"
L["Unlock Spec"] = "解鎖專精"
L["\n\nReset at a class trainer, then load again. (The rest has been staged — click Apply to learn it.)"] = "\n\n請到職業訓練師處重置天賦，然後重新載入。（其餘部分已準備就緒——點擊「套用」即可學習。）"

-- ============================================================================
-- OPTIONS PANEL
-- ============================================================================

L["Adventure Guide (Encounter Journal)"] = "冒險指南（首領戰日誌）"
L["Auction House"] = "拍賣場"
L["Boss and loot browser. Requires a /reload to take effect (the micro button doesn't re-check this live)."] = "首領與戰利品瀏覽器。需 /reload 才會生效（微型按鈕不會即時重新檢查此項）。"
L["Click for this frame's settings."] = "點擊可查看該視窗的設定。"
L["Combined Bag"] = "合併背包"
L["Custom"] = "自訂"
L["Custom scale"] = "自訂縮放"
L["Drag to move."] = "拖曳以移動。"
L["Each window's size: \"Use UI scale\" follows the game's UI Scale slider, \"No scaling\" stays pixel-perfect, \"Custom\" uses its slider. The custom slider is greyed out and locked unless that window's mode is set to Custom."] = "每個視窗的大小：\"使用介面縮放\"會跟隨遊戲的介面縮放滑桿，\"不縮放\"維持像素精確，\"自訂\"使用它自己的滑桿。除非該視窗的模式設為「自訂」，否則自訂滑桿會變灰並鎖定。"
L["Guild"] = "公會"
L["Looking For Group"] = "尋找隊伍"
L["Looking For Group (Dungeon/Raid Finder)"] = "尋找隊伍（地城/團隊副本搜尋器）"
L["NewEra panels ported onto DragonUI. Toggle a panel below to enable or disable it. Panels appear here as their modules load."] = "移植到 DragonUI 上的 NewEra 面板。在下方開啟或關閉某個面板。面板會隨其模組載入而出現在這裡。"
L["No scaling"] = "不縮放"
L["Our all-in-one bag window. Turn OFF to use the stock Blizzard bags instead. Reload (/reload) to apply."] = "我們的一體式背包視窗。關閉後將改用暴雪原版背包。需 /reload 生效。"
L["Professions"] = "專業技能"
L["Reload (/reload) to apply."] = "需 /reload 生效。"
L["Scale mode"] = "縮放模式"
L["Scaling controls are unavailable: the 'core\\Scale.lua' file isn't loaded. Make sure your installed DragonUI_NewEra includes core/Scale.lua AND its line in the .toc, then /reload."] = "縮放選項無法使用：檔案 'core\\Scale.lua' 未載入。請確認你安裝的 DragonUI_NewEra 同時包含 core/Scale.lua 以及它在 .toc 中的對應行，然後執行 /reload。"
L["Scaling controls need a newer DragonUI options panel (AddSlider/AddDropdown)."] = "縮放選項需要較新版本的 DragonUI 選項面板（AddSlider/AddDropdown）。"
L["Social"] = "社交"
L["Social (Friends/Who/Guild/Chat/Raid)"] = "社交（好友/誰/公會/聊天/團隊）"
L["Use DragonUI's window in place of the Blizzard default. Changes take effect after a /reload."] = "使用 DragonUI 的視窗取代暴雪預設視窗。變更會在 /reload 後生效。"
L["Use UI scale"] = "使用介面縮放"
L["Window Scaling"] = "視窗縮放"
L["Windows"] = "視窗"

-- ============================================================================
-- SHARED UI
-- ============================================================================

L["Select All"] = "全選"

-- ============================================================================
-- BOSS TIMERS (modules/bossmods)
-- ============================================================================

L["Boss Timers"] = true
L["Boss Abilities"] = true
L["Boss Warnings"] = true
L["Boss Warning - Critical"] = true
L["Boss Warning - Medium"] = true
L["Boss Warning - Minor"] = true
L["Boss ability timers as a retail-style timeline or bar list. Reads its encounter data from DBM; without DBM installed there is nothing to show."] = true
L["Large on-screen warnings for important boss abilities. Needs DBM and the Boss Timers module."] = true
L["|cffff5555DBM is not installed.|r This module renders boss ability timers, it does not detect them — the encounter data comes from Deadly Boss Mods. Install DBM and reload to use it; the switches below are saved either way."] = true
L["Retail's boss ability timeline, drawn from |cffffcc55DBM's|r timers. Shows as a vertical rail of ability icons sliding toward now, or as a list of depleting bars. |cffffcc55Off by default.|r"] = true
L["|cffffcc55Everything else is on the frames themselves.|r Open |cffffcc55/dragonui edit|r, click a Boss Timers handle, and its own dialog carries the view, size, length, opacity, tooltips and the rest — each warning tier included, edited from the tier you clicked."] = true
L["Enable Boss Timers"] = true
L["The timeline and the three warning lines together. While it is on, DBM's own bars and warnings are hidden so the same timers are not drawn twice — its sounds and voice packs are left alone. Off by default. Reload (/reload) to apply."] = true
L["View"] = true
L["Timeline (rail)"] = true
L["Bars"] = true
L["Show the frame"] = true
L["Only while timers are running"] = true
L["Icon size"] = true
L["Rail length"] = true
L["Bar width"] = true
L["Space between bars"] = true
L["Show the countdown"] = true
L["Show the ability name"] = true
L["Timeline view only — the bar list always names its abilities."] = true
L["Show a test timer"] = true
L["Runs four sample timers and one warning through the same path a real DBM timer takes, so what you see is what an encounter will look like."] = true
L["Glow when an ability is imminent"] = true
L["On by default. The action-button proc glow, held for the last five seconds before an ability lands. It stands in for a retail effect this client cannot draw; with it off you get only the brief border flash, which is easy to miss."] = true
L["Revert Changes"] = true
L["Reset to Default"] = true
L["Timeline view only. How far out the rail reaches — the icons space themselves along it."] = true
L["Bars view only."] = true
L["Size"] = true
L["Scales the whole frame — the rail, the icons and the text together. Icon Size below scales only the icons."] = true
L["Background"] = true
L["The plate behind the frame. Retail ships it invisible."] = true
L["Scales the whole warning — text and both flanking icons together."] = true
L["The two spell icons either side of the text."] = true
L["Orientation"] = "方向"
L["Vertical"] = "垂直"
L["Horizontal"] = "水平"
L["Icon direction"] = true
L["Down / Right"] = true
L["Up / Left"] = true
L["Tooltips"] = true
L["At the cursor"] = true
L["Beside the frame"] = true
L["Off"] = true
L["Flip horizontally"] = true
L["Timeline view only. Which way the rail runs; the icons travel along it either way."] = true
L["Timeline view only. Which end of the rail is |cffffcc55now|r — the end abilities travel toward and go off at."] = true
L["Bars view only. Mirrors each row — the icon moves to the right and the bar drains the other way."] = true
L["Hovering an ability shows its spell tooltip. DBM raises some timers that are not a spell at all — a pull timer, a phase change — and those show their own name instead."] = true
L["Show the ability icons"] = true
L["The two copies of the ability's own icon either side of the text — what retail draws. The text already names the ability, so this is decoration; turn it off for a plain line of text."] = true
