-- DOWNPORT: copied from NewEra (see ReferenceAddons); namespace localized to DragonUI_NewEra,
-- art paths re-pointed at DragonUI_NewEra\Textures\EncounterJournal. Content unchanged.
local NE = DragonUI_NewEra
-- Addon/EncounterJournal/AbilitiesEra.lua — hand-seeded VANILLA (Era 1.15) boss ability
-- sections for the instances retail's modern Encounter Journal never authored for the
-- Classic tier (every empty-section boss in Data.lua). Merged into NE.ej.DATA at load by
-- encounter id WITHOUT editing the auto-generated Data.lua — same overlay mechanism as
-- PortraitOverrides.lua, so it survives a Data.lua re-gen. Must load AFTER Data.lua.
--
-- Why this exists (and why NOT from retail DB2): nearly every classic dungeon/raid that
-- lacks sections was REVAMPED in Cataclysm/MoP, so retail's modern EJ describes a different
-- roster (e.g. modern Shadowfang Keep = Ashbury/Godfrey/Walden, not Rethilgore/Arugal). The
-- raids (MC/BWL/AQ/Naxx/Onyxia) have no modern sections at all. Era versioning therefore
-- requires the VANILLA ability set, sourced from the live 1.15 data:
--   * which spells each boss casts  -> cmangos EventAI (creature_ai_scripts) / boss scripts
--   * each spell's school/dispel/mechanic/cast -> cmangos spell_template (== the 1.15 DBC)
--   * resolved tooltip values/durations -> Classic-Era Wowhead spell pages
-- Flag badges are DERIVED, not guessed: Magic(128)=dispel Magic, Curse(256)=dispel Curse,
-- Poison(512)=dispel Poison, Disease(1024)=dispel Disease, Enrage(2048)=self damage frenzy,
-- Interrupt(64)=has a real cast time and is silence-preventable, Healer(4)=heal, Tank(1),
-- Important(32)=summons/major mechanic. (Bit order per EncounterPage FLAG_ATLAS.)
--
-- Schema per entry: ABIL[encounterID] = { {title=, body=, flags=, spell=}, ... } — a flat
-- sibling list (top-level abilities). `spell` is the real vanilla spellID; the renderer
-- resolves its icon via GetSpellTexture at runtime (no baked FDID). Section ids are
-- synthesised as encID*1000 + index, unique within the boss.

NE.ej = NE.ej or {}

local ABIL = {
  -- Shadowfang Keep (instance 64) — vanilla roster
  -- Rethilgore
  [3914] = {
    { title = "Soul Drain", flags = 192, spell = 7295,
      body = "Rethilgore drains the soul from his current target, sapping their life and rooting them in place for 10 sec." },
  },
  -- Razorclaw the Butcher
  [3886] = {
    { title = "Butcher Drain", flags = 0, spell = 7486,
      body = "Razorclaw butchers his foes with savage strokes, draining their vitality to heal himself for a portion of the damage he deals." },
  },
  -- Baron Silverlaine
  [3887] = {
    { title = "Veil of Shadow", flags = 320, spell = 7068,
      body = "Baron Silverlaine shrouds a player in a veil of shadow, reducing all healing they receive by 75% for 15 sec." },
  },
  -- Commander Springvale
  [4278] = {
    { title = "Holy Light", flags = 68, spell = 1026,
      body = "Commander Springvale channels the Light to heal himself or a wounded ally for a large amount." },
    { title = "Hammer of Justice", flags = 128, spell = 5588,
      body = "Commander Springvale hammers his current target with the weight of justice, stunning them for 4 sec." },
  },
  -- Odo the Blindwatcher
  [4279] = {
    { title = "Howling Rage", flags = 2048, spell = 7481,
      body = "As Odo is wounded — at 75%, 50%, and 25% health — he flies into a howling rage, growing in size and increasing the damage he deals. The frenzy intensifies at each threshold." },
  },
  -- Fenrus the Devourer
  [4274] = {
    { title = "Toxic Saliva", flags = 512, spell = 7125,
      body = "Fenrus coats a player in toxic saliva, inflicting Nature damage every 6 sec for 2 min." },
  },
  -- Wolf Master Nandos
  [3927] = {
    { title = "Call of the Pack", flags = 32, spell = 7487,
      body = "Wolf Master Nandos summons his pack to his aid, calling forth Bleak Worgs, Slavering Worgs, and finally a Lupine Horror to overwhelm intruders." },
  },
  -- Archmage Arugal
  [4275] = {
    { title = "Void Bolt", flags = 64, spell = 7588,
      body = "Arugal hurls a bolt of void energy at his target, inflicting heavy Shadow damage." },
    { title = "Arugal's Curse", flags = 256, spell = 7621,
      body = "Arugal curses a player, transforming them into a Shadowfang Glutton under his control for 10 sec." },
    { title = "Thundershock", flags = 32, spell = 7803,
      body = "Arugal unleashes a shock of nature energy around himself, inflicting Nature damage, knocking back nearby players, and stunning them for 5 sec." },
    { title = "Shadow Port", flags = 0, spell = 0,
      body = "Throughout the encounter Arugal vanishes in a swirl of shadow and reappears at another vantage point in the chamber, repositioning before resuming his assault." },
  },

  -- Ragefire Chasm (instance 226)
  [11517] = { -- Oggleflint
    { title = "Cleave", flags = 0, spell = 15584,
      body = "Oggleflint swings his weapon in a wide arc, striking all enemies in front of him for additional Physical damage." },
  },
  [11520] = { -- Taragaman the Hungerer
    { title = "Fire Nova", flags = 0, spell = 11970,
      body = "Taragaman erupts in a nova of flame, inflicting Fire damage to all nearby enemies." },
    { title = "Uppercut", flags = 0, spell = 18072,
      body = "Taragaman delivers a brutal uppercut, inflicting heavy Physical damage and knocking his target back." },
  },
  [11518] = { -- Jergosh the Invoker
    { title = "Immolate", flags = 192, spell = 20800,
      body = "Jergosh engulfs an enemy in flame, inflicting Fire damage instantly and additional Fire damage over time." },
    { title = "Curse of Weakness", flags = 256, spell = 18267,
      body = "Jergosh curses his target with weakness, reducing the Physical damage they deal." },
  },
  [11519] = { -- Bazzalan
    { title = "Sinister Strike", flags = 0, spell = 14873,
      body = "Bazzalan lashes out with a sinister strike, inflicting additional Physical damage." },
    { title = "Poison", flags = 512, spell = 3616,
      body = "Bazzalan's blades are coated in poison, inflicting Nature damage over time to those he strikes." },
  },

  -- Blackfathom Deeps (instance 227)
  [4887] = { -- Ghamoo-ra
    { title = "Trample", flags = 0, spell = 5568,
      body = "Ghamoo-ra tramples the enemies around it, inflicting Physical damage to all nearby." },
  },
  [4831] = { -- Lady Sarevess
    { title = "Forked Lightning", flags = 64, spell = 8435,
      body = "Lady Sarevess hurls forked lightning, inflicting Nature damage to enemies in a cone before her." },
    { title = "Frost Nova", flags = 128, spell = 865,
      body = "Lady Sarevess blasts nearby enemies with frost, freezing them in place for a short time." },
    { title = "Slow", flags = 128, spell = 246,
      body = "Lady Sarevess slows an enemy, reducing their attack and movement speed." },
  },
  [6243] = { -- Gelihast
    { title = "Net", flags = 0, spell = 6533,
      body = "Gelihast ensnares an enemy in a net, rooting them in place and preventing escape." },
  },
  [4832] = { -- Twilight Lord Kelris
    { title = "Sleep", flags = 192, spell = 8399,
      body = "Twilight Lord Kelris lulls nearby enemies into a deep sleep, incapacitating them until they are awakened by damage." },
    { title = "Mind Blast", flags = 64, spell = 15587,
      body = "Kelris assaults a player's mind, inflicting Shadow damage." },
  },
  [4830] = { -- Old Serra'kis
    { title = "Leech Pulse", flags = 0, spell = 8434,
      body = "Old Serra'kis pulses with leeching energy, draining life from nearby enemies to heal itself." },
  },
  [4829] = { -- Aku'mai
    { title = "Poison Cloud", flags = 512, spell = 3815,
      body = "Aku'mai belches a cloud of poison, inflicting Nature damage over time to all enemies caught within it." },
    { title = "Frenzied Rage", flags = 2048, spell = 3490,
      body = "Aku'mai works itself into a frenzied rage, increasing its attack speed and the damage it deals." },
  },

  -- The Stockade (instance 238)
  [1696] = { -- Targorr the Dread
    { title = "Thrash", flags = 0, spell = 3391,
      body = "Targorr thrashes wildly, gaining additional melee attacks." },
    { title = "Enrage", flags = 2048, spell = 8599,
      body = "Upon falling below 30% health, Targorr flies into an enrage, dramatically increasing the damage he deals." },
  },
  [1666] = { -- Kam Deepfury
    { title = "Shield Slam", flags = 0, spell = 8242,
      body = "Kam Deepfury slams his shield into his target, inflicting Physical damage and stunning them briefly." },
  },
  [1717] = { -- Hamhock
    { title = "Chain Lightning", flags = 64, spell = 421,
      body = "Hamhock unleashes a bolt of lightning that arcs between nearby enemies, inflicting Nature damage." },
    { title = "Bloodlust", flags = 128, spell = 6742,
      body = "Hamhock works himself into a bloodlust, increasing his attack speed." },
  },
  [1716] = { -- Bazil Thredd
    { title = "Smoke Bomb", flags = 128, spell = 7964,
      body = "Bazil Thredd hurls a smoke bomb, stunning nearby enemies in a cloud of choking smoke." },
    { title = "Battle Shout", flags = 0, spell = 9128,
      body = "Bazil Thredd lets out a battle shout, increasing the attack power of nearby allies." },
  },
  [1663] = { -- Dextren Ward
    { title = "Strike", flags = 0, spell = 11976,
      body = "Dextren Ward delivers a powerful strike for additional Physical damage." },
    { title = "Intimidating Shout", flags = 32, spell = 19134,
      body = "Dextren Ward looses an intimidating shout, causing nearby players to flee in fear." },
  },
  [1720] = { -- Bruegal Ironknuckle (rare)
    -- No scripted spell list in cmangos and no abilities recorded on Classic Wowhead for this
    -- optional rare, so his one documented trait (the brawler's frenzy) is a spell=0 narrative
    -- section — never a fabricated spellID (cf. the other spell=0 entries in this file).
    { title = "Frenzy", flags = 2048, spell = 0,
      body = "Bruegal Ironknuckle is a rare brawler who patrols the Stockade's cellblocks. Bloodied, he works himself into a frenzy, hammering his foes with greatly increased attack speed." },
  },

  -- Razorfen Kraul (instance 234)
  [6168] = { -- Roogug
    { title = "Lightning Bolt", flags = 64, spell = 9532,
      body = "Roogug hurls a bolt of lightning at its target, inflicting Nature damage." },
    { title = "Summon Earth Rumbler", flags = 32, spell = 8270,
      body = "Roogug summons an Earth Rumbler to fight at its side." },
  },
  [4424] = { -- Aggem Thorncurse
    { title = "Chain Heal", flags = 68, spell = 14900,
      body = "Aggem Thorncurse calls upon nature to heal himself and nearby allies, the healing energy leaping between targets." },
    { title = "Summon Boar Spirit", flags = 32, spell = 8286,
      body = "Aggem Thorncurse summons a Boar Spirit to aid him in battle." },
    { title = "Battle Shout", flags = 0, spell = 6192,
      body = "Aggem Thorncurse bolsters his allies with a battle shout, increasing their attack power." },
  },
  [4428] = { -- Death Speaker Jargba
    { title = "Dominate Mind", flags = 224, spell = 14515,
      body = "Death Speaker Jargba dominates a player's mind, taking control of them and turning them against their allies." },
    { title = "Shadow Bolt", flags = 64, spell = 9613,
      body = "Death Speaker Jargba hurls a bolt of shadow, inflicting Shadow damage." },
  },
  [4420] = { -- Overlord Ramtusk
    { title = "Thunderclap", flags = 128, spell = 15548,
      body = "Overlord Ramtusk slams the ground, inflicting Nature damage to nearby enemies and slowing their attack speed." },
    { title = "Battle Shout", flags = 0, spell = 9128,
      body = "Overlord Ramtusk rallies his warband with a battle shout, increasing their attack power." },
  },
  [4422] = { -- Agathelos the Raging
    { title = "Rushing Charge", flags = 0, spell = 8260,
      body = "Agathelos rushes a distant enemy, charging into them for Physical damage." },
    { title = "Rampage", flags = 0, spell = 8285,
      body = "Agathelos rampages, battering its target with a flurry of heavy Physical blows." },
    { title = "Enrage", flags = 2048, spell = 8269,
      body = "Agathelos works itself into an enrage, increasing the damage it deals." },
  },
  [4421] = { -- Charlga Razorflank
    { title = "Chain Bolt", flags = 64, spell = 8292,
      body = "Charlga unleashes a bolt of lightning that arcs between nearby enemies, inflicting Nature damage." },
    { title = "Renew", flags = 4, spell = 6077,
      body = "Charlga renews herself or a wounded ally, restoring health over time." },
    { title = "Mana Spike", flags = 0, spell = 8358,
      body = "When her mana runs low, Charlga unleashes a spike of energy at a player, inflicting Holy damage." },
  },

  -- Scarlet Monastery (instance 316) — EventAI-backed bosses (the scripted ones follow)
  [3983] = { -- Interrogator Vishas
    { title = "Immolate", flags = 128, spell = 8981,
      body = "Interrogator Vishas sears his victims with Immolate, engulfing them in flames that burn for Fire damage over time." },
  },
  [3974] = { -- Houndmaster Loksey
    { title = "Bloodlust", flags = 128, spell = 6742,
      body = "Houndmaster Loksey incites bloodlust in his hounds, increasing their attack speed." },
    { title = "Battle Shout", flags = 0, spell = 6192,
      body = "Houndmaster Loksey urges on his pack with a battle shout, increasing their attack power." },
  },
  [4542] = { -- High Inquisitor Fairbanks
    { title = "Curse of Blood", flags = 320, spell = 8282,
      body = "Fairbanks curses a player's blood, increasing the Physical damage they take." },
    { title = "Sleep", flags = 192, spell = 8399,
      body = "Fairbanks lulls an enemy into a deep sleep, incapacitating them until they take damage." },
    { title = "Fear", flags = 192, spell = 12096,
      body = "Fairbanks strikes terror into nearby players, causing them to flee in fear." },
    { title = "Heal", flags = 68, spell = 12039,
      body = "Below 30% health, Fairbanks channels a powerful heal to restore his own health." },
    { title = "Power Word: Shield", flags = 0, spell = 11647,
      body = "Below 25% health, Fairbanks shields himself with the Light, absorbing a portion of incoming damage." },
  },
  [4543] = { -- Bloodmage Thalnos
    { title = "Shadow Bolt Volley", flags = 64, spell = 15245,
      body = "Bloodmage Thalnos unleashes a volley of shadow bolts, striking all nearby enemies for Shadow damage." },
    { title = "Flame Spike", flags = 64, spell = 8814,
      body = "Bloodmage Thalnos conjures a spike of flame, scorching all enemies caught in the area for Fire damage." },
  },
  [6487] = { -- Arcanist Doan
    { title = "Detonation", flags = 48, spell = 9435,
      body = "Surrounding himself with an arcane bubble, Arcanist Doan channels a massive detonation that erupts across the entire chamber, inflicting heavy Arcane damage to everyone. Take cover behind the pillars to survive it." },
    { title = "Polymorph", flags = 192, spell = 13323,
      body = "Arcanist Doan polymorphs a player into a harmless creature, removing them from the fight until the effect is broken." },
    { title = "Silence", flags = 192, spell = 8988,
      body = "Arcanist Doan silences nearby spellcasters, preventing them from casting for several seconds." },
    { title = "Arcane Explosion", flags = 128, spell = 9433,
      body = "Arcanist Doan releases a burst of arcane energy, inflicting Arcane damage to all nearby enemies." },
  },
  [3975] = { -- Herod
    { title = "Whirlwind", flags = 0, spell = 8989,
      body = "Herod spins in a deadly whirlwind, striking all nearby enemies for heavy Physical damage." },
    { title = "Rushing Charge", flags = 0, spell = 8260,
      body = "Herod charges a distant target, closing the gap and striking them for Physical damage." },
    { title = "Cleave", flags = 0, spell = 15496,
      body = "Herod cleaves all enemies in front of him for heavy Physical damage." },
    { title = "Frenzy", flags = 2048, spell = 8269,
      body = "Bloodied, Herod flies into a frenzy, dramatically increasing his attack speed." },
  },
  [3976] = { -- Scarlet Commander Mograine
    { title = "Crusader Strike", flags = 0, spell = 14518,
      body = "Mograine smites his target with a powerful Crusader Strike, inflicting heavy Holy and Physical damage." },
    { title = "Hammer of Justice", flags = 128, spell = 5589,
      body = "Mograine hammers his target with the weight of justice, stunning them for a short time." },
  },
  [3977] = { -- High Inquisitor Whitemane
    { title = "Scarlet Resurrection", flags = 32, spell = 9232,
      body = "When Scarlet Commander Mograine falls, Whitemane resurrects him, restoring her commander to the fight to renew his assault." },
    { title = "Deep Sleep", flags = 32, spell = 9256,
      body = "Whitemane casts the entire party into a deep sleep, incapacitating them while she revives her fallen commander." },
    { title = "Heal", flags = 68, spell = 12039,
      body = "Whitemane channels a powerful heal, restoring health to herself or to Mograine." },
    { title = "Holy Smite", flags = 64, spell = 9481,
      body = "Whitemane smites an enemy with the power of the Light, inflicting Holy damage." },
  },

  -- Razorfen Downs (instance 233)
  [7355] = { -- Tuten'kash
    { title = "Curse of Tuten'kash", flags = 256, spell = 12255,
      body = "Tuten'kash curses a player, reducing the healing they receive." },
    { title = "Web Spray", flags = 0, spell = 12252,
      body = "Tuten'kash sprays webbing over nearby enemies, rooting them in place." },
    { title = "Virulent Poison", flags = 512, spell = 12254,
      body = "Tuten'kash's bite carries a virulent poison, inflicting Nature damage over time." },
  },
  [7357] = { -- Mordresh Fire Eye
    { title = "Fireball", flags = 64, spell = 12466,
      body = "Mordresh hurls a fireball at his target, inflicting Fire damage." },
    { title = "Fire Nova", flags = 0, spell = 12470,
      body = "Mordresh erupts in a nova of fire, inflicting Fire damage to all nearby enemies." },
  },
  [8567] = { -- Glutton
    { title = "Disease Cloud", flags = 0, spell = 12627,
      body = "Glutton exudes a cloud of disease, inflicting Nature damage to nearby enemies over time." },
    { title = "Thrash", flags = 0, spell = 8876,
      body = "Glutton thrashes, gaining additional melee attacks." },
    { title = "Frenzy", flags = 2048, spell = 12795,
      body = "Below 15% health, Glutton flies into a frenzy, attacking with greatly increased speed." },
  },
  [7356] = { -- Plaguemaw the Rotting
    { title = "Putrid Stench", flags = 1024, spell = 12946,
      body = "Plaguemaw emits a putrid stench, weakening nearby enemies with rotting disease." },
    { title = "Withered Touch", flags = 0, spell = 12947,
      body = "Plaguemaw's touch withers its victims, draining their mana." },
  },
  [7354] = { -- Ragglesnout
    { title = "Dominate Mind", flags = 224, spell = 7645,
      body = "Ragglesnout dominates a player's mind, controlling them for a time." },
    { title = "Shadow Bolt", flags = 64, spell = 12471,
      body = "Ragglesnout hurls a bolt of shadow, inflicting Shadow damage." },
    { title = "Shadow Word: Pain", flags = 128, spell = 11639,
      body = "Ragglesnout afflicts a player with searing pain, inflicting Shadow damage over time." },
    { title = "Heal", flags = 68, spell = 12039,
      body = "Ragglesnout channels a heal to mend its own wounds or those of an ally." },
  },
  [7358] = { -- Amnennar the Coldbringer
    { title = "Amnennar's Wrath", flags = 0, spell = 13009,
      body = "Amnennar unleashes his wrath upon an enemy, inflicting Frost damage." },
    { title = "Summon Frost Spectres", flags = 32, spell = 12642,
      body = "At 66% health, Amnennar summons a pair of Frost Spectres to assail his foes." },
    { title = "Frost Armor", flags = 0, spell = 12556,
      body = "Amnennar wreathes himself in frost armor, chilling and slowing those who strike him in melee." },
  },

  -- Molten Core (instance 409) — raid
  [12118] = { -- Lucifron
    { title = "Impending Doom", flags = 128, spell = 19702,
      body = "Lucifron places a doom upon a player that erupts after a few seconds, inflicting heavy Shadow damage." },
    { title = "Lucifron's Curse", flags = 256, spell = 19703,
      body = "Lucifron curses the raid, greatly increasing the mana cost of their spells and abilities." },
    { title = "Shadow Shock", flags = 0, spell = 20603,
      body = "Lucifron blasts nearby enemies with shadow energy, inflicting Shadow damage." },
  },
  [11982] = { -- Magmadar
    { title = "Frenzy", flags = 2048, spell = 19451,
      body = "Magmadar works itself into a frenzy, greatly increasing its attack speed. The frenzy can be soothed by a hunter's Tranquilizing Shot." },
    { title = "Panic", flags = 128, spell = 19408,
      body = "Magmadar lets out a terrifying roar, causing nearby players to flee in fear across the molten floor." },
    { title = "Lava Bomb", flags = 32, spell = 19411,
      body = "Magmadar hurls a lava bomb at a distant player, creating a pool of fire that inflicts heavy Fire damage to any who stand in it." },
    { title = "Magma Spit", flags = 0, spell = 19449,
      body = "Magmadar spits molten rock at its enemies, inflicting Fire damage." },
  },
  [12259] = { -- Gehennas
    { title = "Gehennas' Curse", flags = 256, spell = 19716,
      body = "Gehennas curses the raid, reducing all healing they receive by 75%." },
    { title = "Rain of Fire", flags = 0, spell = 19717,
      body = "Gehennas calls down a rain of fire, inflicting Fire damage over time to all enemies in the area." },
    { title = "Shadow Bolt", flags = 64, spell = 19728,
      body = "Gehennas hurls a bolt of shadow at his target, inflicting heavy Shadow damage." },
  },
  [12057] = { -- Garr
    { title = "Antimagic Pulse", flags = 32, spell = 19492,
      body = "Garr emits an antimagic pulse, dispelling beneficial magic effects from nearby players." },
    { title = "Magma Shackles", flags = 128, spell = 19496,
      body = "Garr shackles nearby players with magma, sharply reducing their movement speed." },
  },
  [12264] = { -- Shazzrah
    { title = "Shazzrah's Curse", flags = 256, spell = 19713,
      body = "Shazzrah curses a player, increasing the magic damage they take." },
    { title = "Gate of Shazzrah", flags = 32, spell = 23138,
      body = "Shazzrah blinks to a random player, resetting his threat and teleporting into the midst of the raid." },
    { title = "Counterspell", flags = 32, spell = 2139,
      body = "Shazzrah counters an enemy's spell, locking that school of magic for several seconds." },
    { title = "Arcane Explosion", flags = 128, spell = 19712,
      body = "Shazzrah releases a burst of arcane energy, inflicting heavy Arcane damage to all nearby enemies." },
    { title = "Deaden Magic", flags = 0, spell = 19714,
      body = "Shazzrah shields himself, reducing the magic damage he takes." },
  },
  [12056] = { -- Baron Geddon
    { title = "Living Bomb", flags = 48, spell = 20475,
      body = "Baron Geddon turns a player into a living bomb. After several seconds they detonate, inflicting heavy Fire damage to everyone nearby and knocking them back. Move away from the raid before exploding." },
    { title = "Inferno", flags = 32, spell = 19695,
      body = "Baron Geddon erupts in an inferno, pulsing escalating Fire damage to all nearby players over several seconds." },
    { title = "Ignite Mana", flags = 128, spell = 19659,
      body = "Baron Geddon ignites a player's mana, draining it and inflicting Fire damage as it burns away." },
    { title = "Armageddon", flags = 16, spell = 20478,
      body = "Upon nearing death, Baron Geddon unleashes Armageddon, devastating the entire raid with catastrophic Fire damage." },
  },
  [12098] = { -- Sulfuron Harbinger
    { title = "Hand of Ragnaros", flags = 32, spell = 19780,
      body = "Sulfuron slams the ground with the Hand of Ragnaros, inflicting Fire damage to nearby players and knocking them back." },
    { title = "Inspire", flags = 32, spell = 19779,
      body = "Sulfuron inspires his Flamewaker Priests, increasing their attack and casting speed." },
    { title = "Demoralizing Shout", flags = 0, spell = 19778,
      body = "Sulfuron lets out a demoralizing shout, reducing the attack power of nearby enemies." },
    { title = "Knockdown", flags = 0, spell = 16790,
      body = "Sulfuron knocks down his target, stunning them briefly." },
  },
  [11988] = { -- Golemagg the Incinerator
    { title = "Magma Splash", flags = 1, spell = 13879,
      body = "Golemagg's blows splash molten rock on his target, a stacking debuff that increases the Fire damage they take." },
    { title = "Earthquake", flags = 32, spell = 19798,
      body = "Golemagg stomps the ground, inflicting Physical damage to all nearby players and briefly stunning them." },
    { title = "Pyroblast", flags = 0, spell = 20228,
      body = "Golemagg hurls a massive pyroblast at a distant enemy, inflicting heavy Fire damage." },
  },
  [12018] = { -- Majordomo Executus
    { title = "Magic Reflection", flags = 32, spell = 20619,
      body = "Majordomo Executus shields himself and his guards, reflecting harmful magic back at its caster. Stop casting until it fades." },
    { title = "Damage Shield", flags = 1, spell = 21075,
      body = "Majordomo Executus surrounds himself with a damage shield, reflecting a portion of melee damage back at attackers." },
    { title = "Blast Wave", flags = 0, spell = 20229,
      body = "Majordomo Executus unleashes a blast wave of fire, inflicting Fire damage to nearby players and slowing them." },
  },
  [11502] = { -- Ragnaros
    { title = "Wrath of Ragnaros", flags = 32, spell = 20566,
      body = "Ragnaros strikes a player with his wrath, inflicting Fire damage and hurling them back with tremendous force." },
    { title = "Hand of Ragnaros", flags = 32, spell = 19780,
      body = "Ragnaros slams the molten ground, inflicting Fire damage to all nearby players and knocking them back." },
    { title = "Lava Burst", flags = 32, spell = 21158,
      body = "Ragnaros causes bursts of lava to erupt from the Firelands, inflicting heavy Fire damage to any player caught above them." },
    { title = "Elemental Fire", flags = 0, spell = 20564,
      body = "Ragnaros sears his target with elemental fire, inflicting Fire damage over time." },
    { title = "Sons of Flame", flags = 32, spell = 21108,
      body = "At intervals Ragnaros submerges into the Firelands and summons his Sons of Flame to assail the raid before re-emerging." },
  },

  -- Blackwing Lair (instance 469) — raid
  [12435] = { -- Razorgore the Untamed
    { title = "Conflagration", flags = 32, spell = 23023,
      body = "Razorgore conflagrates a player, inflicting Fire damage over time and causing them to flee in confusion." },
    { title = "Fireball Volley", flags = 0, spell = 22425,
      body = "Razorgore unleashes a volley of fireballs, striking multiple enemies for Fire damage." },
    { title = "Intimidating Roar", flags = 32, spell = 16508,
      body = "Razorgore looses an intimidating roar, causing nearby players to flee in fear." },
    { title = "Cleave", flags = 0, spell = 22540,
      body = "Razorgore cleaves all enemies in front of him for heavy Physical damage." },
  },
  [13020] = { -- Vaelastrasz the Corrupt
    { title = "Essence of the Red", flags = 32, spell = 23513,
      body = "Vaelastrasz grants the raid the Essence of the Red, flooding them with mana, rage, and energy so they may burn him down before his Burning Adrenaline consumes everyone." },
    { title = "Burning Adrenaline", flags = 48, spell = 23620,
      body = "Vaelastrasz afflicts a player with burning adrenaline; their casts become instant, but they build toward a fatal explosion that inflicts massive Fire damage to all nearby. The current tank is afflicted periodically and cannot survive it." },
    { title = "Flame Breath", flags = 0, spell = 23461,
      body = "Vaelastrasz breathes a cone of fire, inflicting heavy Fire damage to all enemies in front of him." },
    { title = "Cleave", flags = 0, spell = 22540,
      body = "Vaelastrasz cleaves all enemies before him for heavy Physical damage." },
    { title = "Tail Sweep", flags = 0, spell = 15847,
      body = "Vaelastrasz sweeps his tail, inflicting Physical damage and knocking back enemies behind him." },
  },
  [12017] = { -- Broodlord Lashlayer
    { title = "Mortal Strike", flags = 1, spell = 24573,
      body = "Broodlord Lashlayer delivers a mortal strike, inflicting heavy Physical damage and reducing the healing his target receives." },
    { title = "Knock Away", flags = 1, spell = 25778,
      body = "Broodlord Lashlayer knocks his target away, inflicting Physical damage and sharply reducing their threat." },
    { title = "Blast Wave", flags = 0, spell = 23331,
      body = "Broodlord Lashlayer unleashes a blast wave of fire, inflicting Fire damage to nearby players and knocking them back." },
    { title = "Cleave", flags = 0, spell = 22540,
      body = "Broodlord Lashlayer cleaves all enemies in front of him for heavy Physical damage." },
  },
  [11983] = { -- Firemaw
    { title = "Shadow Flame", flags = 32, spell = 22539,
      body = "Firemaw breathes shadowflame in a wide cone, inflicting catastrophic Shadow damage and leaving victims vulnerable." },
    { title = "Flame Buffet", flags = 32, spell = 23341,
      body = "Firemaw buffets enemies in front of him with flame, a stacking debuff that increases the Fire damage they take until they break line of sight." },
    { title = "Wing Buffet", flags = 1, spell = 23339,
      body = "Firemaw buffets the area before him with his wings, inflicting Physical damage, knocking players back and reducing their threat." },
  },
  [14601] = { -- Ebonroc
    { title = "Shadow of Ebonroc", flags = 33, spell = 23340,
      body = "Ebonroc curses his target with his shadow, healing himself whenever he strikes them. The afflicted tank must be swapped out until the debuff fades." },
    { title = "Shadow Flame", flags = 32, spell = 22539,
      body = "Ebonroc breathes shadowflame in a wide cone, inflicting catastrophic Shadow damage and leaving victims vulnerable." },
    { title = "Wing Buffet", flags = 1, spell = 23339,
      body = "Ebonroc buffets the area before him with his wings, inflicting Physical damage, knocking players back and reducing their threat." },
  },
  [11981] = { -- Flamegor
    { title = "Frenzy", flags = 2048, spell = 23342,
      body = "Flamegor periodically enters a frenzy, increasing his attack speed. It can be soothed by a hunter's Tranquilizing Shot." },
    { title = "Shadow Flame", flags = 32, spell = 22539,
      body = "Flamegor breathes shadowflame in a wide cone, inflicting catastrophic Shadow damage and leaving victims vulnerable." },
    { title = "Wing Buffet", flags = 1, spell = 23339,
      body = "Flamegor buffets the area before him with his wings, inflicting Physical damage, knocking players back and reducing their threat." },
  },
  [14020] = { -- Chromaggus
    { title = "Brood Affliction", flags = 32, spell = 23153,
      body = "Chromaggus afflicts the raid with Brood Afflictions of five colors. A player carrying all five mutates into a Chromatic Drakonid, so afflictions must be grouped and cleansed carefully." },
    { title = "Time Lapse", flags = 32, spell = 23310,
      body = "Chromaggus's time-lapse breath inflicts Arcane damage and warps time around its victims, sharply reducing their threat." },
    { title = "Incinerate", flags = 0, spell = 23308,
      body = "Chromaggus exhales a torrent of fire, inflicting heavy Fire damage to all enemies before him." },
    { title = "Corrosive Acid", flags = 0, spell = 23313,
      body = "Chromaggus breathes corrosive acid, inflicting Nature damage over time and reducing the armor of those it strikes." },
    { title = "Frenzy", flags = 2048, spell = 23128,
      body = "Chromaggus flies into a frenzy, increasing his attack speed. It can be soothed by a hunter's Tranquilizing Shot." },
  },
  [11583] = { -- Nefarian
    { title = "Shadow Flame", flags = 32, spell = 22539,
      body = "Nefarian breathes shadowflame, inflicting catastrophic Shadow damage to all enemies in a wide arc before him." },
    { title = "Class Calls", flags = 32, spell = 0,
      body = "Throughout the final phase Nefarian shouts mocking commands at specific classes — turning warriors berserk, banishing hunters' ranged weapons, polymorphing the raid's mages, and more — each disrupting that class for several seconds." },
    { title = "Bellowing Roar", flags = 32, spell = 22686,
      body = "Nefarian lets out a bellowing roar, causing the entire raid to flee in fear." },
    { title = "Tail Lash", flags = 0, spell = 23364,
      body = "Nefarian lashes his tail, inflicting Physical damage and stunning enemies standing behind him." },
    { title = "Cleave", flags = 0, spell = 22540,
      body = "Nefarian cleaves all enemies in front of him for heavy Physical damage." },
  },

  -- Onyxia's Lair (instance 249) — raid
  [10184] = { -- Onyxia
    { title = "Deep Breath", flags = 16, spell = 17086,
      body = "Onyxia inhales deeply and exhales a wall of fire across the length of the cavern, inflicting catastrophic Fire damage to any caught in its path." },
    { title = "Flame Breath", flags = 0, spell = 18435,
      body = "Onyxia breathes a cone of fire before her, inflicting heavy Fire damage to all enemies caught in it." },
    { title = "Bellowing Roar", flags = 32, spell = 18431,
      body = "In her final phase, Onyxia repeatedly lets out a bellowing roar, causing the entire raid to flee in fear." },
    { title = "Fireball", flags = 0, spell = 18392,
      body = "While airborne, Onyxia hurls fireballs at random players, inflicting heavy Fire damage." },
    { title = "Wing Buffet", flags = 1, spell = 18500,
      body = "Onyxia buffets the area in front of her with her wings, inflicting Physical damage, knocking players back and reducing their threat." },
    { title = "Tail Sweep", flags = 0, spell = 0,
      body = "Onyxia sweeps her tail, hurling players standing behind her across the cavern." },
    { title = "Onyxian Whelps", flags = 32, spell = 0,
      body = "During her air phase, Onyxia summons waves of Onyxian Whelps from the eggs at the cavern's edges to swarm the raid." },
  },

  -- Ruins of Ahn'Qiraj (instance 509) — 20-player raid
  [15348] = { -- Kurinnaxx
    { title = "Mortal Wound", flags = 1, spell = 25646,
      body = "Kurinnaxx's strikes inflict Mortal Wounds, a stacking debuff that reduces the healing his target receives." },
    { title = "Sand Trap", flags = 32, spell = 25648,
      body = "Kurinnaxx conjures sand traps beneath the raid that erupt when disturbed, inflicting heavy Nature damage and hurling players into the air." },
    { title = "Enrage", flags = 2048, spell = 0,
      body = "Over the course of the fight Kurinnaxx steadily enrages, increasing the damage he deals — he must be slain before it becomes lethal." },
  },
  [15341] = { -- General Rajaxx
    { title = "Summon the Army", flags = 32, spell = 0,
      body = "Rajaxx commands wave after wave of the Qiraji army, each led by a captain, to assault the raid before he himself enters the fray." },
    { title = "Thundercrack", flags = 128, spell = 8150,
      body = "Rajaxx unleashes a thundercrack, inflicting Nature damage and stunning all nearby players." },
    { title = "Thunderclap", flags = 128, spell = 8078,
      body = "Rajaxx slams the ground, inflicting Nature damage to nearby players and slowing their attack speed." },
  },
  [15340] = { -- Moam
    { title = "Drain Mana", flags = 32, spell = 25671,
      body = "Moam drains the mana from the raid's casters, converting it into arcane energy that builds toward a devastating release." },
    { title = "Arcane Eruption", flags = 32, spell = 25672,
      body = "Once charged with stolen mana, Moam erupts with arcane energy, inflicting heavy Arcane damage to the entire raid." },
    { title = "Summon Mana Fiends", flags = 32, spell = 0,
      body = "Moam summons Mana Fiends to drain the raid and turns to stone to recharge once fully energized." },
  },
  [15370] = { -- Buru the Gorger
    { title = "Full Speed", flags = 32, spell = 1557,
      body = "Buru fixates on a single player and pursues them at full speed, ignoring all others. The raid must kite him among his eggs." },
    { title = "Egg Explosion", flags = 32, spell = 0,
      body = "Buru takes greatly reduced damage until his eggs are destroyed. Each egg explodes violently when broken, weakening Buru but harming the raid." },
    { title = "Creeping Plague", flags = 0, spell = 20512,
      body = "Once his eggs are gone, Buru afflicts the raid with a creeping plague, inflicting escalating Nature damage over time." },
  },
  [15369] = { -- Ayamiss the Hunter
    { title = "Paralyze", flags = 32, spell = 25725,
      body = "Ayamiss paralyzes a random player and levitates them to the sacrificial altar, where her swarmers feed on them unless the raid intervenes." },
    { title = "Stinger Spray", flags = 0, spell = 25749,
      body = "Ayamiss sprays a volley of stingers, inflicting Nature damage to players in front of her." },
    { title = "Poison Stinger", flags = 0, spell = 25748,
      body = "While airborne, Ayamiss looses a poison stinger at a distant player, inflicting heavy Nature damage." },
  },
  [15339] = { -- Ossirian the Unscarred
    { title = "Strength of Ossirian", flags = 2048, spell = 25176,
      body = "Ossirian gains a stacking buff that steadily increases his damage. It can only be stripped by luring him onto one of the Crystals scattered around the arena." },
    { title = "Sand Storm", flags = 32, spell = 10134,
      body = "Tornadoes of sand sweep across the arena, hurling any player they touch high into the air." },
    { title = "Supreme Mode", flags = 16, spell = 0,
      body = "If Ossirian is not weakened at a crystal in time, he enters Supreme Mode and devastates the raid with overwhelming force." },
  },

  -- Temple of Ahn'Qiraj (instance 531) — 40-player raid
  [15263] = { -- The Prophet Skeram
    { title = "True Fulfillment", flags = 32, spell = 785,
      body = "Skeram seizes control of a player's mind, turning them against the raid for a time." },
    { title = "Arcane Explosion", flags = 128, spell = 26192,
      body = "Skeram releases a burst of arcane energy, inflicting heavy Arcane damage to all nearby players." },
    { title = "Earth Shock", flags = 0, spell = 26194,
      body = "Skeram blasts a player with Earth Shock, inflicting Nature damage and interrupting their spellcasting." },
    { title = "Mirror Image", flags = 32, spell = 0,
      body = "At intervals Skeram splits into illusory copies of himself, each able to cast his spells. The images must be cut down to find the true Prophet." },
  },
  [15511] = { -- Silithid Royalty (Kri, Vem, Princess Yauj)
    { title = "Lord Kri: Toxic Volley", flags = 512, spell = 25812,
      body = "Lord Kri looses a volley of toxic spines, inflicting Nature damage and poisoning the raid." },
    { title = "Lord Kri: Poison Cloud", flags = 512, spell = 0,
      body = "When Lord Kri dies, his corpse bursts into a lingering cloud of poison that inflicts heavy Nature damage to any who linger in it." },
    { title = "Vem: Charge & Knock Away", flags = 0, spell = 25778,
      body = "Vem charges across the room and knocks his target away, constantly closing and resetting distance." },
    { title = "Vem's Fury", flags = 2048, spell = 0,
      body = "Should Vem fall before his siblings, Princess Yauj and Lord Kri fly into an enrage for the rest of the fight — Vem must be slain last." },
    { title = "Princess Yauj: Heal", flags = 68, spell = 0,
      body = "Princess Yauj channels powerful heals on her brothers, undoing the raid's progress unless interrupted." },
    { title = "Princess Yauj: Fear", flags = 128, spell = 0,
      body = "Princess Yauj terrifies nearby players, causing them to flee, and summons Yauj Brood on her death." },
  },
  [15516] = { -- Battleguard Sartura
    { title = "Whirlwind", flags = 0, spell = 26083,
      body = "Sartura spins in a relentless whirlwind, inflicting heavy Physical damage to all nearby players while moving unpredictably." },
    { title = "Sundering Cleave", flags = 0, spell = 25174,
      body = "Sartura cleaves all enemies before her, inflicting heavy Physical damage." },
    { title = "Enrage", flags = 2048, spell = 28747,
      body = "Sartura enrages, increasing her attack speed and the damage she deals." },
    { title = "Royal Guards", flags = 32, spell = 0,
      body = "Sartura fights alongside her Royal Guards, who also whirlwind and must be controlled by the raid." },
  },
  [15510] = { -- Fankriss the Unyielding
    { title = "Mortal Wound", flags = 1, spell = 28467,
      body = "Fankriss's strikes inflict Mortal Wounds, a stacking debuff that reduces the healing his target receives." },
    { title = "Entangle", flags = 32, spell = 720,
      body = "Fankriss entangles a random player in webbing, rooting them in place and spawning a Spawn of Fankriss to attack them." },
    { title = "Summon Spawns", flags = 32, spell = 0,
      body = "Fankriss teleports players into his brood and summons Spawns of Fankriss and Vekniss Hatchlings to overwhelm the raid." },
  },
  [15299] = { -- Viscidus
    { title = "Frost Vulnerability", flags = 32, spell = 0,
      body = "Viscidus is vulnerable to Frost. Enough Frost damage slows and then freezes him solid, after which a flurry of melee blows shatters him into Glob oozes." },
    { title = "Poison Bolt Volley", flags = 512, spell = 25991,
      body = "Viscidus hurls a volley of poison bolts, inflicting Nature damage to the raid." },
    { title = "Toxin", flags = 0, spell = 26575,
      body = "Viscidus poisons his attackers with a virulent toxin, inflicting Nature damage over time." },
  },
  [15509] = { -- Princess Huhuran
    { title = "Frenzy", flags = 2048, spell = 23128,
      body = "Huhuran periodically enters a frenzy, increasing her attack and casting speed. It can be soothed by a hunter's Tranquilizing Shot." },
    { title = "Berserk", flags = 2048, spell = 26068,
      body = "Below 30% health, Huhuran goes berserk, unleashing relentless torrents of poison on the entire raid until she falls." },
    { title = "Noxious Poison", flags = 512, spell = 26053,
      body = "Huhuran sprays a noxious poison, inflicting Nature damage over time to those it strikes." },
    { title = "Wyvern Sting", flags = 512, spell = 19386,
      body = "Huhuran stings a player, sending them into a poisoned slumber until the venom runs its course." },
  },
  [15276] = { -- The Twin Emperors (Vek'lor & Vek'nilash)
    { title = "Twin Teleport & Heal", flags = 32, spell = 0,
      body = "The emperors swap positions every thirty seconds and heal one another to full whenever they stand close together — they must be tanked far apart and brought low at the same time." },
    { title = "Vek'lor: Shadow Bolt", flags = 64, spell = 26006,
      body = "Emperor Vek'lor hurls heavy Shadow Bolts at the raid from range." },
    { title = "Vek'lor: Arcane Burst", flags = 128, spell = 568,
      body = "When struck in melee, Emperor Vek'lor releases an Arcane Burst, inflicting heavy Arcane damage and knocking nearby players back — he must be fought at range." },
    { title = "Vek'lor: Blizzard", flags = 0, spell = 26607,
      body = "Emperor Vek'lor conjures a blizzard, inflicting Frost damage over a wide area." },
    { title = "Vek'nilash: Unbalancing Strike", flags = 0, spell = 26613,
      body = "Emperor Vek'nilash delivers an unbalancing strike, inflicting heavy Physical damage and reducing his target's defense." },
    { title = "Vek'nilash: Uppercut", flags = 0, spell = 10966,
      body = "Emperor Vek'nilash launches his target into the air with a mighty uppercut." },
  },
  [15517] = { -- Ouro
    { title = "Sand Blast", flags = 32, spell = 26102,
      body = "Ouro unleashes a sand blast, inflicting massive Nature damage to players in front of him." },
    { title = "Ground Rupture", flags = 0, spell = 26100,
      body = "When Ouro erupts from the sand, the ground ruptures beneath the raid, inflicting Physical damage and knocking players back." },
    { title = "Submerge & Summon", flags = 32, spell = 0,
      body = "Ouro periodically burrows beneath the sand, summoning Dirt Mounds and Ouro Scarabs before erupting back to the surface." },
    { title = "Enrage", flags = 2048, spell = 0,
      body = "If the fight runs long, Ouro enrages, vastly increasing the damage he deals." },
  },
  [15727] = { -- C'Thun
    { title = "Dark Glare", flags = 16, spell = 26029,
      body = "In its eye phase, C'Thun's great eye unleashes a rotating Dark Glare — a sweeping beam that instantly kills anything it touches. Take cover behind the chamber's pillars." },
    { title = "Eye Beam", flags = 0, spell = 26134,
      body = "C'Thun's eye fires green beams that chain between nearby players, inflicting Nature damage." },
    { title = "Flesh Tentacles & Stomach", flags = 32, spell = 0,
      body = "In its body phase, C'Thun swallows players whole into its stomach, where two Flesh Tentacles must be destroyed to leave C'Thun vulnerable. Giant Claw and Eye Tentacles erupt from the body throughout." },
    { title = "Digestive Acid", flags = 0, spell = 26476,
      body = "Players swallowed into C'Thun's stomach are bathed in digestive acid, taking steady Nature damage until they escape." },
  },

  -- Zul'Gurub (instance 309) — 20-player raid
  [14507] = { -- High Priest Venoxis
    { title = "Holy Fire", flags = 192, spell = 15261,
      body = "Venoxis engulfs an enemy in holy fire, inflicting Holy damage instantly and additional Holy damage over time." },
    { title = "Holy Nova", flags = 0, spell = 15237,
      body = "Venoxis releases a burst of holy energy, inflicting Holy damage to all nearby enemies." },
    { title = "Renew", flags = 4, spell = 139,
      body = "Venoxis renews himself, restoring health over time." },
    { title = "Venom Spit", flags = 512, spell = 23849,
      body = "At low health Venoxis transforms into a great cobra, spitting venom that inflicts Nature damage over time and poisoning the raid." },
  },
  [14517] = { -- High Priestess Jeklik
    { title = "Sonic Burst", flags = 128, spell = 23918,
      body = "In bat form, Jeklik looses a sonic burst, inflicting heavy Physical damage and silencing those it strikes." },
    { title = "Charge", flags = 0, spell = 100,
      body = "Jeklik charges a distant player, closing the gap and stunning them briefly." },
    { title = "Psychic Scream", flags = 32, spell = 8122,
      body = "In troll form, Jeklik unleashes a psychic scream, causing nearby players to flee in fear." },
    { title = "Great Heal", flags = 68, spell = 23954,
      body = "Jeklik channels a powerful heal to restore her own health. Interrupt it to keep the pressure on." },
    { title = "Bat Swarm", flags = 32, spell = 0,
      body = "Jeklik summons swarms of Frenzied Bats to harry the raid throughout the fight." },
  },
  [14510] = { -- High Priestess Mar'li
    { title = "Poison Bolt Volley", flags = 512, spell = 24099,
      body = "Mar'li hurls a volley of poison bolts, inflicting Nature damage to the raid." },
    { title = "Spawn of Mar'li", flags = 32, spell = 0,
      body = "Mar'li transforms into a great spider and births swarms of Spawn of Mar'li that hatch and grow into deadly broodlings." },
    { title = "Charge", flags = 0, spell = 100,
      body = "Mar'li charges a distant player, closing the gap and stunning them." },
    { title = "Enrage", flags = 2048, spell = 0,
      body = "As she nears death Mar'li enrages, increasing her attack speed and the damage she deals." },
  },
  [11382] = { -- Bloodlord Mandokir
    { title = "Threatening Gaze", flags = 32, spell = 24314,
      body = "Mandokir fixes a player with a threatening gaze. If they move or act while watched, he charges and strikes them down — stand still until it passes." },
    { title = "Bloodlord's Rage", flags = 2048, spell = 0,
      body = "Each player Mandokir slays empowers him, increasing his size and the damage he deals for the rest of the fight." },
    { title = "Charge", flags = 0, spell = 100,
      body = "Mandokir charges a distant player, closing the gap and striking them for Physical damage." },
    { title = "Whirlwind", flags = 0, spell = 1680,
      body = "Mandokir spins in a whirlwind, inflicting Physical damage to all nearby players." },
    { title = "Ohgan", flags = 32, spell = 0,
      body = "Mandokir rides his devilsaur Ohgan into battle; once Ohgan is slain, the Bloodlord fights on foot." },
  },
  [15114] = { -- Gahz'ranka
    { title = "Massive Geyser", flags = 32, spell = 22421,
      body = "Gahz'ranka summons a massive geyser beneath a player, hurling them high into the air." },
    { title = "Frost Breath", flags = 0, spell = 3131,
      body = "Gahz'ranka breathes a cone of frost, inflicting Frost damage and slowing those it strikes." },
    { title = "Slam", flags = 0, spell = 0,
      body = "Gahz'ranka slams a nearby player, inflicting heavy Physical damage." },
  },
  [14509] = { -- High Priest Thekal
    { title = "Resurrection", flags = 32, spell = 0,
      body = "Thekal and his two High Zealots resurrect one another unless all three are brought to defeat within moments of each other." },
    { title = "Mortal Cleave", flags = 1, spell = 22859,
      body = "Thekal cleaves his target, inflicting heavy Physical damage and reducing the healing they receive." },
    { title = "Silence", flags = 192, spell = 8988,
      body = "Thekal silences nearby spellcasters, preventing them from casting for several seconds." },
    { title = "Blood Lust", flags = 128, spell = 379,
      body = "Thekal works himself into a blood lust, increasing his attack speed." },
    { title = "Frenzy", flags = 2048, spell = 0,
      body = "Revived in tiger form, Thekal enters a frenzy, savaging the raid with rapid, brutal strikes." },
  },
  [14515] = { -- High Priestess Arlokk
    { title = "Mark of Arlokk", flags = 32, spell = 0,
      body = "Arlokk marks a player and vanishes, summoning packs of panthers that fixate on and charge the marked target." },
    { title = "Gouge", flags = 0, spell = 1777,
      body = "Arlokk gouges her target, inflicting Physical damage and incapacitating them briefly." },
    { title = "Whirlwind", flags = 0, spell = 1680,
      body = "Arlokk spins in a whirlwind, inflicting Physical damage to all nearby players." },
    { title = "Shadow Word: Pain", flags = 128, spell = 11639,
      body = "Arlokk afflicts a player with searing pain, inflicting Shadow damage over time." },
  },
  [11380] = { -- Jin'do the Hexxer
    { title = "Brain Wash Totem", flags = 32, spell = 0,
      body = "Jin'do plants a Brain Wash Totem that seizes control of nearby players' minds. Destroy it quickly." },
    { title = "Powerful Hex", flags = 256, spell = 0,
      body = "Jin'do hexes a player, transforming them into a harmless frog and stripping their abilities until the curse is removed." },
    { title = "Shades of Jin'do", flags = 32, spell = 0,
      body = "Jin'do spawns shadowy Shades that pursue and drain the mana of the raid's casters." },
    { title = "Healing Ward", flags = 68, spell = 0,
      body = "Jin'do summons a Healing Ward that rapidly mends him; it must be destroyed to make progress." },
  },
  [14834] = { -- Hakkar
    { title = "Aspects of the Hakkari", flags = 32, spell = 0,
      body = "Until each High Priest is slain, Hakkar wields their aspect — Jeklik's bats, Venoxis' renew, Mar'li's poison, Thekal's frenzy, and Arlokk's gaze. Clearing the priests first strips these powers away." },
    { title = "Blood Siphon", flags = 32, spell = 24323,
      body = "Hakkar siphons the blood of the raid, draining their life to heal himself." },
    { title = "Corrupted Blood", flags = 0, spell = 24328,
      body = "Hakkar infects a player with Corrupted Blood, a virulent affliction that inflicts heavy Shadow damage and spreads to anyone standing nearby." },
    { title = "Cause Insanity", flags = 32, spell = 24327,
      body = "Hakkar drives a player insane, turning them against their allies for a time." },
  },
  [15082] = { -- Gri'lek (Edge of Madness)
    { title = "Charge", flags = 0, spell = 100,
      body = "Gri'lek charges a distant player, closing the gap and striking them for heavy Physical damage." },
    { title = "Ground Tremor", flags = 32, spell = 0,
      body = "Gri'lek smashes the ground, inflicting Physical damage to nearby players and interrupting their spellcasting." },
    { title = "Maul", flags = 0, spell = 0,
      body = "Gri'lek mauls his target with a savage two-handed blow for heavy Physical damage." },
  },
  [15083] = { -- Hazza'rah (Edge of Madness)
    { title = "Sleep", flags = 192, spell = 700,
      body = "Hazza'rah lulls a player into a deep sleep, incapacitating them until they take damage." },
    { title = "Mana Burn", flags = 32, spell = 0,
      body = "Hazza'rah burns away a player's mana, inflicting Shadow damage in proportion to the amount destroyed." },
    { title = "Nightmare Illusions", flags = 32, spell = 0,
      body = "Hazza'rah summons Nightmare Illusions to assail the raid while he hides among them." },
  },
  [15084] = { -- Renataki (Edge of Madness)
    { title = "Thousand Blades", flags = 0, spell = 24649,
      body = "Renataki assaults his target with a thousand blades, inflicting rapid bursts of heavy Physical damage." },
    { title = "Gouge", flags = 0, spell = 1777,
      body = "Renataki gouges his target, inflicting Physical damage and incapacitating them briefly." },
    { title = "Vanish & Ambush", flags = 32, spell = 0,
      body = "Renataki vanishes from sight and reappears behind a random player, ambushing them for massive Physical damage." },
  },
  [15085] = { -- Wushoolay (Edge of Madness)
    { title = "Lightning Cloud", flags = 0, spell = 8293,
      body = "Wushoolay conjures a lightning cloud over the ground, inflicting Nature damage to any player who stands beneath it." },
    { title = "Chain Lightning", flags = 64, spell = 421,
      body = "Wushoolay hurls a bolt of lightning that arcs between nearby players, inflicting Nature damage." },
    { title = "War Stomp", flags = 32, spell = 0,
      body = "Wushoolay stomps the ground, stunning all nearby players for a short time." },
  },

  -- Naxxramas (instance 533) — 40-player raid
  [15956] = { -- Anub'Rekhan
    { title = "Impale", flags = 32, spell = 28783,
      body = "Anub'Rekhan erupts a line of impaling spikes from the ground, inflicting heavy Physical damage and hurling players into the air." },
    { title = "Locust Swarm", flags = 32, spell = 28785,
      body = "Anub'Rekhan surrounds himself with a swarm of locusts, draining the life of nearby players and silencing them. The tank must kite him away until it ends." },
    { title = "Corpse Scarabs", flags = 32, spell = 0,
      body = "Slain Crypt Guards and the boss's own corpse erupt with Corpse Scarabs that swarm the raid." },
  },
  [15953] = { -- Grand Widow Faerlina
    { title = "Poison Bolt Volley", flags = 512, spell = 28796,
      body = "Faerlina looses a volley of poison bolts, inflicting heavy Nature damage to the raid." },
    { title = "Rain of Fire", flags = 0, spell = 28794,
      body = "Faerlina calls down a rain of fire, inflicting Fire damage to all players in the area." },
    { title = "Frenzy", flags = 2048, spell = 0,
      body = "Faerlina enrages, vastly increasing her damage. Mind-controlling one of her Worshippers and unleashing its Widow's Embrace removes the frenzy and silences her." },
  },
  [15952] = { -- Maexxna
    { title = "Web Wrap", flags = 32, spell = 28617,
      body = "Maexxna hurls players against the cavern walls, cocooning them in webbing until they are freed by their allies." },
    { title = "Web Spray", flags = 32, spell = 29484,
      body = "Maexxna sprays the raid with webbing, stunning everyone for several seconds." },
    { title = "Necrotic Poison", flags = 512, spell = 28776,
      body = "Maexxna's bite injects a necrotic poison, sharply reducing the healing her target receives." },
    { title = "Frenzy", flags = 2048, spell = 0,
      body = "Below 30% health, Maexxna enters a frenzy, attacking with greatly increased speed." },
  },
  [15954] = { -- Noth the Plaguebringer
    { title = "Curse of the Plaguebringer", flags = 256, spell = 29213,
      body = "Noth curses the raid; after a few seconds the curse erupts, inflicting heavy Shadow damage to anyone still afflicted." },
    { title = "Cripple", flags = 128, spell = 89,
      body = "Noth cripples a player, slowing their attack and movement speed and weakening their strength." },
    { title = "Blink & Raise Dead", flags = 32, spell = 0,
      body = "Noth blinks free of melee and raises Plagued Champions and Warriors, periodically teleporting to his balcony to send skeletons against the raid." },
  },
  [15936] = { -- Heigan the Unclean
    { title = "Eruption", flags = 16, spell = 17731,
      body = "Heigan channels eruptions of plague that sweep across the floor in sequence. Players must move through the safe zones in rhythm — the infamous Safety Dance — or be killed instantly." },
    { title = "Decrepit Fever", flags = 1024, spell = 29998,
      body = "Heigan afflicts the raid with Decrepit Fever, a disease that inflicts Nature damage over time and reduces maximum health." },
    { title = "Spell Disruption", flags = 32, spell = 0,
      body = "Heigan disrupts the magic around him, sharply increasing the mana cost of the raid's spells." },
  },
  [16011] = { -- Loatheb
    { title = "Necrotic Aura", flags = 32, spell = 0,
      body = "Loatheb radiates a Necrotic Aura that prevents nearly all healing. Healing lands only in brief windows between its pulses, demanding precise cooldown timing." },
    { title = "Inevitable Doom", flags = 16, spell = 29204,
      body = "As the fight wears on, Loatheb inflicts Inevitable Doom at ever-shorter intervals, dealing escalating Shadow damage the healers must survive between Necrotic Aura windows." },
    { title = "Spores", flags = 32, spell = 0,
      body = "Loatheb periodically releases Spores; players spread out to soak them and gain the Fungal Bloom buff needed to maximize their damage." },
  },
  [16061] = { -- Instructor Razuvious
    { title = "Understudies", flags = 32, spell = 0,
      body = "Razuvious can only be held by his Death Knight Understudies, which the raid must mind-control with Obedience Crystals and use to tank him." },
    { title = "Unbalancing Strike", flags = 0, spell = 26613,
      body = "Razuvious delivers an unbalancing strike, inflicting heavy Physical damage and reducing his target's defense." },
    { title = "Disrupting Shout", flags = 0, spell = 29107,
      body = "Razuvious lets out a disrupting shout, inflicting heavy damage to everyone near him." },
  },
  [16060] = { -- Gothik the Harvester
    { title = "Split Realm", flags = 32, spell = 0,
      body = "Gothik divides the raid across a gate into living and dead sides, sending waves of undead that cross over when slain. He cannot be reached until every add falls." },
    { title = "Shadow Bolt", flags = 64, spell = 29317,
      body = "Once he descends to fight, Gothik hurls Shadow Bolts at the raid, inflicting heavy Shadow damage." },
    { title = "Harvest Soul", flags = 0, spell = 28679,
      body = "Gothik harvests the souls of nearby players, inflicting Shadow damage." },
  },
  [16065] = { -- The Four Horsemen
    { title = "Mark of the Horsemen", flags = 32, spell = 0,
      body = "Each Horseman brands their target with a Mark that stacks ever higher and more painful. Tanks and raid must rotate around the four corners of the room to keep their stacks from turning lethal." },
    { title = "Meteor", flags = 32, spell = 0,
      body = "Thane Korth'azz hurls fiery Meteors that inflict massive Fire damage split among nearby players." },
    { title = "Void Zone", flags = 32, spell = 0,
      body = "Lady Blaumeux conjures Void Zones of shadow on the ground that inflict heavy damage to any who stand in them." },
    { title = "Holy Wrath", flags = 0, spell = 28883,
      body = "Sir Zeliek, fighting against his will, looses Holy Wrath and chains of holy lightning across the raid." },
    { title = "Death and Decay", flags = 0, spell = 0,
      body = "Baron Rivendare blankets areas of the floor in Death and Decay, inflicting Shadow damage over time to any who remain." },
  },
  [16028] = { -- Patchwerk
    { title = "Hateful Strike", flags = 33, spell = 28308,
      body = "Patchwerk pounds the highest-health player within melee range with a Hateful Strike for enormous Physical damage. Off-tanks must stack in close to absorb these blows." },
    { title = "Enrage", flags = 2048, spell = 28131,
      body = "Below 5% health, Patchwerk enrages, dramatically increasing his attack speed for a frantic final push." },
  },
  [15931] = { -- Grobbulus
    { title = "Mutating Injection", flags = 1056, spell = 28169,
      body = "Grobbulus injects a player with a mutating agent. When it expires or is dispelled it bursts into a lingering Poison Cloud, so the afflicted must carry it to the edge of the room." },
    { title = "Poison Cloud", flags = 32, spell = 0,
      body = "Grobbulus trails clouds of poison gas as he moves, which expand and inflict escalating Nature damage — the raid must keep the floor clear." },
    { title = "Slime Spray", flags = 0, spell = 28157,
      body = "Grobbulus sprays a cone of slime, inflicting Nature damage and spawning a Fallout Slime." },
  },
  [15932] = { -- Gluth
    { title = "Decimate", flags = 48, spell = 28374,
      body = "Gluth decimates the raid and his Zombie Chow, dropping everyone to a sliver of health. The zombies must be cut down before they reach and heal him." },
    { title = "Mortal Wound", flags = 1, spell = 25646,
      body = "Gluth's bite inflicts Mortal Wounds, a stacking debuff that reduces the healing his tank receives." },
    { title = "Terrifying Roar", flags = 32, spell = 14100,
      body = "Gluth lets out a terrifying roar, causing nearby players to flee in fear." },
    { title = "Zombie Chow", flags = 32, spell = 0,
      body = "A steady stream of Zombie Chow shambles toward Gluth; any that reach him heal him substantially." },
  },
  [15928] = { -- Thaddius
    { title = "Polarity Shift", flags = 32, spell = 28089,
      body = "Thaddius assigns every player a positive or negative charge. Like charges amplify one another; opposite charges are lethal on contact — the raid must split by polarity instantly." },
    { title = "Chain Lightning", flags = 0, spell = 421,
      body = "Thaddius unleashes chain lightning that arcs across the raid, inflicting Nature damage to all it strikes." },
    { title = "Stalagg & Feugen", flags = 32, spell = 0,
      body = "Thaddius is guarded by the constructs Stalagg and Feugen, who must be slain within seconds of each other; their Power Surge and Static Field punish the raid until both fall." },
  },
  [15989] = { -- Sapphiron
    { title = "Frost Aura", flags = 0, spell = 28529,
      body = "Sapphiron radiates a Frost Aura, inflicting constant Frost damage to the entire raid — frost resistance is essential." },
    { title = "Frost Breath", flags = 16, spell = 0,
      body = "From the air, Sapphiron exhales a catastrophic Frost Breath across the chamber. Only players sheltered behind a block of ice survive it." },
    { title = "Icebolt", flags = 32, spell = 28522,
      body = "During his flight phase, Sapphiron entombs players in blocks of ice, which then serve as cover against his Frost Breath." },
    { title = "Life Drain", flags = 256, spell = 28542,
      body = "Sapphiron drains the life of several players at once, healing himself for the damage dealt." },
    { title = "Blizzard", flags = 32, spell = 0,
      body = "Sapphiron conjures roaming blizzards that inflict heavy Frost damage to any caught within them." },
  },
  [15990] = { -- Kel'Thuzad
    { title = "Frostbolt", flags = 64, spell = 28478,
      body = "Kel'Thuzad hurls a massive Frostbolt at the raid, inflicting heavy Frost damage." },
    { title = "Frost Blast", flags = 16, spell = 27808,
      body = "Kel'Thuzad encases a player in frost, freezing them solid and spreading lethal cold to anyone standing near them." },
    { title = "Chains of Kel'Thuzad", flags = 32, spell = 28410,
      body = "Kel'Thuzad enslaves several players with shadowy chains, turning them against the raid until the chains are broken." },
    { title = "Shadow Fissure", flags = 32, spell = 27810,
      body = "Kel'Thuzad opens shadow fissures beneath the raid; any player still standing over one when it erupts is slain." },
    { title = "Frostbolt Volley", flags = 0, spell = 28479,
      body = "Kel'Thuzad looses a volley of frostbolts, inflicting Frost damage to all nearby players." },
    { title = "Mana Detonation", flags = 0, spell = 27820,
      body = "Kel'Thuzad detonates the mana of the raid's casters, inflicting Arcane damage based on the amount destroyed." },
  },

  -- Scholomance (instance 289)
  [10506] = { -- Kirtonos the Herald
    { title = "Curse of the Eye", flags = 256, spell = 3360,
      body = "Kirtonos curses a player with the eye, transforming them into a ghostly form and stripping their abilities for a time." },
    { title = "Wing Buffet", flags = 1, spell = 18500,
      body = "Kirtonos buffets the area before him with his wings, inflicting Physical damage and knocking players back." },
    { title = "Swoop", flags = 0, spell = 5708,
      body = "Kirtonos swoops at his target, inflicting Physical damage and stunning them briefly." },
  },
  [10503] = { -- Jandice Barov
    { title = "Illusions", flags = 32, spell = 0,
      body = "Jandice cloaks herself in invisibility and conjures a host of illusionary copies. The raid must find and strike the true Jandice among them." },
    { title = "Curse of Blood", flags = 256, spell = 8282,
      body = "Jandice curses a player's blood, increasing the Physical damage they take." },
    { title = "Banshee Wail", flags = 64, spell = 16565,
      body = "Jandice looses a banshee's wail at an enemy, inflicting heavy Shadow damage." },
  },
  [11622] = { -- Rattlegore
    { title = "Cleave", flags = 0, spell = 797,
      body = "Rattlegore's massive blade cleaves all enemies before him for tremendous Physical damage." },
    { title = "War Stomp", flags = 32, spell = 0,
      body = "Rattlegore stomps the ground with bone-crushing force, stunning all nearby players." },
  },
  [10433] = { -- Marduk Blackpool
    { title = "Whirlwind", flags = 0, spell = 1680,
      body = "The Black Guard Marduk spins in a whirlwind, inflicting Physical damage to all nearby players." },
    { title = "Cleave", flags = 0, spell = 797,
      body = "Marduk cleaves all enemies in front of him for heavy Physical damage." },
    { title = "Frenzy", flags = 2048, spell = 0,
      body = "Marduk works himself into a frenzy, increasing his attack speed and the damage he deals." },
  },
  [10432] = { -- Vectus
    { title = "Fire Shield", flags = 0, spell = 134,
      body = "Vectus surrounds himself with a shield of fire, inflicting Fire damage to any who strike him in melee." },
    { title = "Frenzy", flags = 2048, spell = 0,
      body = "Vectus flies into a frenzy, sharply increasing his attack speed." },
  },
  [10508] = { -- Ras Frostwhisper
    { title = "Frostbolt", flags = 64, spell = 116,
      body = "Ras Frostwhisper hurls a frostbolt at his target, inflicting Frost damage and slowing them." },
    { title = "Chill Nova", flags = 128, spell = 18099,
      body = "Ras Frostwhisper releases a nova of frost, inflicting Frost damage to nearby players and freezing them in place." },
    { title = "Fear", flags = 32, spell = 0,
      body = "Ras Frostwhisper strikes terror into the raid, causing nearby players to flee in fear." },
  },
  [10505] = { -- Instructor Malicia
    { title = "Flash Heal", flags = 68, spell = 2061,
      body = "Instructor Malicia channels a swift heal to restore her own health or that of an ally." },
    { title = "Curse of Agony", flags = 256, spell = 980,
      body = "Instructor Malicia curses a player with agony, inflicting escalating Shadow damage over time." },
    { title = "Mind Flay", flags = 64, spell = 15407,
      body = "Instructor Malicia flays a player's mind, inflicting Shadow damage and slowing them while channeled." },
    { title = "Renew", flags = 4, spell = 139,
      body = "Instructor Malicia renews herself or an ally, restoring health over time." },
  },
  [11261] = { -- Doctor Theolen Krastinov
    { title = "Rend", flags = 8192, spell = 772,
      body = "The Crimson Surgeon rends his target, inflicting Physical damage and causing them to bleed over time." },
    { title = "Backhand", flags = 0, spell = 6253,
      body = "Krastinov backhands his target, inflicting Physical damage and stunning them briefly." },
    { title = "Cleave", flags = 0, spell = 797,
      body = "Krastinov cleaves all enemies in front of him for heavy Physical damage." },
    { title = "Frenzy", flags = 2048, spell = 0,
      body = "Krastinov flies into a frenzy, butchering the raid with greatly increased attack speed." },
  },
  [10901] = { -- Lorekeeper Polkelt
    { title = "Volatile Infection", flags = 1024, spell = 3584,
      body = "Polkelt infects a player with a volatile disease, inflicting Nature damage over time." },
    { title = "Dark Plague", flags = 1024, spell = 12038,
      body = "Polkelt afflicts a player with a dark plague, a disease that festers and inflicts Nature damage over time." },
  },
  [10507] = { -- The Ravenian
    { title = "Trample", flags = 0, spell = 5568,
      body = "The Ravenian tramples the players around it, inflicting Physical damage to all nearby." },
    { title = "Cleave", flags = 0, spell = 797,
      body = "The Ravenian cleaves all enemies in front of it for heavy Physical damage." },
    { title = "Knockdown", flags = 0, spell = 5164,
      body = "The Ravenian knocks its target to the ground, stunning them briefly." },
  },
  [10504] = { -- Lord Alexei Barov
    { title = "Veil of Shadow", flags = 320, spell = 7068,
      body = "Lord Alexei Barov shrouds a player in a veil of shadow, sharply reducing the healing they receive." },
    { title = "Immolate", flags = 128, spell = 20800,
      body = "Lord Alexei Barov engulfs an enemy in flame, inflicting Fire damage instantly and additional Fire damage over time." },
    { title = "Shadow Shock", flags = 0, spell = 16583,
      body = "Lord Alexei Barov blasts nearby enemies with shadow energy, inflicting Shadow damage." },
  },
  [10502] = { -- Lady Illucia Barov
    { title = "Curse of Agony", flags = 256, spell = 980,
      body = "Lady Illucia Barov curses a player with agony, inflicting escalating Shadow damage over time." },
    { title = "Silence", flags = 128, spell = 6726,
      body = "Lady Illucia Barov silences nearby spellcasters, preventing them from casting for several seconds." },
    { title = "Fear", flags = 32, spell = 0,
      body = "Lady Illucia Barov strikes terror into the raid, causing nearby players to flee in fear." },
    { title = "Shadow Shock", flags = 0, spell = 16583,
      body = "Lady Illucia Barov blasts nearby enemies with shadow energy, inflicting Shadow damage." },
  },
  [1853] = { -- Darkmaster Gandling
    { title = "Shadow Portal", flags = 32, spell = 17863,
      body = "Darkmaster Gandling banishes a random player through a shadow portal into one of the side classrooms, sealing them in with a deadly summoned foe until it is slain." },
    { title = "Curse of the Darkmaster", flags = 256, spell = 0,
      body = "Gandling curses a player, weakening them with dark magic." },
    { title = "Arcane Missiles", flags = 0, spell = 5143,
      body = "Gandling channels a barrage of arcane missiles at his target, inflicting Arcane damage." },
    { title = "Shadow Shield", flags = 0, spell = 12040,
      body = "Gandling wraps himself in a shield of shadow, inflicting Shadow damage to any who strike him in melee." },
  },
}

NE.ej.ABIL = ABIL

-- Merge the seeded abilities into NE.ej.DATA. Only fills bosses that have no sections yet,
-- so a future Data.lua that ships real sections for an encounter wins automatically.
local function applyAbilities()
  local data = NE.ej.DATA
  if not data then return end
  for _, inst in ipairs(data.instances or {}) do
    for _, enc in ipairs(inst.encounters or {}) do
      local list = ABIL[enc.id]
      if list and (not enc.sections or #enc.sections == 0) then
        local secs = {}
        local n = #list
        for i, a in ipairs(list) do
          secs[i] = {
            id = enc.id * 1000 + i, title = a.title, parent = 0, child = 0,
            sib = (i < n) and (enc.id * 1000 + i + 1) or 0, order = i,
            spell = a.spell or 0, icon = a.icon or 0, flags = a.flags or 0,
            cdisp = 0, body = a.body,
          }
        end
        enc.sections = secs
        enc.rootSection = secs[1] and secs[1].id or 0
      end
    end
  end
end
applyAbilities()
