-- DOWNPORT: copied from NewEra (see ReferenceAddons); namespace localized to DragonUI_NewEra,
-- art paths re-pointed at DragonUI_NewEra\Textures\EncounterJournal. Content unchanged.
local NE = DragonUI_NewEra
-- Addon/EncounterJournal/PortraitOverrides.lua — wires the LOCALLY-GENERATED boss portraits
-- (the cmangos standin bosses that retail never gave an EJ portrait) into the journal WITHOUT
-- editing the auto-generated Data.lua. Generated by the /ne ejportrait capture pipeline (see
-- memory project_ej_boss_portraits): each model rendered on magenta, cut to a 128x64 BLP keyed
-- by its creatureDisplayID, shipped under Art/EncounterJournal/BossesGen/<displayID>.blp.
--
-- Mechanism: register each generated BLP under a local key == its displayID, then patch
-- NE.ej.DATA so every standin creature with a generated portrait resolves `file` to that key
-- (EncounterPage reads `NE.tex.localFiles[cr.file] or cr.file`). Survives a Data.lua re-gen
-- because it's an overlay applied at load (must load AFTER Data.lua in the TOC). Grows as more
-- batches (the wide/beast set) are generated — just add the displayIDs.

NE.ej = NE.ej or {}

-- displayIDs with a shipped BossesGen/<id>.blp.
local GEN = {
  -- humanoid batch (43)
  517, 1621, 2040, 2041, 2042, 2043, 2044, 2149, 2353, 2605, 2606, 3222, 3223, 3250, 4642,
  4939, 5266, 6097, 6110, 6124, 7970, 8055, 10248, 10901, 11069, 11070, 11072, 11073, 11288,
  11311, 11382, 11396, 11429, 11492, 11835, 15216, 15217, 15218, 15219, 15220, 15267, 15268, 15269,
  -- wide/beast batch (26) — first pass; some beasts pending per-model head tuning
  522, 524, 825, 1773, 1816, 2007, 2142, 2352, 2450, 2837, 4644, 4652, 4979, 5027, 7534, 7845,
  7864, 7919, 7971, 8390, 10433, 11179, 11611, 12073, 15288, 15295,
}

local _P = "Interface\\AddOns\\DragonUI_NewEra\\Textures\\EncounterJournal\\BossesGen\\"
local have = {}
for _, did in ipairs(GEN) do
  local path = _P .. did .. ".blp"
  if NE.tex and NE.tex.RegisterLocal then NE.tex.RegisterLocal(did, path) end
  if NE.ej.Preload then NE.ej.Preload(path) end
  have[did] = true
end

-- Patch the seeded data: point each standin creature at its generated portrait.
local function applyOverrides()
  local data = NE.ej.DATA
  if not data then return end
  for _, inst in ipairs(data.instances or {}) do
    for _, enc in ipairs(inst.encounters or {}) do
      local cr = enc.creatures and enc.creatures[1]
      if cr and cr.display and have[cr.display] and (cr.file == 521744 or not cr.file) then
        cr.file = cr.display
      end
    end
  end
end
applyOverrides()
