#!/usr/bin/env python3
"""Emit a Locales/<locale>.lua from enUS.lua plus a translation map.

enUS.lua is the manifest: this walks it in order, keeps its section headings, and writes each key
with either its translation or `= true` (AceLocale's "use the English key"). Driving the layout from
enUS means a translation file can never drift out of order or silently lose a key -- regenerate and
the diff is only the strings that changed.

Translations live in tools/locale-lint/translations/<locale>.py as `T = {raw_key: translated}`,
where raw_key is the key exactly as it appears between the quotes in enUS.lua.

    python tools/locale-lint/gen_locale.py deDE frFR ...
    python tools/locale-lint/gen_locale.py --all
"""

import importlib.util
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
LOCALES = os.path.join(ROOT, "Locales")
TRANSLATIONS = os.path.join(HERE, "translations")

HEADER = """--[[
================================================================================
DragonUI_NewEra - %(name)s (%(locale)s)

Generated by tools/locale-lint/gen_locale.py from enUS.lua; edit the translation
map in tools/locale-lint/translations/%(locale)s.py and regenerate, or correct a
string here and port the fix back. Entries left as `= true` fall back to English.

Machine-drafted and unreviewed by a native speaker: corrections welcome. Every
entry is checked against its English key for placeholder parity
(check_keys.py --verify), so a %%d or |n cannot go missing, but wording has not
been through a human pass.
================================================================================
]]

local L = LibStub("AceLocale-3.0"):NewLocale("DragonUI_NewEra", "%(locale)s")
if not L then return end
"""

NAMES = {
    "deDE": "German Locale", "esES": "Spanish Locale", "esMX": "Latin American Spanish Locale",
    "frFR": "French Locale", "koKR": "Korean Locale", "ptBR": "Brazilian Portuguese Locale",
    "ruRU": "Russian Locale", "zhCN": "Simplified Chinese Locale",
    "zhTW": "Traditional Chinese Locale",
}

KEYLINE = re.compile(r'^L\[(".*")\]\s*=')
STRPART = re.compile(r'"((?:[^"\\]|\\.)*)"')


def load_map(locale, _seen=None):
    """The locale's map, with any EXTENDS parent merged underneath it.

    esMX shares almost all of its wording with esES; carrying one full copy plus a short override
    map keeps the two from drifting apart on the 380 strings where they genuinely agree.
    """
    _seen = _seen or set()
    if locale in _seen:
        sys.exit("circular EXTENDS involving %s" % locale)
    _seen.add(locale)
    path = os.path.join(TRANSLATIONS, locale + ".py")
    if not os.path.exists(path):
        sys.exit("no translation map at %s" % path)
    spec = importlib.util.spec_from_file_location("tr_" + locale, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    table = {}
    parent = getattr(mod, "EXTENDS", None)
    if parent:
        table.update(load_map(parent, _seen))
    table.update(mod.T)
    return table


def emit(locale):
    table = load_map(locale)
    src = io.open(os.path.join(LOCALES, "enUS.lua"), encoding="utf-8", newline="").read()
    nl = "\r\n" if "\r\n" in src else "\n"
    lines = src.replace("\r\n", "\n").split("\n")

    out, body_started, used, problems = [], False, set(), []
    for line in lines:
        m = KEYLINE.match(line)
        if m:
            body_started = True
            key = "".join(p for p in STRPART.findall(m.group(1)))
            if key in table:
                used.add(key)
                raw = table[key]
                # Values are plain text: this escapes them, so a value that arrives pre-escaped
                # ends up with a visible backslash in game. That is invisible in the Lua source
                # (it parses fine) and only shows up on screen, so it is rejected here instead.
                if '\\"' in raw:
                    problems.append((key, raw))
                value = raw.replace("\\", "\\\\").replace('"', '\\"')
                # The key's own escapes are already Lua source; the value's are not -- except \n,
                # which is written as the two-character sequence and must survive as a Lua escape.
                value = value.replace("\\\\n", "\\n")
                out.append('L[%s] = "%s"' % (m.group(1), value))
            else:
                out.append('L[%s] = true' % m.group(1))
        elif body_started or line.startswith("-- ="):
            # Keep the section headings, drop enUS's own file header.
            if line.startswith("-- ") or line.strip() == "":
                out.append(line)
        # everything before the first key that isn't a heading is enUS's header: skipped

    if problems:
        print('  %s: %d value(s) contain a pre-escaped \\" -- write plain quotes, the generator'
              " escapes them:" % (locale, len(problems)))
        for key, value in problems:
            print("    %s" % key[:80])
            print("      %s" % value[:80])
        sys.exit(1)

    unknown = sorted(set(table) - used)
    if unknown:
        print("  %s: %d translation(s) for keys not in enUS.lua:" % (locale, len(unknown)))
        for k in unknown[:10]:
            print("    %s" % k[:90])

    header = HEADER % {"locale": locale, "name": NAMES.get(locale, "Locale")}
    text = header + "\n".join(out).rstrip("\n") + "\n"
    io.open(os.path.join(LOCALES, locale + ".lua"), "w", encoding="utf-8",
            newline="").write(text.replace("\n", nl))
    total = sum(1 for l in lines if KEYLINE.match(l))
    print("  %s: %d/%d translated" % (locale, len(used), total))


def main():
    args = sys.argv[1:]
    if not args:
        sys.exit(__doc__)
    if args == ["--all"]:
        args = sorted(f[:-3] for f in os.listdir(TRANSLATIONS)
                      if f.endswith(".py") and not f.startswith("_"))
    for locale in args:
        emit(locale)
    return 0


if __name__ == "__main__":
    sys.exit(main())
